### ISSUE TITLE
Comment: MAV lines - all three same color with style="Charles"

### ISSUE THREAD

**Issue by baqwas** [matplotlib/mplfinance#108]
LOW PRIORITY:
Perhaps an operator-user error here. Would love some guidance. The following code snippet results in the same color for the MAV lines and only the 50 & 100 are drawn.
```

		mpf.plot(daily_data, mav=(20,50,100), 
			title=filenm, type=plots[1], 
			ylabel="OHLC candles", ylabel_lower="Shared\nTrade", 
			savefig="./plots/"+t+".png", style="charles", volume=True)
```
![IBM-charles](https://user-images.githubusercontent.com/7071255/80283056-a0fab980-86da-11ea-8f3d-9838e0ac763f.png)
If I use the default style, the MAV lines have different colors (but still no 20 line):
![IBM-default](https://user-images.githubusercontent.com/7071255/80283080-c38cd280-86da-11ea-8686-5d8b28652397.png)

I prep the data with the following (apologies for the convoluted code):

`	series = [
		["TIME_SERIES_DAILY_ADJUSTED", "Time Series (Daily)"],
		["T3-20",	"Technical Analysis: T3"],	# triple exponential moving average
		["T3-50",	"Technical Analysis: T3"],
		["T3-100",	"Technical Analysis: T3"],	# time_period=200
		["MACD",	"Technical Analysis: MACD"],# moving average convergence / divergence
		["RSI-20",	"Technical Analysis: RSI"],	# relative strength index
		["RSI-50",	"Technical Analysis: RSI"],
		["RSI-100",	"Technical Analysis: RSI"],	# time_period=200[
		["ADX",		"Average Directional Movement Index (ADX)"],
		["AROON",	"Technical Analysis: AROON"],
		["BBANDS",	"Technical Analysis: BBANDS"],
		["OBV",		"Technical Analysis: OBV"],
		["STOCH",	"Technical Analysis: STOCH"]
		]
	ticker = ["MDB", "IBM"]
	plots = ["ohlc", "candle", "line", "renko", "pnf"]
	delim = "-"
	folder = "./data/"

	s = 0
	s0 = series[s][0]					# TIME_SERIES_DAILY_ADJUSTED
	for t in ticker:					# t = 0
		filenm = t + delim + s0 
		filenm_fullyqualified = folder + filenm
		dataset = filenm_fullyqualified + ".json"
										# meta data section of current json file
		daily_json = json.load(open(dataset))
		daily_head = pd.json_normalize(daily_json["Meta Data"], max_level=1).T
		daily_head.reset_index(drop=False, inplace=True)
		daily_head.rename(columns={"index":"key", 0:"value"}, inplace=True)
		daily_head['key'] = daily_head['key'].str[3:]
		current_ticker = daily_head.loc[daily_head["key"]=="Symbol", "value"].values[0]

										# time-series data section of current json file
		daily_data = pd.json_normalize(daily_json[series[s][1]], max_level=0).T
		daily_data.rename(columns={0:"ohlc"}, inplace=True)
		daily_data[['Open', 'High', 'Low', 'Close', 'Adjusted close',	# split list to multiple columns
			'Volume', 'Dividend', 'Split coefficient']] = pd.DataFrame(
			daily_data.ohlc.values.tolist(), index=daily_data.index)
		daily_data.drop(columns="ohlc", inplace=True)		# drop column used as list for split
		
										# datetime evaluations
		daily_data.reset_index(drop=False, inplace=True) # reapply index
		daily_data = daily_data.iloc[::-1]	# alphavantage to ascending order for mpl
		daily_data.rename(columns={"index":"Date"}, inplace=True)
		daily_data["Date"] = pd.to_datetime(daily_data["Date"])
		daily_data = daily_data.set_index("Date")
										# apparently the column split casts string values for new columns
		daily_data = daily_data.apply(lambda x: pd.to_numeric(x, errors='ignore'))`

Sample data can be obtained from:
[alphavantage demo data](https://www.alphavantage.co/query?function=TIME_SERIES_DAILY_ADJUSTED&symbol=IBM&outputsize=full&apikey=demo)

This is low priority inquiry while I read the docs and try out the various parameters for the plots. Thanks.

Kind regards.

**Comment by DanielGoldfarb** [comment]
Matha,

   You are not doing anything wrong.  That is fundamentally part of the "Charles" style, which is intended to somewhat resemble charts on schwab.com

![IBM_schwab_chart2](https://user-images.githubusercontent.com/11164790/80295498-126d5300-8741-11ea-8e43-7e7facab2200.jpg)

---

As you can see by the image from schwab.com they use the same color for the first two MAVs, and a different color for the next two.   [You can see this here in the configuration file for the "charles" style, where it says:](https://github.com/matplotlib/mplfinance/blob/master/src/mplfinance/_styledata/charles.py) 

    mavcolors     = ['#ef5714','#ef5714','#9f4878','#9f4878']

You can create your own style based on the "charles" style [as explained in the customization and styles tutorial](https://github.com/matplotlib/mplfinance/blob/master/examples/customization_and_styles.ipynb)
 
for example, you could write:

    s  = mpf.make_mpf_style(base_mpf_style='charles',mavcolors=['#1f77b4','#ff7f0e','#2ca02c'])

    mpf.plot(daily_data, mav=(20,50,100), 
			title=filenm, type=plots[1], 
			ylabel="OHLC candles", ylabel_lower="Shared\nTrade", 
			savefig="./plots/"+t+".png", style=s, volume=True)

**Comment by baqwas** [comment]
Thanks again, @DanielGoldfarb. I learn new things everyday (the "charles" part!). Your solution worked perfectly for my case. It also helped me to learn how to heap more data on a single chart.

Kind regards.

**Comment by azhar145** [comment]
Thank You. Colors worked llke a charm.
