### ISSUE TITLE
Feature Request: make mplfinance._styles public

### ISSUE THREAD

**Issue by char101** [matplotlib/mplfinance#110]
**Is your feature request related to a problem? Please describe.**
The line width and label size are hardcoded in the styles. When making small plots or very large plots, the line width and label sizes will be oversized/undersized.

Now, from what is seems, the manual way of sizing the line width and label sizes is to use the `style` parameter. The easiest way to do that is to modify the `dict` of existing style. `mplfinance._style` is available to load the existing styles, but it is marked as non public. I think it would be useful to make `mplfinance._styles` part of the public API for the reason previously specified.

**Describe the solution you'd like**
Make `mplfinance._styles` public -> `mplfinance.styles`

**Comment by char101** [comment]
Here is an example. It would be nice if the line width and label size could be autosized relative to the dimension of the plot though.

![AALI](https://user-images.githubusercontent.com/71255/80451101-32716200-894d-11ea-8e23-a5ed874811bc.png)

**Comment by char101** [comment]
One problem I encounter is that some style use `dict` style for the `rc` key while others uses `list` of `tuples`.

**Comment by char101** [comment]
After modifying the style

```python
style = _styles._get_mpfstyle('yahoo')
customize = {'font.size': 6, 'lines.linewidth': 1}
rc = style['rc']
if isinstance(rc, dict):
    rc.update(customize)
else:
    rc.extend((k, v) for k, v in customize.items())
```

![ABMM](https://user-images.githubusercontent.com/71255/80452253-0a373280-8950-11ea-9f5d-a24aa459de4b.png)

Unfortunately I still can't change the candle lines width, even after changing the `linewidths` parameter of the collection. Also the price and volume label is not vertically aligned.

**Comment by DanielGoldfarb** [comment]
Hi Charles,

   As noted at the bottom of **[the customization and styles notebook](https://github.com/matplotlib/mplfinance/blob/master/examples/customization_and_styles.ipynb)** , the method `mpf.make_mpf_style()` accepts the kwarg `rc=`.

Did you try using this??   For example:

    custom_rc = {'font.size': 6, 'lines.linewidth': 1}
    s =mpf.make_mpf_style(base_mpf_style='yahoo',rc=custom_rc)
    mpf.plot(df,...,style=s)

Did you try something like the above?   Does it work for you?

Thanks.  --Daniel

**Comment by char101** [comment]
It works, thank you. I haven't checked the notebooks because jupyter notebooks always failed to load in github (at least in my browser).

I'll close this issue.

**Comment by char101** [comment]
Just a note for anyone searching to align the y axis labels:

```python
fig, axlist = mpf.plot(..., returnfig=True)
if len(axlist) > 2:
    xpos = 1.1
    axlist[0].yaxis.set_label_coords(xpos, 0.5)
    axlist[2].yaxis.set_label_coords(xpos, 0.5)
```

**Comment by DanielGoldfarb** [comment]
@char101 
   Thanks.
