### ISSUE TITLE
Is it possible to do "bbox_inches='tight'" when saving a fig?

### ISSUE THREAD

**Issue by 3dvg** [matplotlib/mplfinance#117]
In mpl-finance, when saving an image **without** using `bbox_inches='tight'` saved the image with big white areas surrounding the plot, Just like what happens with the current mplfinance.

**How it should looks like with `bbox_inches='tight'`:** 
![descarga (2)](https://user-images.githubusercontent.com/32895945/80912801-f6b90c80-8d3f-11ea-876b-6a93c5929c39.png)

**How it looks like now:** 
![7e563426-ff13-467b-ae1c-238cde353116](https://user-images.githubusercontent.com/32895945/80912810-02a4ce80-8d40-11ea-92d7-0fb858599681.png)

Notice the **big white margins**

### Is there any way to achieve what `bbox_inches='tight'` does with the current mplfinance package?

**Comment by DanielGoldfarb** [comment]
I will look into this.  Possibly will do.  ( or it will become do-able through #17 )

**Comment by DanielGoldfarb** [comment]
@3dvg 
Eduardo
Yes, you can do this already.   See "**Specifying image attributes with savefig**" [**just below cell number 8 in this notebook**](https://github.com/matplotlib/mplfinance/blob/master/examples/savefig.ipynb) and see also **cell number 9** in the same notebook.

You can specify `bbox_inches='tight'` when using the `savefig` kwarg:

    mpf.plot( data, savefig=dict(fname='myfile',bbox_inches='tight') )
