### ISSUE TITLE
Feature Request: mpf.plot column names should be case-insensitive

### ISSUE THREAD

**Issue by josephjaspers** [matplotlib/mplfinance#118]
Hi, I am requesting that the default plot function be case-insensitive in regards to the columns names (open, close, high, low). 

Reasoning:

many times user's access dataframe columns via getattribute,
and python properties and variables should be lowercase (PEP8).
ergo, having lower case column names is more "pythonic". (Subjectively).

Thanks! Library has been great so far!

**Comment by DanielGoldfarb** [comment]
@josephjaspers 
Hi Joseph,
   Thanks for your interest in mplfinace and for your suggestion.   This has been discussed and [**there is an easy alternative here**](https://github.com/matplotlib/mplfinance/pull/73#issue-395338461).   The reason behind not defaulting to case insensitive is [**explained here**](https://github.com/matplotlib/mplfinance/issues/82#issuecomment-619585700).  Hope that helps.  All the best.  --Daniel
