### ISSUE TITLE
how to addplot with different lengths?

### ISSUE THREAD

**Issue by allahyarzadeh** [matplotlib/mplfinance#124]
I have plotted the normal data,
but there are some add_plots that are either shorter or longer which I want to plot on top of the main plot, now it complains about their length,
```
File "....Python\Python38\lib\site-packages\matplotlib\axes\_base.py", line 269, in _xy_from_xy
    raise ValueError("x and y must have same first dimension, but "
ValueError: x and y must have same first dimension, but have shapes (401,) and (171,)
```

although I could do this with normal plots easily by just plotting on top of the previous one to get some shapes like this :
![image](https://user-images.githubusercontent.com/11909557/81019102-970d4f00-8e6e-11ea-8cb6-28e4a273e2f2.png)

now for example I have this code:
```
 added_plots = [mplfinance.make_addplot(tcdfohlcv),
                           mplfinance.make_addplot(tcdfvalues),
                           mplfinance.make_addplot(tcdfpredicted)]
            mplfinance.plot(ohlc, addplot=added_plots, type='candle', volume=True, style='yahoo')
```
so tcdfohlcv is same size as ohlc data but tcdfvalues is smaller and tcdfpredicted is larger.
is there anyway I can plot these together?

**Comment by DanielGoldfarb** [comment]
@allahyarzadeh 
Reza,
I'm not 100% sure if this will work, but try filling the "missing data" with NaNs so that each addplot data set is the same length (same number of rows) as the original ohlc data set.  Let me know how that works.  If that doesn't work, please put your data (ohlc, tcdfohlcv, tcdfvalues, tcdfpredicted) somewhere that I can grab it, and I what solution I can come up with.  Thanks.  --Daniel

**Comment by DanielGoldfarb** [comment]
p.s. maybe, if tcdfpredicted is larger, you will have to fill out everything to be as long as tcdfpredicted.
Please let me know if that works.

**Comment by allahyarzadeh** [comment]
it seems to be ok, for smaller addplots,
but for the longer one it's pretty difficult , for starte how do I add np.nan to date list? I mean how to add date that doens't matter or I copy the last day and extend it with same value?

**Comment by allahyarzadeh** [comment]
Thank you @DanielGoldfarb  yes adding np.nan did the trick, I ended up copying the last date for those predicted date,
and also extending everything to the size of largest list, but could be a nice addition to have it as flag to pass to extend everything and fill nan.
![image](https://user-images.githubusercontent.com/11909557/81024150-36384380-8e7b-11ea-85b3-19ee7a496bfc.png)

**Comment by DanielGoldfarb** [comment]
I'm glad it worked.  It occurs to me now, that this NaN filling can be easily done using 

    newdf = pandas.merge(data,series,how='outer',on='Date',sort=True)`

and repeating for each `addplot` series that you want to plot.  I will consider maybe implementing some kind of a "fillnan" kwarg as you suggested.

**Comment by chuckf201** [comment]
Daniel: I decided to add RSI to panel-2 to keep my graph easy to read. I wanted to add to that panel buy and sell points but has an issue with sparse arrays for both 'buys' and 'sells'.
Panda.merge worked like a charm and gave me the panel presentation I needed.
`newDF = df2.loc[df2['rsi_signal'] == -1,['RSI']]
newDF_2 = pd.merge(df2,newDF,how='outer',on='Date',sort=True)

newDF_1 = df2.loc[df2['rsi_signal'] == 1,['RSI']]
newDF_3 = pd.merge(newDF_2,newDF_1,how='outer',on='Date',sort=True)`

So, thank you for all the work you do for all of us.

**Comment by DanielGoldfarb** [comment]
@chuckf201  ... you're welcome.  and thank you for your comment and for sharing your code; always good to see how folks are doing this stuff in practice.  much appreciate.
