### ISSUE TITLE
how to embed mplfinance to certain program in python?

### ISSUE THREAD

**Issue by bluesaturn1** [matplotlib/mplfinance#125]
Hi. 
It is very convenient and excellent.
It is well operated on Jupyter Notebook and Pycharm.
I want to embed into some program, not pop-up.
Is there any tip to embed on layout?

**Comment by DanielGoldfarb** [comment]
You should be able to embed using the kwarg `block=False` .   
**See these two comments here: https://github.com/matplotlib/mplfinance/issues/46#issuecomment-596155295 and https://github.com/matplotlib/mplfinance/issues/46#issuecomment-596209866**

You don't have to include the code discussed in those comments.  That code is now built into `mpf.plot()`.  **Simply call `mpf.plot(data,...,block=False)`**

Please let me know if that works for you.

**Comment by bluesaturn1** [comment]
Thanks. I am newbi.

I usually plot matplotlib item as below.

self.fig = plt.figure(figsize=(8, 5))
self.canvas = FigureCanvas(self.fig)
self.chartlayout.addWidget(self.canvas)
ax = self.fig.add_subplot(111)
ax = df.plot(data.......)
self.canvas.draw()

but mpf has inclued axes.
so I can't understand how to insert below code to canvas.

mpf.plot(daily,type='candle',mav=(5,20,60),volume=True)

**Comment by DanielGoldfarb** [comment]
I am not very familiar with embedding plots in gui applications, however I think what you need to do is set **`mpf.plot(returnfig=True)`**.  (I made a mistake above mentioning setting `block=False`; forget that.)

Try the following:  Do not create your own figure, but rather first call `mpf.plot()` and create your widget using the figure returned from `mpf.plot()`

    fig, axlist = mpf.plot(ohlcv_dataframe, figratio=(8, 5), returnfig=True)
    canvas = FigureCanvas(fig)
    chartlayout.addWidget(canvas)
    canvas.draw()

The above code is ***not*** exact.  As I said I am not familiar with this stuff, but you should be able to get the general idea from the above and modify the code accordingly for your needs.  Please let me know how it goes.

**Comment by bluesaturn1** [comment]
Thank you very much. Finally I can embed mpf chart to my program.

![20200506222820](https://user-images.githubusercontent.com/49546499/81182884-5d148800-8fe9-11ea-814e-81608748af9a.png)

![20200506222839](https://user-images.githubusercontent.com/49546499/81182898-60a80f00-8fe9-11ea-92fb-955e69e4485d.png)

But one more thing.
whenever I click button to see chart, image is getting more. 
I want delete previous image and plot new chart.

**Comment by DanielGoldfarb** [comment]
I'm not sure about that.  As previously mentioned, I have no experience embedding matplotlib plots in gui applications.  I imagine it depends on how your code responds to the button's click event.  And it seems to me your code is responding to the click by re-plotting the figure without closing the old one.  You may try modifying the button click handler to check if the plot has already been plotted and, if so, do nothing.

Alternatively, upon click, you may try closing the figure before plotting a new one.  If the data possibly has changed, then re-plotting may be what you want:

    plt.close(fig)

See also here: https://stackoverflow.com/a/11141305/1639359

**Comment by lignpeng** [comment]
very good！
mobai dalao!

**Comment by hmhjapan** [comment]
@bluesaturn1 
Could you publish all the Source Code？
I have the same problem. Refer to these Source Code,I still can't finish.
thank you!
