### ISSUE TITLE
Bug Report: min/max return NaN if nan in data, can use np.nanmin/np.nanmax instead.

### ISSUE THREAD

**Issue by DanielGoldfarb** [matplotlib/mplfinance#126]
**[From @char101](https://github.com/matplotlib/mplfinance/issues/116#issuecomment-623977064)**

> I have found one problem due to the usage of `min` and `max` on `ndarray` (https://github.com/matplotlib/mplfinance/blob/master/src/mplfinance/plotting.py#L424). If the array contains `nan` then both `min` and `max` will return `nan` so it should be replaced with `np.nanmin` and `np.nanmax`.

**Comment by char101** [comment]
Also in https://github.com/matplotlib/mplfinance/blob/master/src/mplfinance/plotting.py#L340

**Comment by DanielGoldfarb** [comment]
What this really comes down to is whether we will support data that includes some NaN values.  In general I want to support it.  In that regard, perhaps this should be an _enhancement_ to support NaN values.  

That said, this will require extensive testing to see which features work, and which do not, when some values are NaN.  

Will also have to figure out what to do if/when not all of OHLC are NaN for a given row, but only some of them are.  Do we treat it as if _all_ are NaN for that row if any one of them are?  Or maybe if any of OHL are NaN then we treat all three as NaN but we still allow use of Close for that row?

**Comment by char101** [comment]
A `nan` value in the OHLC data indicates invalid data. If there is at least one transaction then the value of OHLC should equal to the price of that transaction. If there is no transaction then all values should be `nan`.

I think this is a good case to show a warning to the user. And since the data point is invalid which means it cannot be graphed then it should be skipped.

**Comment by DanielGoldfarb** [comment]
@char101 
Charles,  I would like to get you feedback.  Here is what I have done so far, in my fork:
- fixed all `min/max` that could have NaN to use `np.nanmin/max`
- removed any code that was treating ` -1 ` as missing.
- there was some code from the old original_flavor that was checking to make sure that any missing points are missing for all O,H,L,C.  I changed that code to check for `NaN` instead of ` -1 ` it it works fine.  **As it always did, it raises an exception if missing data is not the same missing data** (i.e. missing for the same date) for all of O,H,L,C.

The only question now is how to handle moving averages which you mentioned.   If only one (or more) values in a given rolling window is NaN, then the moving average value will be NaN for that window at that date.  

As a test, I took a year's worth of data and set O,H,L,C for every 18th point to NaN.  If the `mav` rolling window period is less than 18, the moving average appears on the plot.  (Any rolling window of 18 or more results in ***all*** nans for the mav plot, so nothing appears).  

For periods less than 18, the mav curve appears only as segments.  And, as `mav` period increases, getting closer to 18, then the mav segments get smaller and smaller.  

---

Here is an example showing ` mav=(7,11,15) ` on data that contains a NaN value every 18th data point:

![nanmavs](https://user-images.githubusercontent.com/11164790/81607728-2650c000-93a3-11ea-8634-fa078e00381b.png)

**You can see** the mav segments for the 15 period moving average are only 3 days long, because there are only 3 days out of every 18 for which a 15 data point window does not contain any NaN values.  The question is what to do, **if anything**.

**Comment by char101** [comment]
How about `dropna` first then `reindex` like mentioned here https://stackoverflow.com/questions/56122660/pandas-rolling-mean-skipping-nans

That way the moving average lines will not have large gaps in the middle.

**Comment by DanielGoldfarb** [comment]
I was thinking of doing something like that.  Just not sure if the numbers will mean what people expect when viewing a moving average on a plot (especially if they make any trading decisions based on it).   I will play it and see how it looks.  Thanks for the idea and the reference.

**Comment by char101** [comment]
I think most trading charts skip days without data so it will replicate their ma lines.

**Comment by char101** [comment]
Hi,

The default value of `miss` is `-1` in https://github.com/matplotlib/mplfinance/blob/master/src/mplfinance/_utils.py#L47, I think it should be changed to `np.nan`.

**Comment by DanielGoldfarb** [comment]
> The default value of `miss` is `-1` ...

I've already changed this in the current set of enhancements that I hope to merge in the next couple of days.   ***Only NaN*** will count as missing data; all other values will be considered potentially valid data.

**Comment by DanielGoldfarb** [comment]
new version 0.12.5 just released to [Pypi](https://pypi.org/project/mplfinance/) fixes this
