### ISSUE TITLE
Feature Request: Plot to variable

### ISSUE THREAD

**Issue by tavurth** [matplotlib/mplfinance#130]
Hi, nice charts!

**Is your feature request related to a problem? Please describe.**
I'm saving a lot of charts to buffers and passing them around.
I'd like to be able to disable the "display by default" behaviour of the jupyter notebook.

I see that there's a shebang style `%%capture`, but is there any other way to accomplish the same with code?

An example would be:

Generate an array of images, and then return them.

At the moment this will display every image in the array when they're created, whereas I only want to display some of them later by `print(image)` them.

**Describe the solution you'd like**
I'd love to be able to simply return the generated chart as a `Pillow` image
I'd like to be able to prevent the image from displaying without using "%%capture"

**Additional information**
I'm trying to avoid this sort of double display.

<img width="713" alt="Screenshot 2020-05-09 at 21 37 24" src="https://user-images.githubusercontent.com/100964/81478454-52eac780-923d-11ea-8e17-39ba76b1ee88.png">

In my function when `capture=True` we return a PIL image, which can then be output to display. However the `mplfinance` has already displayed everytime!

**Comment by tavurth** [comment]
I figured it out:

```org
# Prevent figures from showing
%matplotlib agg
```

Will prevent the figures from matplotlib from showing automatically and simply return me my buffer.

**Comment by DanielGoldfarb** [comment]
@tavurth 
Will,
  Thanks for posting the answer you figured out.  Much appreciated.

    All the best.  --Daniel
