### ISSUE TITLE
How to calculate the indicator ATR(Average True Range)?

### ISSUE THREAD

**Issue by franklee00** [matplotlib/mplfinance#135]
and other technical analysis indicator, is there a list of them. thx.

**Comment by DanielGoldfarb** [comment]
@franklee00 
As noted in the **[Price Movement Plots](https://github.com/matplotlib/mplfinance/blob/master/examples/price-movement_plots.ipynb)** tutorial, when you request a Renko or Point and Figure chart, you can specify the `brick_size` (Renko) or `box_size` (Point and Figure) to ` 'atr' `.  

This tells mplfinance to calculate the ATR and use that as the brick or box size for these plots.  You can also specify the ` atr_length ` to indicate the time period over which to calculate the Average True Range.  See examples in the above mentioned tutorial for specifics.

If you want to see the actual value that was calculated, create an empty dict, and set kwarg `return_calculated_values` to this empty dict.  The dict will then be filled with various values that `mpf.plot()` calculates.  The ATR will be labeled ` size ` in the returned dict.  
For example:

    retvals = {}
    mpf.plot(data,type='renko', ..., return_calculated_values=retvals)
    print('ATR =',retvals[size])

I hope that helps.  All the best.  --Daniel

**Comment by franklee00** [comment]
> @franklee00
> As noted in the **[Price Movement Plots](https://github.com/matplotlib/mplfinance/blob/master/examples/price-movement_plots.ipynb)** tutorial, when you request a Renko or Point and Figure chart, you can specify the `brick_size` (Renko) or `box_size` (Point and Figure) to `'atr'`.
> 
> This tells mplfinance to calculate the ATR and use that as the brick or box size for these plots. You can also specify the `atr_length` to indicate the time period over which to calculate the Average True Range. See examples in the above mentioned tutorial for specifics.
> 
> If you want to see the actual value that was calculated, create an empty dict, and set kwarg `return_calculated_values` to this empty dict. The dict will then be filled with various values that `mpf.plot()` calculates. The ATR will be labeled `size` in the returned dict.
> For example:
> 
> ```
> retvals = {}
> mpf.plot(data,type='renko', ..., return_calculated_values=retvals)
> print('ATR =',retvals[size])
> ```
> 
> I hope that helps. All the best. --Daniel

thx

**Comment by camstuart** [comment]
In case anyone encounters this, more recent versions of mplfinance have this information in:

```python
print('ATR =', retvals['renko_size'])
```
