### ISSUE TITLE
Setting different alphas on different lines

### ISSUE THREAD

**Issue by Sile25** [matplotlib/mplfinance#139]
Hello! I was going through the various types of lines, i found that i can plot more lines with different colors at the same time, this is awesome! But can i do the same with the alpha value, such as setting a different alpha for different lines?

From the examples:
```
mpf.plot(df,
         type='candle',
         alines=dict(alines=seq_of_seq_repeat_point_in_between,
                     colors=['b','r','c'],
                     linewidths=40,
                     alpha=0.35),
         figscale=1.25
        )

```

**Comment by DanielGoldfarb** [comment]
This is not possible because the underlying **matplotlib** code will not accept alpha as a sequence (whereas it does accept colors as a sequence).

The only way to do this is if we modify the `alines` kwarg to also accept a sequence of dict's.

**Comment by Sile25** [comment]
Thank you @DanielGoldfarb ! I'm pretty sure i can do this by just assigning different colors too!

**Comment by DanielGoldfarb** [comment]
If different colors works for you (instead of different alphas) that's great.  Thanks.

**Comment by highwayroad** [comment]
Hi there, I would like to know if this possibility will be added for assigning different alpha values for alines?

**Comment by DanielGoldfarb** [comment]
@highwayroad 
See https://github.com/matplotlib/mplfinance/issues/554#issuecomment-1243150309

**Comment by ateeq-code** [comment]
it is possible daniel
