### ISSUE TITLE
how to change color of candle and MA lines？

### ISSUE THREAD

**Issue by leochan007** [matplotlib/mplfinance#14]
how to change color of candle and MA lines？

**Comment by DanielGoldfarb** [comment]
Coding of this enhancement is currently in progress.  Estimate 2 to 3 weeks until release.

**Comment by dodid** [comment]
Looking forward to it. Also I'd like to customize the size of the plot. Scaling with a fixed aspect ratio seems not sufficient...

**Comment by DanielGoldfarb** [comment]
noted.  i've been thinking about that (waiting for someone to mention it).  will probably do something to allow changing aspect ratio while adding the other customization stuff.

**Comment by DanielGoldfarb** [comment]
This is now released.  [See documentation here.](https://github.com/matplotlib/mplfinance/blob/master/examples/customization_and_styles.ipynb)

`pip install --upgrade mplfinance` to pick up the new version.

**Comment by chrsengel** [comment]
The above link does not work anymore. For everyone who's searching: [Working Link](https://github.com/matplotlib/mplfinance/blob/master/markdown/customization_and_styles.md)

**Comment by DanielGoldfarb** [comment]
@chrsengel  -- **Thanks!** ---

- [**See also here**](https://github.com/matplotlib/mplfinance/blob/master/markdown/customization_and_styles.md) (and fixed above link).
