### ISSUE TITLE
Editing background color of outer figure

### ISSUE THREAD

**Issue by Jacks349** [matplotlib/mplfinance#141]
I'm trying to edit the color of the outer space outside the chart, here is my chart:

![ONE](https://user-images.githubusercontent.com/65462643/82467012-6d386700-9ac1-11ea-9e6e-40fde32ec872.png)

Basically the background of the chart is blue, while the outer chart is black. I think i'm doing something wrong, because i tried this but i still got the same output:
```
# Create my own `marketcolors` to use with the `nightclouds` style:
mc = mpf.make_marketcolors(up='#00faf6',down='#ff0019',inherit=True)

# Create a new style based on `nightclouds` but with my own `marketcolors`:
s  = mpf.make_mpf_style(base_mpf_style='nightclouds',marketcolors=mc, gridstyle='', figcolor='#201D33', facecolor="#201D33", 
    rc={'axes.spines.bottom':False, 'axes.spines.left':False, 'axes.spines.right':False, 'axes.spines.top':False, 'font.size': 50})
```

**Comment by DanielGoldfarb** [comment]
Try adding ` 'figure.facecolor' : <color> ` to your ` rc= ` dict in `make_mpf_style()`

**Comment by DanielGoldfarb** [comment]
Actually, you are already doing ` figcolor='#201D33' ` which ***should*** do the same thing.  If that's not working, then there may be a bug.   Please let me know if adding ` 'figure.facecolor' : '#201D33' ` to your `rc` dict works.

**Comment by Jacks349** [comment]
I'm still not sure whether this is a bug or me doing something wrong. However, this seems to be happening with saved charts but not when the chart is opened by the library from your code. Adding `'figure.facecolor' ` does not seem to work

**Comment by DanielGoldfarb** [comment]
Aha!   I saw the same thing yesterday on something I was working on --- savefig (png) colors were definitely different from what was on screen.  

Have not had time to experiment with it.  Very possibly a **matplotlib** issue; but I wanted to run some tests first (perhaps see if I can reproduce with just a simple matplotlib plot) but I haven't had time.  

If you have some time, please check if .jpg has the same issue (savefig .jpg requires `pip install Pillow`).  Also, if you could check what version of matplotlib you have installed that would be helpful. 

Thanks.

**Comment by Jacks349** [comment]
Done! My matplotlib version is `matplotlib==3.2.1`. I tried to save it as JPG and the output was weird. Weirdly, i did not have to install Pillow, maybe i had it already installed?

Anyway, here is how i'm saving the chart:
`mpf.plot(df, type='candle', figscale=0.5, figratio=(50, 50), style=s, savefig="plottedCharts/myChart.jpg", alines=dict(linewidths=5, alpha=0.5, alines=walls, colors=colors))`

**Comment by DanielGoldfarb** [comment]
I just took the time to run a simple matplotlib test.  This appears **definitely a matplotlib issue.**

I will post it to matplotlib.  I do see some similar, but not same, issues there.

Will post a link here when done.

**Comment by Jacks349** [comment]
Awesome! Thank you a lot again @DanielGoldfarb !

**Comment by DanielGoldfarb** [comment]
### https://github.com/matplotlib/matplotlib/issues/17467

**Comment by Jacks349** [comment]
I will follow the issue! Thanks!

**Comment by Jacks349** [comment]
As mentioned [here](https://github.com/matplotlib/matplotlib/issues/17467), using `savefig.facecolor` worked flawlessly. Awesome! Thank you Daniel!

**Comment by DanielGoldfarb** [comment]
@Jacks349 
Yes, thanks.  Was about to post that.  Glad you saw it.  All the best.
