### ISSUE TITLE
Cropping space outside of the chart

### ISSUE THREAD

**Issue by Jacks349** [matplotlib/mplfinance#143]
Hello! I'm playing with Renko candles and i'm trying to correct a little detail on my chart: when i save the chart, there is always some free space outside of the chart, on the right. I would like to crop or fill that space, here is what i mean:

![q](https://user-images.githubusercontent.com/65462643/82755209-7fbce400-9dd2-11ea-8964-3e5483644906.png)

Here is how i generate the chart:
` mpf.plot(df, volume=Volume, type='renko', mav=MovingAverages, renko_params=dict(brick_size=brick_size), figscale=0.5, figratio=(50, 50), style=s, savefig="renkochart.png")`

I tried to change `figratio`, but of course it will only make the chart wider/higher, but it won't remove that space; is there any way to do this? Maybe i need to use MPL? By the way, the Renko charts generated by this library are awesome!

**Comment by DanielGoldfarb** [comment]
Hi @Jacks349 ,

Instead of: ` savefig="renkochart.png" `, 

try: ` savefig=dict(fname="renkochart.png",bbox_inches="tight") `.  

Let me know if that works.

--Daniel

**Comment by Jacks349** [comment]
Works flawlessly! Thank you a lot @DanielGoldfarb  !

**Comment by DanielGoldfarb** [comment]
@Jacks349 
Anytime.  By the way, I like the colors on your chart.  Nice choice!

**Comment by Jacks349** [comment]
@DanielGoldfarb Thank you! Yes, it looks good! Here are the colors i used, in case anyone wanted to replicate:
Background (chart and outer chart): #131722. Candle up: #00bed4, candle down: #EB4D5C. Created this stile on top of Nightclouds.

**Comment by DanielGoldfarb** [comment]
@ang-jason 
See [above](https://github.com/matplotlib/mplfinance/issues/143#issuecomment-633232845) regarding `bbox_inches="tight"` ***and*** see also **https://github.com/matplotlib/mplfinance/issues/212#issuecomment-655603896**.
