### ISSUE TITLE
plotting intraday candlesticks

### ISSUE THREAD

**Issue by pvenkate64** [matplotlib/mplfinance#144]
I had used the old mpl filnance some time back but gave up as it was not too helpful for intra-day candlestick plotting without using tedious code. I did browse the new mplfinance at a high level, but I believe I only saw daily OHLC data being used in examples.. Please tell me I did not look too closely :)

Thanks,
Prasanna

**Comment by DanielGoldfarb** [comment]
Prasanna,

Take the full 5 minutes to read all of the **[REAME](https://github.com/matplotlib/mplfinance/blob/master/README.md)** ... there are a couple of examples of intraday plots towards the bottom third of the README file.  I hope after that you will find it worth your while to read all of [**the tutorials**.](https://github.com/matplotlib/mplfinance#tutorials)

All the best.   --Daniel
