### ISSUE TITLE
how to plot more than 3 ma line? 

### ISSUE THREAD

**Issue by leochan007** [matplotlib/mplfinance#15]
now, i got an exception:
ValueError: kwarg "mav" with invalid value: "(5, 20, 60, 90)"
    def _mav_validator(mav_value):
    '''
    Value for mav (moving average) keyword may be:
    scalar int greater than 1, or tuple of ints, or list of ints (greater than 1).
    tuple or list limited to length of 3 moving averages (to keep the plot clean).
    '''
    if isinstance(mav_value,int) and mav_value > 1:
        return True
    elif not isinstance(mav_value,tuple) and not isinstance(mav_value,list):
        return False

    if not len(mav_value) < 4:
        return False
    for num in mav_value:
        if not isinstance(num,int) and num > 1:
            return False
    return True

**Comment by DanielGoldfarb** [comment]
Sorry, i arbitrarily limited it to 3.  Don't want the plots to get too crazy.   I will increase the limit to 7.

**Comment by DanielGoldfarb** [comment]
This is done and released.  
Run `pip install --upgrade mplfinance` to pick up the change.
