### ISSUE TITLE
Version 0.12.5

### ISSUE THREAD

**Issue by Shuffydog** [matplotlib/mplfinance#150]
Hi, I noticed there are comments regarding Version 0.12.5. When will this version be released ?

**Comment by Shuffydog** [comment]
I was reading the release notes for your very useful work with mplfinance. I noticed the release notes say v0.12.5a0 Released Date 2020-05-24, but I cannot find this version. Is this a mistake ? if so could you please advise as to when you plan to release version v0.12.5a0?

**Comment by DanielGoldfarb** [comment]
Yes, due to unexpected circumstances, unrelated to this project, the release of v0.12.5 is delayed.  I am hoping to have it released sometime next week.

**Comment by DanielGoldfarb** [comment]
Thank you.  I have updated the release date to June 10.
