### ISSUE TITLE
Plot custom function on top of mplfinance axes

### ISSUE THREAD

**Issue by Yharooer** [matplotlib/mplfinance#157]
Hi,

Is it possible to plot candlesticks and a custom line on the same axes, something like:
```
mplfinance.plot(data[0:100], type='candle')
plt.plot(data[0:100].index, data[0:100].CustomFunction)
```
where the units of CustomFunction is in price, so it would be plotted on top of the candlestick chart.

Right now this plots the function on a new set of axes.

Thanks.

**Comment by DanielGoldfarb** [comment]
You should be able to do this **[using kwarg `addplot`](https://github.com/matplotlib/mplfinance/blob/master/examples/addplot.ipynb)**.  

You ***may*** need to include `secondary_y=False` in your call to `mpf.make_addplot()`, but try first without including it; that should work if indeed your CustomFunction results in data of the same order of magnitude as your prices.
