### ISSUE TITLE
Specified brick_size may not be larger than (50% of the close price range of the dataset) which has value: 0.001693

### ISSUE THREAD

**Issue by Jacks349** [matplotlib/mplfinance#159]
I'm trying to chart renko charts of some cryptocurrencies, but i keep getting the following error:
`Specified brick_size may not be larger than (50% of the close price range of the dataset) which has value: 0.001693`

```
URL = "https://api.binance.com/api/v1/klines?&symbol=ETHBTC&interval="+timeframe+"&limit=" + limit
            
ResultRaw = BU.get(URL, timeout=(10, 15)).content
Result = json.loads(ResultRaw)


for x in Result:
    TimeUnix = float(x[0]) / float(1000)
    K = datetime.datetime.fromtimestamp(TimeUnix)
    x[0] = K


#print(Result[-1][0])
df = pd.DataFrame([x[:6] for x in Result], 
                  columns=['Date', 'Open', 'High', 'Low', 'Close', 'Volume'])


format = '%Y-%m-%d %H:%M:%S'

df['Date'] = pd.to_datetime(df['Date'], format=format)
df = df.set_index(pd.DatetimeIndex(df['Date']))
df["Open"] = pd.to_numeric(df["Open"],errors='coerce')
df["High"] = pd.to_numeric(df["High"],errors='coerce')
df["Low"] = pd.to_numeric(df["Low"],errors='coerce')
df["Close"] = pd.to_numeric(df["Close"],errors='coerce')
df["Volume"] = pd.to_numeric(df["Volume"],errors='coerce')
```

I know it happens because cryptocurrencies markets can have very low prices, but is there any way to solve this?

**Comment by DanielGoldfarb** [comment]
Did you try specfying a brick size smaller than 0.001693 ?

**Comment by Jacks349** [comment]
Ok, it looks like i only had to set a lower `bricksize` to make it work. I'm trying to chart other markets with very low prices, and it looks like renko has some troubles with them :)

Same code but with `URL = 'https://api.binance.com/api/v1/klines?&symbol=HOTBTC&interval=30m&limit=1200'` gave me this:
![renkochart](https://user-images.githubusercontent.com/65462643/84131284-a4f15980-aa44-11ea-93e2-367e6715e102.png)

**Comment by DanielGoldfarb** [comment]
Try also `brick_size='atr'` and `atr_length='total'`.   How does that look?

**Comment by Jacks349** [comment]
@DanielGoldfarb it looks definitely better! Thank you a lot!

I'm closing this as the issue is fixed and it wasn't really related to the library, but more to the kind of data i was trying to chart. Thans again!
