### ISSUE TITLE
Changing spines color

### ISSUE THREAD

**Issue by Sile25** [matplotlib/mplfinance#167]
I'm trying to change the color of the frame around the chart, but i'm having an hard time finding the right `rc` parameter. Until now, i managed to remove them with `'axes.spines.bottom':False` but not to edit the appearance of the spines, how can i do that? Thanks in advance!

**Comment by DanielGoldfarb** [comment]
@Sile25 ,
As far as I can tell, there are no rcparams for spine color, only booleans to turn the spines off or on, as you did:

    axes.spines.bottom
    axes.spines.left
    axes.spines.right
    axes.spines.top

It appears that the spine color can be changed by calling `Axes.spines[which].set_color()` where `which` is `'bottom'`, `'left'`, `'right'`, or `'top'`.

We could, in theory, add `spinecolor` to mplfinance styles, and then apply the color later in the code, after the axes are created.  I'm not sure how much of a demand there is for adjusting spine color, but if you wanted to write the code I don't think I would object.

In the meantime, as a workaround, you can have mplfinance return the figure and axes:

    fig, axes = mpf.plot(df,...,returnfig=True)

And then call `.spines.set_color(...)` on the appropriate axes object among the list of axes returned.

hth.  --Daniel

**Comment by DanielGoldfarb** [comment]
P.S.  If you only want to turn the spines off,  I believe you can turn off all spines at once by setting `axisoff=True` when you call `mpf.plot(df,...,axisoff=True)`

**Comment by DanielGoldfarb** [comment]
I did some poking around and found two rcparams that you can use:

    s = mpf.make_mpf_style(base_mpf_style='default',
                           rc={'axes.edgecolor':'lime','axes.linewidth':2}
                          )
    mpf.plot(df,style=s)

![image](https://user-images.githubusercontent.com/11164790/84423484-85953080-abec-11ea-8767-57d62f928280.png)

**Comment by Sile25** [comment]
> And then call `.spines.set_color(...)` on the appropriate axes object among the list of axes returned.

I was actually going to use it, but as you already mentioned, i can do it with rc params too! This library is insanely customizable! Thank you a lot Daniel!
