### ISSUE TITLE
Possible to have OHLC chart as Addplot?

### ISSUE THREAD

**Issue by luongjames8** [matplotlib/mplfinance#168]
Hi - this is a great package. Thanks for the work on it.

Is it possible to have two ohlc plots? I've setup an ohlc chart on panel 0. But when I try to create an ohlc chart on panel1, I get an error that there's no candle type on the addplot? 

Is the ohlc limited to main chart in panel 0? 

Sorry if I missed it in the documentation somewhere.

```
C:\ProgramData\Anaconda3\lib\site-packages\mplfinance\plotting.py in make_addplot(data, **kwargs)
    735         raise TypeError('Wrong type for data, in make_addplot()')
    736 
--> 737     config = _process_kwargs(kwargs, _valid_addplot_kwargs())
    738 
    739     # kwarg `type` replaces kwarg `scatter`

C:\ProgramData\Anaconda3\lib\site-packages\mplfinance\_arg_validators.py in _process_kwargs(kwargs, vkwargs)
    230                 import inspect
    231                 v = inspect.getsource(vkwargs[key]['Validator']).strip()
--> 232                 raise TypeError('kwarg "'+key+'" validator returned False for value: "'+str(value)+'"\n    '+v)
    233 
    234        # ---------------------------------------------------------------

TypeError: kwarg "type" validator returned False for value: "candle"
    'Validator'   : lambda value: value in valid_types },

```

**Comment by luongjames8** [comment]
Bump. 

Anyone can comment here? Is a second candle chart not allowed on panel 2? Or is there a simple fix?

**Comment by DanielGoldfarb** [comment]
It's not yet possible to have more than one panel of ohlc/candle.  Coming soon ... maybe a month or so.

**Comment by luongjames8** [comment]
Thank you Daniel for the response 👍

**Comment by DanielGoldfarb** [comment]
`pip install --upgrade mplfinance`

**Comment by luongjames8** [comment]
Works! Thank you!!!!

**Comment by Johnnee** [comment]
hi I got same issue, can new version add another ohlc plots? how to write it

**Comment by DanielGoldfarb** [comment]
@Johnnee ... yes this works, as indicated above as of June 24, 2020, just use `mpf.make_addplot()` to create additional OHLC or Candle charts in other panels (or on the same panel).   See, for example, `In [23]` in https://github.com/matplotlib/mplfinance/blob/master/examples/addplot.ipynb

**Comment by Johnnee** [comment]
> @Johnnee ... yes this works, as indicated above as of June 24, 2020, just use `mpf.make_addplot()` to create additional OHLC or Candle charts in other panels (or on the same panel). See, for example, `In [23]` in https://github.com/matplotlib/mplfinance/blob/master/examples/addplot.ipynb

Thanks, amazing work!
