### ISSUE TITLE
Is there any way to set the size of moving averages?

### ISSUE THREAD

**Issue by Sile25** [matplotlib/mplfinance#171]
Hello! I added MAs to my chart, but the problem is that in some parts of the charts they override the candles, since the moving average is too wide. Is there any way to set them smaller? I know i can set the color using `mavcolors=[]`, but `mavwidths=[]` doesn't work

**Comment by DanielGoldfarb** [comment]
I'm glad you brought this to my attention.   Version 0.12.5 introduced a new algorithm to calculate widths of candles, ohlc ticks, and volume bars, based on the density and other factors that affect which widths "look good."  

I now realize that I should have included mav ilnes, and `type='line'` lines in that calculation.  That will be done with the next release.   I will post here when it is relased and we will see if the moving averge is then not too wide.  There will also be a way to adjust the width if the algorithm doesn't get it quite the way you want.

**Comment by DanielGoldfarb** [comment]
**`mplfinance 0.12.5a3`** is now released on Pypi (`pip install --upgrade mplfinance`) and addresses this issue.  I expect that you will find the automatic adjustment of mav line widths to be adequate, but if not, please post here and I will direct you as to how to adjust them further.  Thank you.

**Comment by Sile25** [comment]
Thank you @DanielGoldfarb , this is exactly what i wanted! The new candle widths algorithm looks faboulous though!

**Comment by DanielGoldfarb** [comment]
@Sile25 - thanks for the feedback.  much appreciated.
