### ISSUE TITLE
Ability to depict candles as hollow/filled green and filled/hollow red candles?

### ISSUE THREAD

**Issue by eevark** [matplotlib/mplfinance#172]
Hello, love the new mplfinance charts. Is there any way to plot candles in 4 styles, e.g. hollow green for positive price change on the day and compared to the previous day, filled green for negative price change on the day and positive price change compared to the previous day, hollow red for positive price change on the day and negative price change compared to the previous day, filled red for negative price change on the day and compared to the previous day

Apologies if I have missed this in the documentation. Thanks, Ravi

**Comment by DanielGoldfarb** [comment]
I have seen the type of chart you are talking about.  Will look into making the enahncement.

**Comment by eevark** [comment]
Thank you for the quick response!

**Comment by soulmachine** [comment]
Currently the candlestick `mpf.plot(df, type='candle')` shows white and black candlesticks, while most people get used to red/green candlesticks, is there a way to config colors?

**Comment by DanielGoldfarb** [comment]
@soulmachine 
Frank,  Please read the documentation, for which there is a [**table of contents with links here.**](https://github.com/matplotlib/mplfinance#contents-and-tutorials)
Thanks.  All the best.  --Daniel

**Comment by kenorb** [comment]
> Currently the candlestick `mpf.plot(df, type='candle')` shows white and black candlesticks, while most people get used to red/green candlesticks, is there a way to config colors?

- See: https://github.com/matplotlib/mplfinance/blob/master/examples/styles.ipynb
- For red and green, you can use: `style='binance', type='candle'`.

**Comment by DanielGoldfarb** [comment]
This feature has been released.
```
pip install --upgrade mplfinance
python -c 'import mplfinance as mpf;print(mpf.__version__)'
0.12.7a7
```
[**Click here for examples and iformation**](https://github.com/matplotlib/mplfinance/blob/master/examples/hollow_and_filled_candles.ipynb).
