### ISSUE TITLE
Is there a way to have the grid set as background not foreground?

### ISSUE THREAD

**Issue by manuelwithbmw** [matplotlib/mplfinance#175]
Ask anything you want about mplfinance usage, project philosophy and/or priorities, or anything else related to mplfinance:

It seems grid lines overlap candles body when their colour is different, while they should just be hidden behind it (I should see in this example a full red body with no grey lines over it). Can we set this as background and not foreground, I don't think this is made on purpose? Thank you
![Screenshot 2020-06-15 at 10 12 47](https://user-images.githubusercontent.com/63164573/84640044-13c12d80-aef1-11ea-9b05-bb6e33299a97.png)

**Comment by DanielGoldfarb** [comment]
This was [requested already](https://github.com/matplotlib/mplfinance/issues/115#issuecomment-639446764), and [done here](https://github.com/matplotlib/mplfinance/pull/158/files#diff-450accb80db208ece0e75e2dbd950597R165-R166) (by the addition of kwarg `saxbelow` which defaults to True, but can be set to False for backwards compatibility).

Please double check that you are running `mpf.__version__` **0.12.5a2**

If your version is correct, then I may have a bug.  Please let me know.

**Comment by manuelwithbmw** [comment]
OK I was on 0.12.5a1, now upgraded to 0.12.5a2 and it is indeed fixed. TA
