### ISSUE TITLE
make_addplot Method Doesn't Work with Bollinger Band type='scatter' example

### ISSUE THREAD

**Issue by mostlycurious** [matplotlib/mplfinance#176]
Using the same code as in the Bollinger Band example in the tutorial "Adding plots to the basic mplfinance plot()" I got an error.

Preliminary code was:

import pandas as pd
import mplfinance as mpf
pth = 'Data\\mplfinance\\'
df = pd.read_csv(pth+'SPY_20110701_20120630_Bollinger.csv',index_col=0,parse_dates=True)

# This works fine
apdict = mpf.make_addplot(df['LowerB'])
mpf.plot(df,volume=True,addplot=apdict)

# This doesn't work. 
apd = mpf.make_addplot(df['LowerB'],type='scatter')
mpf.plot(df,addplot=apd)

The error stack is:
Traceback (most recent call last):
  File "C:\Users\(My Users Name)\Documents\Python\temp.py", line 20, in <module>
    apd = mpf.make_addplot(df['LowerB'],type='scatter')
  File "C:\Python38\lib\site-packages\mplfinance\plotting.py", line 661, in make_addplot
    config = _process_kwargs(kwargs, _valid_addplot_kwargs())
  File "C:\Python38\lib\site-packages\mplfinance\_arg_validators.py", line 221, in _process_kwargs
    raise KeyError('Unrecognized kwarg="'+str(key)+'"')
KeyError: 'Unrecognized kwarg="type"'

**Comment by DanielGoldfarb** [comment]
Sounds like you may have an older version of mplfinance.

**Comment by mostlycurious** [comment]
Thanks for responding so quickly.
I have version 0.12.4a0
By the way, what you're doing with this is awesome.

**Comment by mostlycurious** [comment]
You were right! I upgraded to -0.12.5a2 and the problem is gone.
Consider this case closed, and thanks again.
