### ISSUE TITLE
how can i show plot on tkinter

### ISSUE THREAD

**Issue by xiaofeng68** [matplotlib/mplfinance#178]
how can i show plot on tkinter.

```
    daily = LocalData.getInstance().data('000001',0)
    daily['Date'] = pd.to_datetime(daily['trade_date'])
    daily['Open'] = daily['close']
    daily['High'] = daily['high']
    daily['Low'] = daily['low']
    daily['Close'] = daily['close']
    daily.set_index(["Date"], inplace=True)
    daily.index.name = 'Date'
    mpf.plot(daily)
```

**Comment by DanielGoldfarb** [comment]
I am not familiar with TkInter, but I can show you what I have seen here in these discussions.
There appear to be two approaches:

1. Use `mpf.plot(data,...,returnfig=True)` to return the Figure and Axes, and use that Figure in TkInter.  An example of this approach can be found here:  **https://github.com/matplotlib/mplfinance/issues/125#issuecomment-624368289**  You can also see [**another example here**]( https://github.com/matplotlib/mplfinance/wiki/TkInter-Example).

2. Use `mpf.plot(data,...,savefig=buffer)` to save the figure image into an **io.BytesIO** buffer, and then pass that buffer to TkInter.  An example of this approach can be found here: **https://github.com/matplotlib/mplfinance/issues/170#issue-637905059**  (Please note: although that comment discusses a bug, *the example code is valid* and the bug only occurs if you use matplotlib's "TkAgg" bakcend.  But if you use any other matplotlib backend, it should work).   See also [this comment here](https://github.com/matplotlib/matplotlib/issues/17651#issuecomment-645070848).

I hope the above reference help you to find what you are looking for.
