### ISSUE TITLE
Trendlines

### ISSUE THREAD

**Issue by VaseSimion** [matplotlib/mplfinance#18]
Hi Daniel,

Thanks for the work you put into this. I tried working with it and I want to do something that I'm not sure it's supported. I want to draw trendlines over the graph (just have  list of values). Is this possible?

**Comment by DanielGoldfarb** [comment]
If you have you trendline values in a list, you can use `make_addplot()` (make additional plot).  See the documentation here: https://github.com/matplotlib/mplfinance/blob/master/examples/addplot.ipynb

**Comment by VaseSimion** [comment]
Hi Daniel,

Thanks a lot. I saw the function but didn't manage to find the details on how to work with it until you sent the link. Many thanks

**Comment by DanielGoldfarb** [comment]
closing as per above comments.  Thank you for your appreciation and interest in mplfinance.
