### ISSUE TITLE
Question Axisoff

### ISSUE THREAD

**Issue by brk030** [matplotlib/mplfinance#180]
Hello,

so I just tried using the argument axisoff = True. However, it zooms in the original picture making it look different. Attached you can find both versions. Why does that happen? Where is my mistake?

Thank you in advance and best regards. 
<img width="1210" alt="Screenshot 2020-06-18 at 17 33 18" src="https://user-images.githubusercontent.com/65129575/85041252-f5c22a00-b189-11ea-94f0-deca510f08bb.png">
<img width="1250" alt="Screenshot 2020-06-18 at 17 33 38" src="https://user-images.githubusercontent.com/65129575/85041264-fb1f7480-b189-11ea-8151-7b8211cf840f.png">

**Comment by DanielGoldfarb** [comment]
When axisoff was originally requested, by several people, they wanted also `axisoff` to show a tight layout.  At the time, kwarg `tight_layout` was not yet available for mplfinance.   This is why `axisoff` is effectively automatically doing `tight_layout` at the same time.  Unfortunately there is presently no way around this unless you want to tweak the code.

In the meantime, I think for the next release, I will make `axisoff` and `tight_layout` *more independent* ... although I may decide to still have axisoff default to tight_layout=True, but the user can override it with tight_layout==False; not sure yet, but at the very least you ***will*** be able to control it one way or the other.

**Comment by DanielGoldfarb** [comment]
Since coupling between otherwise independent kwargs is, imho, not good, I have decided to completely remove the coupling between  `axisoff` and `tight_layout` and make these two kwargs completely independent of each other.  The code has been changed in my fork and I expect to enter a PR (along with some other enehancements) sometime in the next few days.

**Comment by DanielGoldfarb** [comment]
`pip install --upgrade mplfinance`
