### ISSUE TITLE
How to use different types of alines in the same plot?

### ISSUE THREAD

**Issue by TigranGit** [matplotlib/mplfinance#184]
Hi,

I want to have some "zigzag" lines and horizontal lines with fixed length.
![1](https://user-images.githubusercontent.com/45096793/85204852-7585fb00-b328-11ea-9cd4-2551c9935c64.png)
![2](https://user-images.githubusercontent.com/45096793/85204855-79198200-b328-11ea-8e9a-af992644cc51.png)

Merge of this two.
The reason I don't use hlines is that I can't control their length. I want to limit them at some point.
I tried using 'seq_of_points' and 'seq_of_seq_of_points' for this task but got validation error.

` mpf.plot(data, alines=dict(alines=[zigzag, horizontals]))
`
Here is my code. When I run this I get an error: `TypeError: kwarg "alines" validator returned False for value: "{'alines': ([[[Timestamp('2020-04-28 16:59:59.999000'), 7753.77], [Timestamp('2020-04-29 09:59:59.999000'), 7753.77]], [[Timestamp('2020-04-29 09:59:59.999000'), 7863.0], [Timestamp('2020-04-29 11:59:59.999000'), 7863.0]], [[Timestamp('2020-04-28 18:59:59.999000'), 7683.41], [Timestamp('2020-04-29 11:59:59.999000'), 7683.41]]], [[Timestamp('2020-04-28 17:59:59.999000'), 7764.1], [Timestamp('2020-04-28 19:59:59.999000'), 7665.21], [Timestamp('2020-04-29 03:59:59.999000'), 7770.0], [Timestamp('2020-04-29 06:59:59.999000'), 7710.05], [Timestamp('2020-04-29 09:59:59.999000'), 7874.75]])}"
    'Validator'   : lambda value: _alines_validator(value) },`

But it works when I show only one of them.
zigzag is an array "seq_of_points"
horizontals is an array "seq_of_seq_of_points"

Regards,
Tigran

**Comment by DanielGoldfarb** [comment]
Tigran,
As indicated in the [documentation](https://github.com/matplotlib/mplfinance/blob/master/examples/using_lines.ipynb), the value for alines should be:

    a sequence of two or more date/price pairs, or
    a sequence of sequences of two or more date/price pairs

I think what you have is **a sequence of sequences of sequences** of two or more date/price pairs

One way you can see this is, if you carefully read the error message it says that the alines **validator returned False for value:** which is then followed by the value you passed in, surrounded by double quotes **( " )**.  If I take that entire string and pass it into pretty print (`import pprint`), the output looks like this:

    {'alines': ([[[Timestamp('2020-04-28 16:59:59.999000'), 7753.77],
              [Timestamp('2020-04-29 09:59:59.999000'), 7753.77]],
             [[Timestamp('2020-04-29 09:59:59.999000'), 7863.0],
              [Timestamp('2020-04-29 11:59:59.999000'), 7863.0]],
             [[Timestamp('2020-04-28 18:59:59.999000'), 7683.41],
              [Timestamp('2020-04-29 11:59:59.999000'), 7683.41]]],
            [[Timestamp('2020-04-28 17:59:59.999000'), 7764.1],
             [Timestamp('2020-04-28 19:59:59.999000'), 7665.21],
             [Timestamp('2020-04-29 03:59:59.999000'), 7770.0],
             [Timestamp('2020-04-29 06:59:59.999000'), 7710.05],
             [Timestamp('2020-04-29 09:59:59.999000'), 7874.75]])}

---

**If each one (zigzag and horizontals) is working fine separately, the try combining them like this:**

    my_alines = zigzag
    my_alines.append(horizontals)

    mpf.plot(data, alines=my_alines)

---

Notice in the example above, `my_alines` is not a dict, but is a sequence of sequences.  You don't need to set `alines` to a `dict` unless you want to pass additional attributes, for example:

    mpf.plot(data, alines=dict(alines=my_alines,color='g',linestyle='-.'))

Let me know if that works for you.  All the best.  --Daniel

**Comment by TigranGit** [comment]
Daniel, thank you very much! It worked for me.
But it's still mystery for me because I tried to concat them by adding (zigzag + horizontals) or ([zigzag, horizontals]) but only **append** worked perfectly.
Anyway, thank you, I really appreciate your work. Good luck in it!

Regards,
Tigran

**Comment by DanielGoldfarb** [comment]
I also would have thought that `zigzag + horizontals` would have worked, but I didn't take the time to investigate why **`append()`** works but **` + `**  doesn't.  When I have some more time I will look into it.

**Comment by DanielGoldfarb** [comment]
Tigran,

I figured it out.  As noted above. the `aline` specification must be either:

- **a sequence of two or more date/price pairs** (call this "**`sop`**"), or
- **a sequence of sequences of two or more date/price pairs** (call this "**`sosop`**")

***but it cannot be a mixture of both***.

Therefore, when you combine them, the result must be the "higher order" of the two, that is, 
***when you combine `sop` with `sosop`, the result must be an `sosop`*** (_not_ a mixture).

If you use **plus** to combine `sop` and `sosop`, 
the result is a _mixture_ of `sop` and `sosop`, which is no good.

**But if you surround the `sop` with square brackets so that it becomes an `sosop`**
Thus any of the the follow will work:

    alines = [sop] + sosop             # works
    alines = sosop + [sop]             # works
    alines = sosop.append(sop)         # works

    alines = sop + sosop               # does NOT work
    alines = sosop + sop               # does NOT work
    alines = sop.append(sosop)         # does NOT work

---

In your example `zigzag` is an `sop` and `horizontals` is an `sosop`, 
therefore each of the following will work or not work as indicated:

    alines = [zigzag] + horizontals            # works
    alines = horizontals + [zigzag]            # works
    alines = horizontals.append(zigzag)        # works

    alines = zigzag + horizontals              # does NOT work
    alines = horizontals + zigzag              # does NOT work
    alines = zigzag.append(horizontals)        # does NOT work

**Please let me know if you get a chance to check if the above is correct with your code.**

All the best.  Thanks.  --Daniel

**Comment by TigranGit** [comment]
Yeah, it worked as you described. Only one note, append doesn't return the list.
`alines = horizontals.append(zigzag) # does NOT work`

So need to do this:
```
horizontals.append(zigzag)
alines = horizontals
```
Regards,
Tigran
