### ISSUE TITLE
Make_Addplot Alpha and Width Kwargs not functioning

### ISSUE THREAD

**Issue by PowerrNuller** [matplotlib/mplfinance#185]
Hello, 

Please note the width and alpha arguments in are not functioning in the make_addplot function

addplot = [mpf.make_addplot(df['R'], type='line',secondary_y=True, ylabel='R', width= 0.1, alpha = 0.5)]

**Comment by DanielGoldfarb** [comment]
Width and Alpha kwargs were meant for `type=bar` charts.   We can enhance to affect lines as well, but there is also a separate [way to affect all lines widths](https://github.com/matplotlib/mplfinance/blob/master/examples/widths.ipynb).   It makes sense to have width and alpha affect  `make_addplot(...,type='lines',...) too.  Will add that.

**Comment by DanielGoldfarb** [comment]
`pip install --upgrade mplfinance`
