### ISSUE TITLE
Incorrect linestyles character for dotted

### ISSUE THREAD

**Issue by amiaty** [matplotlib/mplfinance#186]
Hello,

I think in valid_linestyles, '.' should change to ':', since mplfinance sent it to matplotlib, and matplotlib throws an error.

the correct character for dotted is ':'

https://matplotlib.org/3.1.0/api/_as_gen/matplotlib.lines.Line2D.html#matplotlib.lines.Line2D.set_linestyle

**Comment by DanielGoldfarb** [comment]
Amir,
  Thanks for pointing this out.
    All the best.  --Daniel

**Comment by DanielGoldfarb** [comment]
`pip install --upgrade mplfinance`
