### ISSUE TITLE
how to plot Vertical line based one day?

### ISSUE THREAD

**Issue by cvJie** [matplotlib/mplfinance#187]
how to plot Vertical line based one day?
I used the function API ：
mpf.plot(frame_data，addplot=self_data）

but I don't know how to Vertical line based X-axis？

thanks

**Comment by DanielGoldfarb** [comment]
Take a look at this tutorial: https://github.com/matplotlib/mplfinance/blob/master/examples/using_lines.ipynb

Let me know if you have any questions after going through that.   All the best.  --Daniel
