### ISSUE TITLE
Problem with using addplot()

### ISSUE THREAD

**Issue by AminSaqi** [matplotlib/mplfinance#189]
When some data points of an additional plot is out of the scale of the OHLCV plot, the library automatically adds another y scale to the right of the chart, and tries to show that additional plot within the main area. 

This behavior changes the representation of the chart. See the following for an example of this issue, while I'm trying to plot a channel:

![خاذین_روزانه_2020-06-25_raw](https://user-images.githubusercontent.com/39796124/85663255-1e887900-b6ce-11ea-8d5d-9c434f2201b9.jpg)

However, it performs as expected whenever the additional plot data is in range of the OHLCV plot. for example:

![کلوند_روزانه_2020-06-25_raw](https://user-images.githubusercontent.com/39796124/85663465-5d1e3380-b6ce-11ea-879f-d9df59258e1a.jpg)

How can I avoid the behavior in the first example and always plot like the second example?

Thanks in advance.

**Comment by DanielGoldfarb** [comment]
Please see here: https://github.com/matplotlib/mplfinance/blob/master/examples/addplot.ipynb 

Pleasr see the explanation after cell 15, and the examples through cell 18.  Hth.
