### ISSUE TITLE
Adjust the candle width

### ISSUE THREAD

**Issue by schorschie** [matplotlib/mplfinance#19]
Hello,

is there a possibility to adjust the candle width (1, 2, 4 hours etc.)?

regards

**Comment by DanielGoldfarb** [comment]
You should be able to do this using [`pandas.DataFrame.resample()`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.resample.html) before passing the data into `mpf.plot()`.    Let me know if you need more detail.

**Comment by DanielGoldfarb** [comment]
Additional information here:  [Resampling Time Series Data with Pandas](https://github.com/matplotlib/mplfinance/wiki/Resampling-Time-Series-Data-with-Pandas)

**Comment by schorschie** [comment]
Hello Daniel,
tank you, `DataFrame.resample()` works great! I already coded a loop, but your way is better:
```python
def adjust_candle_width(ticker_frame, sample_time='1D'):
    adj_ticker_frame = ticker_frame.resample(sample_time).agg({
        'Open': 'first',
        'High': 'max',
        'Low': 'min',
        'Close': 'last',
        'Volume': 'sum'
    })
    return adj_ticker_frame
```
