### ISSUE TITLE
Error adding 2nd panels 

### ISSUE THREAD

**Issue by hubofjon** [matplotlib/mplfinance#192]
Thank you for the package contribution. When I tried to follow sample code to add 2nd panel per instruction:
https://github.com/matplotlib/mplfinance/blob/master/examples/panels.ipynb

it gave errors: ValueError: kwarg "panel" validator returned False for value: "2""

after changing to panel='lower', it does display subplot.  looks the panel options available are limited to ['main', 'lower'], 
wondering if I missed anything when trying to add more than 2 panels (<10)

Thanks in advance
Jon

**Comment by DanielGoldfarb** [comment]
Sounds like you may have an older version of mplfinance installed.  Try

    pip install --upgrade mplfinance

Lmk.
