### ISSUE TITLE
Plot OHLCV from Binance

### ISSUE THREAD

**Issue by gambitov** [matplotlib/mplfinance#199]
I am trying to plot OHLCV from Binance, the estructure from the exchange is as follows:
```
[1550361600000, 3617.22, 3700.11, 3604.4, 3667.58, 25690.227779], 
[1550448000000, 3667.62, 3925.0, 3655.0, 3898.6, 64042.730492], 
[1550534400000, 3897.35, 3994.52, 3856.0, 3907.79, 50207.172667], 
[1550620800000, 3907.35, 3986.98, 3870.66, 3969.74, 36205.14085], 
[1550707200000, 3969.74, 4016.48, 3901.03, 3937.31, 31103.884728]
```
I am using `mpf.plot(data)` , but I get next error:

`TypeError: Expect data as DataFrame`

I think it needs a differente format, could you help me, please.

**Comment by DanielGoldfarb** [comment]
I am not familiar with Binance, but looking at the data you have, you can convert it into a DataFrame as follows:

**First, create a DataFrame from the data:**

    data = [
        [1550361600000, 3617.22, 3700.11, 3604.4, 3667.58, 25690.227779], 
        [1550448000000, 3667.62, 3925.0, 3655.0, 3898.6, 64042.730492], 
        [1550534400000, 3897.35, 3994.52, 3856.0, 3907.79, 50207.172667], 
        [1550620800000, 3907.35, 3986.98, 3870.66, 3969.74, 36205.14085], 
        [1550707200000, 3969.74, 4016.48, 3901.03, 3937.31, 31103.884728]
    ]

    import pandas as pd

    df = pd.DataFrame(data,columns=['Date','Open','High','Low','Close','Volume'])
    df.head()

                Date     Open     High      Low    Close        Volume
    0  1550361600000  3617.22  3700.11  3604.40  3667.58  25690.227779
    1  1550448000000  3667.62  3925.00  3655.00  3898.60  64042.730492
    2  1550534400000  3897.35  3994.52  3856.00  3907.79  50207.172667
    3  1550620800000  3907.35  3986.98  3870.66  3969.74  36205.140850
    4  1550707200000  3969.74  4016.48  3901.03  3937.31  31103.884728   

**Then convert the Date column from `epoch` to `Pandas.Timestamp`, 
and set the 'Date' column as the Index of the DataFrame:**

    import time
    import pandas as pd

    df['Date'] = df['Date'].apply(lambda date: pd.Timestamp(time.ctime(date/1000.)))
    df.set_index('Date',inplace=True)
    df.head()
                            Open     High      Low    Close        Volume
    Date
    2019-02-16 19:00:00  3617.22  3700.11  3604.40  3667.58  25690.227779
    2019-02-17 19:00:00  3667.62  3925.00  3655.00  3898.60  64042.730492
    2019-02-18 19:00:00  3897.35  3994.52  3856.00  3907.79  50207.172667
    2019-02-19 19:00:00  3907.35  3986.98  3870.66  3969.74  36205.140850
    2019-02-20 19:00:00  3969.74  4016.48  3901.03  3937.31  31103.884728

**Now pass the DataFrame into mplfinance:**

    mpf.plot(df)

**Let me know if that works for you, or if you have any questions about it.**

**Comment by gambitov** [comment]
Thank you for your answer. Do you know an indicator library? Such as kdj, macd, ADX, ema and so on.

**Comment by DanielGoldfarb** [comment]
I have never actually used any of the python technical analysis or indicator libraries.   Most of the indicators are really just a couple of lines of Pandas code.  You can see **[an example of using Pandas to calculate MACD, and plot using mplfinance, towads the bottom of this notebook here](https://github.com/matplotlib/mplfinance/blob/master/examples/panels.ipynb)**.

If you google "python market indicators" or "python technical analysis" you can see there are quite a few libraries, and documents on how to calculate the indicators.  One of the more popular ones is [**Darío López Padial's ta library**](https://github.com/bukosabino/ta).  
There is also [**tulipy**](https://github.com/cirla/tulipy) and [**stock market indicators**](https://github.com/voice32/stock_market_indicators).  
I can't comment on ease-of-use nor accuracy for any of these libraries, having never actually used them, nor tested them.

[**Here is an example of an artical that explains how to calculate many of the indicators yourself using Pandas.**](https://blog.quantinsti.com/build-technical-indicators-in-python/) 

HTH.  Let me know if you have any further questions.  All the best.  --Daniel

**Comment by manuelwithbmw** [comment]
> I have never actually used any of the python technical analysis or indicator libraries. Most of the indicators are really just a couple of lines of Pandas code. You can see **[an example of using Pandas to calculate MACD, and plot using mplfinance, towads the bottom of this notebook here](https://github.com/matplotlib/mplfinance/blob/master/examples/panels.ipynb)**.
> 
> If you google "python market indicators" or "python technical analysis" you can see there are quite a few libraries, and documents on how to calculate the indicators. One of the more popular ones is [**Darío López Padial's ta library**](https://github.com/bukosabino/ta).
I have used Dario López Padial's ta library and it works pretty well, I also congratulated him. It is exhaustive of many common indicators

**Comment by gambitov** [comment]
> mpf.plot(df)
@DanielGoldfarb, Thank you so much, it works perfect. 
I am actually testiting 
[](https://github.com/jealous/stockstats)

**Comment by gambitov** [comment]
> I am not familiar with Binance, but looking at the data you have, you can convert it into a DataFrame as follows:
> 
> **First, create a DataFrame from the data:**
> 
> ```
> data = [
>     [1550361600000, 3617.22, 3700.11, 3604.4, 3667.58, 25690.227779], 
>     [1550448000000, 3667.62, 3925.0, 3655.0, 3898.6, 64042.730492], 
>     [1550534400000, 3897.35, 3994.52, 3856.0, 3907.79, 50207.172667], 
>     [1550620800000, 3907.35, 3986.98, 3870.66, 3969.74, 36205.14085], 
>     [1550707200000, 3969.74, 4016.48, 3901.03, 3937.31, 31103.884728]
> ]
> 
> import pandas as pd
> 
> df = pd.DataFrame(data,columns=['Date','Open','High','Low','Close','Volume'])
> df.head()
> 
>             Date     Open     High      Low    Close        Volume
> 0  1550361600000  3617.22  3700.11  3604.40  3667.58  25690.227779
> 1  1550448000000  3667.62  3925.00  3655.00  3898.60  64042.730492
> 2  1550534400000  3897.35  3994.52  3856.00  3907.79  50207.172667
> 3  1550620800000  3907.35  3986.98  3870.66  3969.74  36205.140850
> 4  1550707200000  3969.74  4016.48  3901.03  3937.31  31103.884728   
> ```
> 
> **Then convert the Date column from `epoch` to `Pandas.Timestamp`, and set the 'Date' column as the Index of the DataFrame:**
> 
> ```
> import time
> import pandas as pd
> 
> df['Date'] = df['Date'].apply(lambda date: pd.Timestamp(time.ctime(date/1000.)))
> df.set_index('Date',inplace=True)
> df.head()
>                         Open     High      Low    Close        Volume
> Date
> 2019-02-16 19:00:00  3617.22  3700.11  3604.40  3667.58  25690.227779
> 2019-02-17 19:00:00  3667.62  3925.00  3655.00  3898.60  64042.730492
> 2019-02-18 19:00:00  3897.35  3994.52  3856.00  3907.79  50207.172667
> 2019-02-19 19:00:00  3907.35  3986.98  3870.66  3969.74  36205.140850
> 2019-02-20 19:00:00  3969.74  4016.48  3901.03  3937.31  31103.884728
> ```
> 
> **Now pass the DataFrame into mplfinance:**
> 
> ```
> mpf.plot(df)
> ```
> 
> **Let me know if that works for you, or if you have any questions about it.**

@DanielGoldfarb, Thank you so much, it works perfect.
I am actually testiting [https://github.com/jealous/stockstats](url)

**Comment by gambitov** [comment]
> I have never actually used any of the python technical analysis or indicator libraries. Most of the indicators are really just a couple of lines of Pandas code. You can see **[an example of using Pandas to calculate MACD, and plot using mplfinance, towads the bottom of this notebook here](https://github.com/matplotlib/mplfinance/blob/master/examples/panels.ipynb)**.
> 
> If you google "python market indicators" or "python technical analysis" you can see there are quite a few libraries, and documents on how to calculate the indicators. One of the more popular ones is [**Darío López Padial's ta library**](https://github.com/bukosabino/ta).
> There is also [**tulipy**](https://github.com/cirla/tulipy) and [**stock market indicators**](https://github.com/voice32/stock_market_indicators).
> I can't comment on ease-of-use nor accuracy for any of these libraries, having never actually used them, nor tested them.
> 
> [**Here is an example of an artical that explains how to calculate many of the indicators yourself using Pandas.**](https://blog.quantinsti.com/build-technical-indicators-in-python/)
> 
> HTH. Let me know if you have any further questions. All the best. --Daniel

@DanielGoldfarb, Thank you so much I tihink this library is very complete [Darío López Padial's ta library](https://github.com/bukosabino/ta)
