### ISSUE TITLE
Feature Request: Support for Exponential Moving Average

### ISSUE THREAD

**Issue by PowerrNuller** [matplotlib/mplfinance#206]
**Is your feature request related to a problem? Please describe.**
With mav built in - support for emav - exponential moving average would be nice - and I suppose easy to configure.

**Describe the solution you'd like**
Addition of emav as an argument to mpf.plot ***kwargs with support in mpf.make_mpf_style() to assign custom colors

**Describe alternatives you've considered**
Manually calculate and plot? Why not add it?

**Additional context**
Nope.

**Comment by DanielGoldfarb** [comment]
A reasonable request.   Regarding custom colors, is there any reason not to use the existing `mavcolors`?   Do people every want to plot both SMA and EMA?

**Comment by manuelwithbmw** [comment]
> A reasonable request. Regarding custom colors, is there any reason not to use the existing `mavcolors`? Do people every want to plot both SMA and EMA?

Not really, it is either SMA or EMA (or else), I personally prefer EMA, more adaptive. But it's a matter of 'tastes'

**Comment by PowerrNuller** [comment]
Yes - I think having that flexibility helps and keep the library dynamic to help different traders with different sytles

**Comment by farzinaa** [comment]
Has anyone managed to add the emav successfully? Thanks.

**Comment by manuelwithbmw** [comment]
Easy and well explained here
https://github.com/matplotlib/mplfinance/issues/506

**Comment by DanielGoldfarb** [comment]
Implemented: #563
