### ISSUE TITLE
Bug Report:The candle color is always 'down' color while open,close(& high,low) price are same

### ISSUE THREAD

**Issue by appleack** [matplotlib/mplfinance#207]
Hi , Sir / Miss,

The candle color is always 'down' color while open,close(& high,low) price are same.

For example:  I set the color 'up' as 'red' , 'down' as 'blue'.  it is always show 'blue' if the open, close(& high,low) price are same.  eg: open:100 ;  close: 100 ; high: 100 ; low :  100 / 95(any)

By right it should be 'red' if the open & close(they are same price as above case ) price greater than yesterday's (eg: yest price are : open: 80;  close:  82; high: 85; low :  78)

And it must be 'blue'  if open & close(they are same price as above case ) price less than yesterday's (eg: yest price are : open: 120;  close:  110; high: 125; low :  105)

Kindly check and fix it. Thanks for you concern.

Regards ,

Jimmy.

**Comment by DanielGoldfarb** [comment]
Jimmy,

When Open==Close, this is called a Doji candle.   Common practice is for Doji candles to have the same color as a down candle, as you can see here: http://www.chart-formations.com/candlestick-patterns/doji.aspx

On a *simple* or *filled* candlestick chart, which is what mplfinance supports, candle color is depends only on where each day's close is in relation to the open **of the same day**.  We do _not_ look at the day before. 

There is a different kind of candle chart, sometimes called four-color candlestick chart and sometimes called hollow candlestick chart, where the color and filling of the candle depends on two things: (1) where todays close is in relation to today's open, and (2) where today's close is in relation to yesterday's close.  There is a request to support hollow or four-color candles in mplfinance here: https://github.com/matplotlib/mplfinance/issues/172 but as of now it is not supported.

I hope that makes the issue clear.   All the best.  --Daniel

**Comment by appleack** [comment]
Hi Daniel,

Thanks for your prompt response . I got it and can share whether you are planning to support hollow  later ?

**Comment by DanielGoldfarb** [comment]
Yes, definitely plan to support hollow (four-color) candles.  Not sure when.   Maybe in 3 to 4 months.  Depends in part how much others people contribute to the code base here, and in part how much of my time is spent in this versus other projects.
