### ISSUE TITLE
Feature Request: Use the mouse to zoom(Ctrl + wheel) the candles along with volume, MACD etc  and move X axis (Press left button / CTRL + Left / right) 

### ISSUE THREAD

**Issue by appleack** [matplotlib/mplfinance#208]
Hi Daniel,
    May I know whether you are planning to add the function to zoom candles(along with volume, MACD etc) using mouse wheel(CTRL+wheel) .  And can move X axis while press mouse left  / ctrl+left or any other shortcut in order that we can easily view the candles after zoom.
  I know there is interactive navigation , but it is hard to use . And it's also have an 'issue' that can pull the line / candle to anywhere without restriction like below .Normally , we do not expect the pic out of view range.
 
Really appreciate you can make the figure friendly and easy to use with common shortcut.  

![image](https://user-images.githubusercontent.com/67829186/86528474-c118d700-beda-11ea-97c7-d0ea8758d907.png)

Yours sincerely,

Jimmy

**Comment by DanielGoldfarb** [comment]
JImmy,
Presently there are no plans to enable any zoom or panning functionality other than what comes standard with interactive matplotlib navigation.  There is some [**code suggested here,**](https://stackoverflow.com/a/11562898/1639359) and you are welcome to try to make it work in mplfinance.  Alternatively you may be able to find some other ways to implement shortcuts for panning and zooming.

I am not opposed to the idea, it is just not a priority for my goals for this library at this time.  If you or someone else want to implement it, I would consider merging it in.

All the best.  --Daniel

**Comment by tacaswell** [comment]
https://gist.github.com/tacaswell/3144287 is a slightly more maintained version of that code.  

I am also open to seeing that merged to upstream Matplotlib, but needs a bit of thought.
