### ISSUE TITLE
Feature Request: Allow plotting on the existing AXIS

### ISSUE THREAD

**Issue by joeatbayes** [matplotlib/mplfinance#209]
My existing plots directly use matPlotLib I want to add candle sticks to those graphs not have the candle stick take over. In the old api at mpl_finance it worked great I just passed in the axis of my existing work. You really should support the old strategy. I will just use the deprecated version until you do.

The old API  Allowed:
    fig = plt.figure(figsize=(14, 10))
    ax = plt.gca()  # Get current axis
    from mpl_finance import candlestick_ohlc
    candlestick_ohlc(ax, myBarData)

And it would would just add it's drawing to the existing graph.
The new version requires creating a panda data frame converting 
the datetime from string to panda index and then it created a 
entirely new figure popping up in a  different window.   I already
had my X axis labels they way I wanted them so you should not
render them.

**Comment by DanielGoldfarb** [comment]
Joe,

This is currently in development.  I hope to have it ready within the next 2 to 3 weeks. 

For more details, see [**The Matplotlib Method**](https://github.com/matplotlib/mplfinance/blob/master/markdown/subplots.md#the-matplotlib-method) under [Subplots in mplfinance](https://github.com/matplotlib/mplfinance/blob/master/markdown/subplots.md#subplots-in-mplfinance)

All the best.  --Daniel

**Comment by joeatbayes** [comment]
Perfect.

**Comment by mac133k** [comment]
Hi Guys,

What do you think about the idea, that the plot functions take matplotlib's fig and ax as parameters, and can also create new instances of those, so then it is possible to easily mix them in with more complex layouts. What I mean is:

```
def plot(..., fig=None, ax=None):
    if not fig and not ax:
        fig, ax = plt.subplots()
    
    # make the drawing
    ...
    return fig, ax
```

Then if you need just a single plot you call a function as usual and do not care about anything else, but when you need it as one of the subplots:

```
fig, axs = plt.subplots(3, sharex=True, ...)
mpl.plot(daily, type='candle', fig=fig, ax=axs[0]
axs[1].plot(something)
axs[2].plot(something_else)
```

This would provide more flexibility for embedding mpl plots into complex custom layouts and make use of the existing matplotlib functionalities without the need of wrapping.

Regards,
MS.

**Comment by DanielGoldfarb** [comment]
@mac133k 
That's almost exactly what is currently being developed, as mentioned above.  

Did you [**read this link**](https://github.com/matplotlib/mplfinance/blob/master/markdown/subplots.md#the-matplotlib-method) from [the comment above](https://github.com/matplotlib/mplfinance/issues/209#issuecomment-653952971)**?**

Also, for a long time now you can set `returnfig=True` when calling `mpf.plot()` and mplfinance will return the Figure and List of Axes it created, to allow you to further do what you want with them.  Did you see that?

**Comment by mac133k** [comment]
All right, that's cool. I didn't know about returnfig.

**Comment by DanielGoldfarb** [comment]
[**External Axes Mode**](https://github.com/matplotlib/mplfinance/blob/master/markdown/subplots.md#external-axes-method) is now available.
