### ISSUE TITLE
Possible to add descriptions in a panel

### ISSUE THREAD

**Issue by PowerrNuller** [matplotlib/mplfinance#210]
Hello, 

Is there any way to achieve a descriptive panel such as the one attached with the current library. 
![image](https://user-images.githubusercontent.com/66706903/86845641-ce1efd00-c077-11ea-9c19-2b021811d7c0.png)

**Comment by DanielGoldfarb** [comment]
The following workaround may work:   Read from cell **`In [12]`** through **`In [14]`** in the **[panels tutorial](https://github.com/matplotlib/mplfinance/blob/master/examples/panels.ipynb)** to see how you can create an empty panel.

Then call `mpf.plot()` with `returnfig=True`:

    fig, axlist = mpf.plot(df,...,returnfig=True)

This will return a tuple containing the figure ***and a list of axes*** in the following order:  two axes for each panel (primary and seconday) starting from the top panel down.  (Thus if there are four panels you will get back 8 axes instances in the list).

I suggest taking the primary axes for whichever panel you want, and place your annotations on it, or put an image on it.

Then call `plt.show()`

Please let me know if that works for you.

Thanks. --Daniel

**Comment by PowerrNuller** [comment]
Thanks. It seems to work.

**Comment by DanielGoldfarb** [comment]
@PowerrNuller 
Thanks for letting me know.  Would you please share here (or email me at dgoldfarb.github@gmail.com) an image of a plot you made with this technique?  I love seeing the creative things people are doing with mplfinance.
