### ISSUE TITLE
Bug Report: Alpha setting with Panel not working

### ISSUE THREAD

**Issue by PowerrNuller** [matplotlib/mplfinance#211]
**Describe the bug**
When Adding a plot mpf.make_addplot((df['SPY']),color='black',alpha=0.3,panel=0) the Alpha Setting is not reflected once Panel number is assigned. The line remains a solid black.

**To Reproduce**
1. Add Panel_ratios and num_panels to mpf.plot
2. Add apds = [mpf.make_addplot((df['SPY']),color='black',alpha=0.3,panel=0)]
3. Add addplot = pads to **kwargs

**Expected behavior**
Alpha setting to work

**Screenshots**
None

**Comment by DanielGoldfarb** [comment]
What version of mplfinance are you running?  `print(mpf.__version__)`

I believe this issue was fixed in version **`0.12.6`**

**Comment by PowerrNuller** [comment]
Yup its been fixed. TYVM.
