### ISSUE TITLE
Feature Request: Horizontal Lines in add subplot

### ISSUE THREAD

**Issue by strikar21** [matplotlib/mplfinance#215]
**Is your feature request related to a problem? Please describe.**
![image](https://user-images.githubusercontent.com/63551985/87662901-994e2c80-c780-11ea-8b56-eb959775e7df.png)

**Describe the solution you'd like**
i know rsi plots fine using the addsublpot method and fetching data from DataFrame.
however if i wanted to plot overbought/ oversold zones being represented with horizontal lines. 
the lines dont match up with the rsi levels.

**Describe alternatives you've considered**

**Additional context**
![image](https://user-images.githubusercontent.com/63551985/87663183-0e216680-c781-11ea-90a0-6ba82a2d7d42.png)

if i try to plot 20/80 as over sold and overbought zones.

**Comment by DanielGoldfarb** [comment]
duplicate of #140 

In the meantime, there is an easy workaround for this.  If `df` is your dataframe containing OHLCV data, then

    df['rsi_overbought'] = [70.]*len(df)
    df['rsi_oversold']   = [30.]*len(df)
    ap = mpf.make_addplot(df[ ['rsi_overbought','rsi_sold'] ])
    mpf.plot(df,...,addplot=ap)

HTH.   Thanks.  --Daniel

**Comment by strikar21** [comment]
> duplicate of #140
> 
> In the meantime, there is an easy workaround for this (which it looks like you have attempted, but you may need to add `secondary_y=False` to get it to look right).
> 
> If `df` is your dataframe containing OHLCV data, then
> 
> ```
> df['rsi_overbought'] = [80.]*len(df)
> df['rsi_oversold']   = [20.]*len(df)
> ap = mpf.make_addplot(df[ ['rsi_overbought','rsi_sold'] ], secondary_y=False)
> mpf.plot(df,...,addplot=ap)
> ```
> 
> HTH. Thanks. --Daniel

Thanks a Ton.
Works great.
