### ISSUE TITLE
Double Y Axis... Is it possible?

### ISSUE THREAD

**Issue by johnbest5673** [matplotlib/mplfinance#22]
Hi Daniel,

Is it possible to have 2nd Y-axis on the either side, along with the stock price? Basically, I am looking for the same feature, as I will plot some longitudes of planets to study the impact of these planets.

If you need a pic for what I am asking, here it is -
https://1.bp.blogspot.com/-3rN2z9PfuXE/XfyyxGjH_gI/AAAAAAAACRA/b6K06eP6h7w0_LLDJi6iN-C75H5mFHQXgCLcBGAsYHQ/s1600/NIFTY%2B-%2BDhuma-2.png

In the above pic, along with the candlestick chart you can see the planetary line, here only one is used, but I may require more.

Regards

**Comment by DanielGoldfarb** [comment]
Thanks for the picture.  That definitely helps.  Presently a secondary Y-axis is only available on the lower panel.  **[See this comment](https://github.com/matplotlib/mplfinance/issues/17#issuecomment-581095725)** for more detail.  **I expect the next release will allow a secondary Y-axes on both panels.**  

That said, the mplfinance code for additional plot data supports either a line plot or scatter plot.  **[See additional plot documentation here](https://github.com/matplotlib/mplfinance/blob/master/examples/addplot.ipynb).**  So it would work fine for the the green line in your picture, but I am unsure as to how best to support the vertical black bars in your picture.

That said, when `mpf.axplot()` is available (maybe another month) you will certainly be able to do this, but you will have to do on your own the matplotlib work needed to plot the additional data (the green line and the vertical black bars).  

All this can be done right now, with a bit of work, using the **[old api](https://github.com/matplotlib/mplfinance#oldapi)**

**Comment by johnbest5673** [comment]
Hi Daniel,

Thanks for the reply. No need to worry about the vertical black bars. They are simple vertical lines to denote the crossing of Green colored line and the horizontal ones. 

I will be watching the project and will wait for required plot. 

Thanks again for this wonderful project. :)

Regards

**Comment by DanielGoldfarb** [comment]
DONE.  **[See documentation here](https://github.com/matplotlib/mplfinance/blob/master/examples/addplot.ipynb).** towards the bottom.  `pip install --upgrade mplfinance` to pick up the enhancement.
