### ISSUE TITLE
Easiest way to add mav to volume

### ISSUE THREAD

**Issue by PowerrNuller** [matplotlib/mplfinance#220]
Hi - I can't find an intuitive way to add a moving average to the volume panel. A workaround is using make_addplot but wouldn't it be better to have a default setting tied to volume=True in **kwargs?

Apologies if this is already applicable.

**Comment by strikar21** [comment]
@PowerrNuller  hi

kindly go through the link below:
https://github.com/matplotlib/mplfinance/issues/216#issuecomment-659423317

**Comment by PowerrNuller** [comment]
Thanks. volmav would be ideal. I will close this for now.
