### ISSUE TITLE
fill_between in addplot

### ISSUE THREAD

**Issue by vvirball** [matplotlib/mplfinance#222]
I've been trying to use fill_between in a separate panel to identify bollinger bands and have been unable to do it. Is it possible or not? If it is possible can you tell me where I can get and example of information on how to do it?

Thank you for the work you're doing on mplfinance.

**Comment by DanielGoldfarb** [comment]
There are some `fill_between` examples toward the bottom of [**this tutorial notebook**](https://github.com/matplotlib/mplfinance/blob/master/examples/plot_customizations.ipynb).  

You can presently provide **only one** `fill_between` specification (however you can indicate which panel it should be on if you use the `dict` version of `fill_between` and provide `panel=<panel_id>` where panel_id is an integer from 0 to 9).

See also Issue #218 

There is also an example of using `fill_between` with Bollinger Bands **at** cell **`In [23]:`** in [**this scratch notebook**](https://github.com/matplotlib/mplfinance/blob/master/examples/scratch_pad/dev_fill_between.ipynb)

HTH.  LMK.  --Daniel

**Comment by vvirball** [comment]
Thanks for a very quick reply. I studied the example and ran into problems when I tried to include a fill_between clause in an add plot that had multiple phrases and 2 panels. I couldn’t get it to work. And I didn’t see an example for my specific use case. It would give a error that said it was missing a data value.

**Comment by DanielGoldfarb** [comment]
As noted on issue #218 mentioned above, fill_between does not yet work with addplot.

**Comment by vvirball** [comment]
Ah! I thought I looked at everything, but I missed that. Thanks. I'll stop beating my head against a wall.
