### ISSUE TITLE
Strange error at the end of my code using Mplfinance after reinstalling my Mac OS, any hints?

### ISSUE THREAD

**Issue by manuelwithbmw** [matplotlib/mplfinance#225]
**Ask anything you want about mplfinance usage, ....**

I now get a strange error at the end of my code using Mplfinance after reinstalling my Mac OS, any hints on how I can fix this?
Thank you

![Screenshot 2020-07-24 at 10 05 02](https://user-images.githubusercontent.com/63164573/88372108-96ad9180-cd95-11ea-9fdb-4dc4d6cfcf01.png)

**Comment by DanielGoldfarb** [comment]
Manuel,
I have no idea.  It doesn't appear to be related to `mplfinance` (although seeing the entire traceback may help verify that and/or determine where it was in the code when this error occured).

I tried googling `isPrefsCreateCacheFromEnabledAndDefaultInputSources` and found the following:

- https://stackoverflow.com/questions/53603246/strange-error-running-osascript-e-command-on-macos-mojave

It definitely appears to be more mac, or mac python related, than mplfinance, so if the above link (or the one's below) don't help, you might try on a mac related stackexchange or similar.

These links reference the one above for the fix:
- https://www.jamf.com/jamf-nation/discussions/30495/jamf-helper-can-t-find-anything-from-getinputsourceenabledprefs
- https://github.com/mikaelbr/gulp-notify/issues/128

HTH.  All the best.  --Daniel

**Comment by manuelwithbmw** [comment]
@DanielGoldfarb Hey Daniel, you spotted it perfectly.  I had indeed downgraded to a clean Mojave and adding/deleting the new keyboard has made the storage error disappear. Spot on! Thank YOU!
