### ISSUE TITLE
Is it possible to remove Y axis price data?

### ISSUE THREAD

**Issue by kitt-th** [matplotlib/mplfinance#226]
Greets,
1st, thanks for this library - it's awesome and I love it.

I have a perhaps a leftfield question in the opposite direction of most.

I'd like to remove the numerical price data on the Y axis of the main plot and subplot windows - is that possible?
My desired plot is simply the candles and other TA indicators without any price or indicator numerical data whatsoever.
I've looked through the documentation and couldn't find that.

Thanks.

**Comment by DanielGoldfarb** [comment]
Not 100% sure what you are getting at, but it sounds like you want something like this: https://user-images.githubusercontent.com/26544399/76427422-909db200-63ac-11ea-89d4-db9cc32dc00e.png

If so, you should be able to do this with `axisoff=True`.  See Issue #48 for more details.

**Comment by kitt-th** [comment]
yes, that's the problem I had - thanks!

**Comment by rogeliotg** [comment]
hi, axisoff=True removes axis completely, also vertical grid lines I'm interested in. Some way to draw these vertical grid dashed lines, for example for every week separator?

**Comment by DanielGoldfarb** [comment]
> hi, axisoff=True removes axis completely, also vertical grid lines I'm interested in. Some way to draw these vertical grid dashed lines, for example for every week separator?

This is not directly supported in mplfinance (nor do I expect it to be).   You can do this yourself directly through **Matplotlib** by gaining access to the Figure and Axes objects used by mplfinance.   There are two ways to gain this access: [**as described here**](https://github.com/matplotlib/mplfinance/issues/219#issuecomment-671292326).

Alternatively, I think this can alos be done through Matplotlib's `rcparams` settings.   First [read about Mplfinance styles here](https://github.com/matplotlib/mplfinance/blob/master/examples/styles.ipynb).  Then, when calling `mpf.make_mpf_style()`, use kwarg **`rc=`** to set whatever matplotlib `rcparms` you want .  (Note also: at the bottom of the [mplfinance styles notebook](https://github.com/matplotlib/mplfinance/blob/master/examples/styles.ipynb) there is a table of all possible kwargs to `make_mpf_style()` 

HTH.  Please keep me posted and let me know if ou have any further questions.  Thanks.

**Comment by rogeliotg** [comment]
thanks
