### ISSUE TITLE
How to Indicate Custom Column Names?

### ISSUE THREAD

**Issue by andresberejnoi** [matplotlib/mplfinance#23]
Is it possible to indicate custom column names for the OHLC data? I receive some candle data from Oanda as 'o','h','l','c', and volume: 'v'. However when trying to plot it will ask for names with uppercase as "Open","Low",etc. 

I would like to know if there is a way I can pass an argument indicating the naming convention I am using so that I don't need to modify the dataframe or saved files.

Thanks for developing this library. It makes plotting financial data so much easier than the old mpl-finance module.

**Comment by schorschie** [comment]
Hi, 

you could rename the columns with `DataFrame` and if you do it in the function call of `mpf.plot()`, then the changes wouldn't affect the original `DataFrame`. 

```python
import pandas as pd
import numpy as np

def some_fun(my_frame):
    print(my_frame)

a_frame = pd.DataFrame(np.random.rand(2, 4), 
                       columns=['o', 'h', 'l', 'c'])
print(a_frame)
some_fun(a_frame.rename(columns={'o': 'Open',
                                 'h': 'High',
                                 'l': 'Low',
                                 'c': 'Close'}))
print(a_frame)
```
regards
Gregory

**Comment by andresberejnoi** [comment]
Thanks. I will use that solution for now.

**Comment by DanielGoldfarb** [comment]
In addition to the above solution, would a kwarg to `mpf.plot()` as `colnames=dict(open='o',close='c',...)`  be ideally preferred to the above solution?

**Comment by andresberejnoi** [comment]
I think that addition would be great and make it more generalized

**Comment by schorschie** [comment]
Hello Daniel,

For me that would be a low priority Feature, since it wouldn‘t save that much typing in comparison to the posted solution.

In my use case I fetch the data from a SQLite database or yahoo finance and then I create and resample the Dataframe on the fly with the appropriate column names. 

Regards
Gregory

**Comment by DanielGoldfarb** [comment]
closing, but will leave it as a pinned issue, since @schorschie provided an excellent answer for all who have the same question.

**Comment by tioneb22** [comment]
The ability to provide custom column names would be a nice feature. Manipulating the dataframe before plotting is a good work around. Thanks for this thread!

**Comment by DanielGoldfarb** [comment]
@tioneb22 
Custom column names already exists thanks to @borgstrom (see PR #73)

In `mpf.plot()` just use kwarg `columns=(o, h, l, c, v)` where o,h,l,c,v are strings containing your own names for Open, High, Low, Close, and Volume.  In the `columns` kwarg, the names must be in that order (ohlcv), but they can be any strings that will match exactly to your dataframe's column names (and, of course, inside the dataframe the order does *not* matter, as long as those are the correct names in your dataframe).
