### ISSUE TITLE
Feature Request: plot specific points on graphics

### ISSUE THREAD

**Issue by alexandre-a** [matplotlib/mplfinance#231]
Is it possible to plot specific point in a graphic like with pyplot :
plt.scatter(x_min, y_min, color='green')

It would be very usefull to be able to add some signs on graphics. Is there a way to do that ?

**Comment by DanielGoldfarb** [comment]
Yes, this is possible.  Please read [**the addplot tutorial**](https://github.com/matplotlib/mplfinance/blob/master/examples/addplot.ipynb).  

See also [**this comment here**](https://github.com/matplotlib/mplfinance/issues/97#issuecomment-641385571) and its [**related examples here**](https://nbviewer.jupyter.org/github/matplotlib/mplfinance/blob/master/examples/scratch_pad/scatter_multiple_markers.ipynb).
