### ISSUE TITLE
Comment: Trade Markers?

### ISSUE THREAD

**Issue by DiSchi123** [matplotlib/mplfinance#242]
Great package!
I suppose in theory you could add trade markers into the chart, indicating buys and sells on the chart, on the candle, at a particular time  and price. Buys and sells can be either color coded or small upward/downward triangles.

Just wondering if someone has already done that work, perhaps leveraging the custom indicator functionality
(https://github.com/matplotlib/mplfinance/blob/master/examples/addplot.ipynb)

**Comment by DanielGoldfarb** [comment]
Hi Dirk,
Thanks.  There isn't a "Trade Marker" method per se, just the `make_addplot()` functionality.   

[**See also this comment**](https://github.com/matplotlib/mplfinance/issues/231#issuecomment-668865389) and the links therein.

Some people have gotten quite creative with `make_addplot()`, for example take a look at some of the images in [**this issue**](https://github.com/matplotlib/mplfinance/issues/97) such as [**this**](https://user-images.githubusercontent.com/49436733/79945165-84a61500-846d-11ea-8d7c-ec3ac876bdd5.png) and [**this**](https://user-images.githubusercontent.com/11164790/82761057-b04a5100-9dc5-11ea-93e2-dfba0ef00095.png).  Additional discussion [**here**](https://github.com/matplotlib/mplfinance/issues/49) too.

I've had in mind for a while to code something specific to trades and/or buy and sell signals, but it has not been a priority (and people are generally using the make_addplot functionality to do so.  There is also the issue of coming up with an interface for specifying trades/signals that, at least, most people would agree is convenient to use.

It should be easy enough to write a method, or kwarg, that takes a list of buys and sells, and optionally a color for buy and a color for sell (and shapes too?) and that method would then make the necessary make_addplot calls.  Are you interested in contributing this?

**Comment by DiSchi123** [comment]
Hi Daniel, thanks for the info. Let me spend some time to go through those links.  It looks like some people already have done similar things, potentially good enough for me.  As far as building it, I have to see, I doubt my skill level is up to it. But if I do build it I will make it available.

**Comment by DiSchi123** [comment]
This is for the most part covered under issue 49. 
https://github.com/matplotlib/mplfinance/issues/49
Closing.

**Comment by DiSchi123** [comment]
see above
