### ISSUE TITLE
plot candle sticks using numpy array data

### ISSUE THREAD

**Issue by tessanix** [matplotlib/mplfinance#243]
Hello!
I would like to know if it's possible to give a numpy array as parameter instead of a dataFrame in the mpf.plot(data) function.

**Comment by DanielGoldfarb** [comment]
What does your data look like?  Separate numpy arrays.  Or array of arrays?  Please show example data.  Thank you.

**Comment by tessanix** [comment]
thanks for the comment but I solved my issue. Now I'm using dataframes.
