### ISSUE TITLE
Candle stick colors incorrectly colored

### ISSUE THREAD

**Issue by lcobiac** [matplotlib/mplfinance#248]
Hi Daniel,

Im running the following code and getting incorrect colors for the cande sticks. Output and screenshot are given below. Please advise. 

Code
```
import mplfinance as mpf
import pandas as pd
print("mpf version:", mpf.__version__)

AAL_csv = pd.read_csv('./data/F.csv', index_col='timestamp', parse_dates=True)
print(AAL_csv.head())
mpf.plot(AAL_csv[['open', 'high', 'low', 'close']][-20:], type='candlestick', style='yahoo')
plt.show()
```
Output
``` 
mpf version: 0.12.7a0
            open  high    low  close    volume
timestamp                                     
2020-08-19  6.89  7.02  6.860   6.87  44158123
2020-08-18  6.98  7.01  6.885   6.89  40444196
2020-08-17  7.05  7.06  6.870   6.98  64307597
2020-08-14  6.97  7.11  6.930   7.04  43517662
2020-08-13  7.03  7.18  7.000   7.03  50066758
```
Screenshot of plot
![image](https://user-images.githubusercontent.com/35825667/91021291-bce37d00-e632-11ea-8fd5-2784ed9d9e0f.png)

**Comment by lcobiac** [comment]
I notice this is also the case in the screenshot in #247

**Comment by lcobiac** [comment]
I have realized there are no issues with the colors. My data is in reverse order when compared with the expected input.

**Comment by DanielGoldfarb** [comment]
> I have realized there are no issues with the colors. My data is in reverse order when compared with the expected input.

Thanks.   I should probably put a check in the code and issue a warning if the datetime index appears to be going in the wrong direction.

**Comment by lcobiac** [comment]
> > I have realized there are no issues with the colors. My data is in reverse order when compared with the expected input.
> 
> Thanks. I should probably put a check in the code and issue a warning if the datetime index appears to be going in the wrong direction.

Or automatically reverse the order of the data.
