### ISSUE TITLE
How to plot points on ohlc plot with diffrent shape?

### ISSUE THREAD

**Issue by Full4me** [matplotlib/mplfinance#249]
I have ohlc data(shape (720,)) and also some points (shape (110,)) which share dates, but data is not continous. And I have an error: 'ValueError: x and y must have same first dimension, but have shapes (720,) and (110,)'.

**Comment by DanielGoldfarb** [comment]
Create a shape with the larger (720) np.nan values and merge the smaller (120) into that based on the matching dates.

If you are not sure how to do that let me know and i will help.

Note: you must use **`nan`** values for the empty dates (***not*** `None` values)
