### ISSUE TITLE
Bug Report: Not being able to access addplot.ipynb on the github page, everything else works 

### ISSUE THREAD

**Issue by euler007** [matplotlib/mplfinance#255]
All docs seem to work fine except the addplot docs

![Screenshot 2020-09-03 at 11 55 10 AM](https://user-images.githubusercontent.com/20284507/92078697-53a2fd00-eddc-11ea-8889-6d2506e523ae.png)

**Comment by DanielGoldfarb** [comment]
@euler007 

Not sure why you closed this.  Perhaps it started working again?   
Or perhaps you did enough digging to determine that **this is actually a bug in the GitHub.com website!**

[**Please see this comment here**](https://github.com/iurisegtovich/PyTherm-applied-thermodynamics/issues/11#issuecomment-641407590) and the other comments on that page.  You can also Google `"Sorry, something went wrong. Reload?"` to see just how prevalent are complaints about this.  When the notebook display fails on GitHub.com then, as a workaround, you can use https://nbviewer.jupyter.org/ to view the notebooks online.  (Of course you can always clone the repository and view them locally on your own machine.)

Please, please, if you have some time, please do what you can to put pressure on GitHub.com to fix this bug, and ask others you know to do the same.

Thank you very much for your interest in mplfinance.  I hope you find it useful.  All the best.  --Daniel

**Comment by euler007** [comment]
@Daniel

Yes and yes, it did start working again and I also figures that this issue
is persistent on github. It's appaling how many people suffer from this
issue, it definitely has enough traction not sure why github does not
respond.

Appreciate all that you are doing. Thank you!

P.S I ended up downloading the repo and then went through the readme.
