### ISSUE TITLE
Animate the candle by aggregating tick value for a defined duration (1 min, 3 min, 5 min, 15 min etc) - without increasing the length of dataframe

### ISSUE THREAD

**Issue by centi1** [matplotlib/mplfinance#256]
Hi, How to view the price change within the candle in real time? Does the animation function in mplfinance support this feature?
we have the real time data coming in from an API & we have to plot that data by aggregating it & watching them real time in plot? 
The current animation is stopping at the end of the length of the given dataframe. 
Please suggest a way...

**Comment by DanielGoldfarb** [comment]
Hi @centi1 

Thank you for your interest in mplfinance.   It will help me to answer your questions if you can provide a little more clarity and perhaps some example data and/or code and describe what you are hoping to do with it.  For example, I don't understand what you mean by "... view the price change within the candle in real time?"

In the meantime, I will try to provide you with some help based on the limited information you have provided:

- Mplfinance's `mpf.plot()` will plot candles based on the data you give it, **one candle for each row of Open,High,Low,Close data**.  Any aggregation you want to do, you will have to do before passing the data to `mpf.plot()`, but aggregation is easy to do using Pandas.  There is [**some information about aggregating OHLC data here**](https://github.com/matplotlib/mplfinance/wiki/Resampling-Time-Series-Data-with-Pandas) ... (or just google 'aggregating time series data with pandas').

- Regarding **animation**, this is really [**a feature of Matplotlib**](https://matplotlib.org/3.3.1/api/animation_api.html).  Mplfinance merely gives you access to this Matplotlib feature by allowing you to pass Axes objects into mplfinance's API.  As you can see from the mplfinance animation examples ([demo1](https://github.com/matplotlib/mplfinance/blob/master/examples/mpf_animation_demo1.py), [demo2](https://github.com/matplotlib/mplfinance/blob/master/examples/mpf_animation_demo2.py), [macd](https://github.com/matplotlib/mplfinance/blob/master/examples/mpf_animation_macd.py)) **all of the code to create the animation is ***external*** to mplfinance.**

I hope the above information is helpful.  Please let me know if it works for you, or if you have further questions.

All the best.  --Daniel

**Comment by centi1** [comment]
Hi @DanielGoldfarb, 
       Thank you for your reply. I understood that the animation feature is from Matplotlib. And, i understood that the aggregation supposed to be handled before passing the data to mpf.plot(). 
        But my requirement of animation while plotting is, viewing the candle's progress based on the fresh data from a source(say API) . Now, I found a source to feed the data real time basis. But I failed to effectively handle it in different time frames. 
**lets take the example of 30 Minutes time frame :**
1. I have the past data for about a week for a particular stock/contract
2. I can effectively process the week's data for 30 minutes timeframe using "Existing OHLCV data to new OHLC data" (ie, 1 candle represents 30 Minutes) & pass it to mpf.plot() - lets say i have done it at 3:00 PM during market hours.
3. Now, I can view the chart with 30 minutes candle for the last week. But I need to view the candle from 3:00 PM to 3:30 PM as & when the data comes. lets say every 1 second the data needs to be refreshed and lets say, we are at 3:10 PM, the Open price of the candle will be the price exactly at 3:00 PM, The High Price of the candle can be the highest price between 3:00 PM and 3:10 PM, the low Price of the candle can be the lowest price between 3:00 PM and 3:10 PM,  the close price supposed to get refreshed for the new data coming in from the
![Annotation 2020-09-06 084539](https://user-images.githubusercontent.com/65355093/92326440-4a09d700-f020-11ea-9483-f23a64f088bb.png)
 source and it needs to show the last received price. 
It is very simple as this is how we used to see it in the Charting  platforms.

I am new to python, but i found it really useful as it helps to apply our own strategist instead of the regular ones offered by charting platforms. 
Now, i am struggling to get this animation working as i don't know how to handle the resampling of data for the last candle. 
Any suggestion in this regard will help me to figure it out quickly. 
for an easy understanding, i have illustrated the above in 3 different images in the attachment. Kindly look at it. 
Thank you...

**Comment by DanielGoldfarb** [comment]
@centi1 
Thanks.  That makes it very clear what you want to do.  I have some ideas how possibly to accomplish that, but I'm short on time right now.  I will try to respond fully within a day or two.  --Daniel

**Comment by centi1** [comment]
Thank you for considering this request...

**Comment by centi1** [comment]
May I request your help in this question @DanielGoldfarb?

**Comment by DanielGoldfarb** [comment]
Thanks for pinging me (This had fallen off my radar).

I have added an example to demonstrate what you want to do.  See https://github.com/matplotlib/mplfinance/blob/master/examples/mpf_animation_growingcandle.py

You can **`git clone`** this repository, and then **`cd mplfinance/examples`** and run **`python mpf_animation_growingcandle.py`** to run and watch the simulation.  Please read carefully the comments in the file.

Let me know if you have any questions.  And thank you so much for posting this question.  This was a very interesting one.

**Comment by centi1** [comment]
Dear @DanielGoldfarb,
      Thank you so much for the guidance. I have successfully integrated the code in my data feed & receiving candles. Now, I am trying to integrate the Volume & other strategies.
