### ISSUE TITLE
tkinter

### ISSUE THREAD

**Issue by swoloj** [matplotlib/mplfinance#261]
Ask anything you want about mplfinance usage, project philosophy and/or priorities, or anything else related to mplfinance.
it is posible to use tkinter with this library? I develop a front end for show avery single stock on market, but this library is really usufull.

    def insertoGrafico(self, lugarDondeVa, columna, fila): #(lugarDondeVa = PlaceWhereItGoes, Columne, File) and i use a class so self it's every where
        self.fig = plt.Figure(figsize=(5, 4), dpi=100) # defino la figura y le indico el tamaño
        self.ax = self.fig.add_subplot(111) # agrego los ejes y para meter cosas así los llamo ax
        
        self.canvas = FigureCanvasTkAgg(self.fig, master=lugarDondeVa)                  # Coloco la figura en lugar donde va (en este caso frame = tab1)
        self.canvas.get_tk_widget().grid(column = columna, row =fila)                   # le indico donde colocarlo dentro del sistema grid de tab1
        toolbar = NavigationToolbar2Tk(self.canvas, lugarDondeVa, pack_toolbar=False)   # agrega la barra de navegación
        toolbar.grid(column = columna, row =fila+1)                                     # Coloco la barra de navegación donde corresponde
        #toolbar.update()

        self.x = [0,1,2,3,4,5,6,7] #np.arange(0, 2*np.pi, 0.01)                         # Genero los datos de x
        self.y = [0,1,2,3,4,5,6,7] #np.arange(0, 2*np.pi, 0.01)                         # Genero los datos iniciales de Y
        self.line = self.ax.plot(self.x, self.y)

        self.anim = animation.FuncAnimation(self.fig, self.animate, np.arange(1, 200), interval=1000, blit=False) # funcion que me permite actualizar
                                                                                                                # el gráfico cada tantos ms todo lo que 
                                                                                                                #se quiera poner debe de ir en animate

it will be nice is i can declare an axis and add this mpl figure to this frame.
great job by the way

**Comment by DanielGoldfarb** [comment]
You can use mplfinance with TkInter.  There are multiple ways to go about this, including using the Figure returned from `mplfinance.plot()` to create your TkInter canvas, or creating your own Figure and Axes to pass into `mplfinance.plot()`.

Take a look at these comments here: **https://github.com/matplotlib/mplfinance/issues/178#issuecomment-645750460**

If you decide to create your own Figure, see also here: **https://github.com/matplotlib/mplfinance/blob/master/examples/external_axes.ipynb**
