### ISSUE TITLE
OHLC candle edge/wicks change colors (white->grey) as more points added to plot

### ISSUE THREAD

**Issue by luongjames8** [matplotlib/mplfinance#266]
I've been using the 'mike' style sheet as it seems to mimic the charting output from my terminal which is what I'm used to.

So for the 'mike' style the candle wicks and edges are #fffffff for both up and down. 

But as more and more points get added into a chart (and each candle gets smaller) the wicks start looking more and more grey.

I was wondering whether my eyes were just tricking me. But, on closer examination I can see that  edges/wicks is basically the same color now as the grid lines. A plot with a similar number of points from my terminal still has the edges/wicks as white.

I am not sure why it does this? Maybe there's a grey padding with white edge when the candles are larger. But as the candles get smaller, the white edge disappears and MPL renders the wick using the grey padding color. I don't know.

The effect is that the chart starts looking dull as more points are added from a loss of contrast between the edges and the background.

Can this be fixed at all?

**Comment by DanielGoldfarb** [comment]
Will try to make time to research this next week.  In the meantime a couple comments:

> So for the 'mike' style the candle wicks and edges are #fffffff for both up and down.

- wicks, yes; edges no.  (down is different for the edge).

It is possible that the edges are being decreased as the candle size is adjusted smaller to handle the case of a very large number of candles.  I'm not sure, would have to look closer at the code and run some tests (maybe next week).  In the meantime feel free to experiment with the code yourself.   See https://github.com/matplotlib/mplfinance/blob/master/examples/widths.ipynb and https://github.com/matplotlib/mplfinance/blob/master/src/mplfinance/_widths.py

Also, regarding ...

> I've been using the 'mike' style sheet as it seems to mimic the charting output from my terminal which is what I'm used to.

... which terminal would that be?

**Comment by luongjames8** [comment]
> wicks, yes; edges no. (down is different for the edge).

Sorry my mistake on this one. The down candle is blue and appears quite vibrant even when there are a lot of candles. 

When I say "a lot of candles" -- to be more precise, 6 months of daily the white edges looks fine. But as I increase to 7,8,9 months, the white edges look more and more grey.

> ... which terminal would that be?

Sorry. I thought it was obvious. I thought the Mike theme was named after the eponymous (Mike) Bloomberg terminal as the charting output looks nearly the same. 

Thanks, I'll take a look at the code and play with it a bit as well.

**Comment by DanielGoldfarb** [comment]
I did some playing around with this, and it is definitely the case that the apparent "gray"ness of the candles is the result of the candle edges and wicks becoming thinner.  

There is an algorithm that adjusts the appearance of the candles, ohlc bars, volume, etc. based mostly on the _density_ of the data. 
 Large amounts of data (higher density) can cause objects (such as candles, etc) to overlap somewhat if their sizes are not adjusted accordingly.

Unfortunately, the parameters that feed into the algorithm are a kind of _best-fit average_ of what looks OK across many different styles and data sets.  This means that _sometimes_ what looks good in one style, may be too thin or too thick in another style.  In theory the algoirthm could be enhanced to start with different sets of parameters for different styles.  This would certainly improve the algorithm.  In the meantime, it is possible to use certain kwargs to scale and/or adjust some of the parameters going into the "width adjuster algorithm" to hopefully suit your needs.

First a demonstration:  The images below were made with the same data, the first with 100 data points, and the second with 250 data points.  I then used the matplotlib zoom widget to zoom in to approximately the same 20 data points from each set.  You can clearly see that for the second data set (originally 250 points) the candle edges are noticibly thinner:  

![Figure_1](https://user-images.githubusercontent.com/11164790/94192697-4cbc5700-fe7d-11ea-99b2-ce3cc7d4a5c9.jpeg)

![Figure_2](https://user-images.githubusercontent.com/11164790/94192730-58a81900-fe7d-11ea-8ec8-97d88742f2ec.jpeg)

---

The thinner candle edges _do_ look better in _some_ styles, but clearly not so great in style "mike" (yes, named after Mike Bloomberg, just like style "charles" is named after Schwab).

---

Here are a couple of things you can try to see if, in your opinion, they improve the appearance of the high-density plots:

1. **`mpf.plot(data,...,width_adjuster_version='v0')`**  This uses the old/original width adjust algorithm, which does a lot less adjusting to the visual objects; but for your situation you may like the appearance.

2. **`mpf.plot(data,...,update_width_config=dict(candle_linewidth=0.7))`**  This will set the candle edges and wicks to the approximate size that they are when they are fewer than 100 data points.

Try each of the above two things independently (not together).  Let me know what you think.   

For more information see [**the widths tutorial**](https://github.com/matplotlib/mplfinance/blob/master/examples/widths.ipynb).

All the best.

**Comment by luongjames8** [comment]
Somehow I missed the email notification that you had replied to this issue already. 

The` width_adjuster_version='v0'` option seems to work the best for me.  I played around with adjusting the widths previously, but still noticed the 'greying' effect on the white candles no matter what settings I used.

Thank you!

**Comment by DanielGoldfarb** [comment]
I'm glad it helped.  (And I'm glad it occurred to me to continue to allow access to the old algorithm when I was implementing the new algorithm).
