### ISSUE TITLE
How to retrieve time series data from SQL Server and plot a candlestick chart

### ISSUE THREAD

**Issue by sunilfussey** [matplotlib/mplfinance#268]
I am able to access and retrieve data from SQL Server but unable to plot candlestick or other types of chart.  Request you to review and suggest changes to below code. Thanks a lot for your help and advise.

```python
import pandas as pd
import pyodbc 
import mplfinance as mpf

conn = pyodbc.connect('Driver={SQL Server};'
                      'Server=DESKTOPSK\SQLEXPRESS;'
                      'Database=NSESQL;'
                      'Trusted_Connection=yes;')

cursor = conn.cursor()

sql_query = '''SELECT TradeDate as Date,OpenPrice as [Open],HighPrice as High,LowPrice as Low,ClosePrice as [Close],TotalTradedQuantity as Volume 
             from dbo.SpotMarketData where tradedate>='01-Apr-2020' 
             and Symbol='BHEL' '''

Data = pd.read_sql(sql_query, conn,parse_dates=True)
Data.index.name = 'Date'
mpf.plot(pdata,type='candle')
```

***********
Below is the error message:

```
mpf.plot(pdata,type='candle')
Traceback (most recent call last):

  File "<ipython-input-66-e36f9c63b1e0>", line 1, in <module>
    mpf.plot(pdata,type='candle')

  File "C:\anaconda3\lib\site-packages\mplfinance\plotting.py", line 275, in plot
    dates,opens,highs,lows,closes,volumes = _check_and_prepare_data(data, config)

  File "C:\anaconda3\lib\site-packages\mplfinance\_arg_validators.py", line 29, in _check_and_prepare_data
    raise TypeError('Expect data.index as DatetimeIndex')

TypeError: Expect data.index as DatetimeIndex
```

*****************

Sample data given below:
data[0:5]
Out[68]: 
             Open   High    Low  Close    Volume
Date                                            
2020-04-01  20.65  21.20  20.40  20.70  15999994
2020-04-03  21.15  21.20  20.40  20.65  14724854
2020-04-07  21.05  21.45  20.85  21.30  18390253
2020-04-08  21.20  22.65  20.95  21.25  28424499
2020-04-09  21.65  22.65  21.40  22.35  28488302

![image](https://user-images.githubusercontent.com/71934449/94344097-943c1200-003a-11eb-8303-2ef9a1ea7e07.png)

**Comment by DanielGoldfarb** [comment]
Sunil,

Thank you for your interest in mplfinance. 
It seems to me that you need to add `index_col` kwarg to your `read_sql()` call:

```python
Data = pd.read_sql(sql_query,conn,parse_dates=True)
```

becomes:

```python
Data = pd.read_sql(sql_query,conn,index_col=0,parse_dates=True)
```

**Please let me know if that works.**
All the best.  --Daniel

**Comment by DanielGoldfarb** [comment]
Seems strange though as I look closer:  
Looking at [**your picture**](https://user-images.githubusercontent.com/71934449/94344097-943c1200-003a-11eb-8303-2ef9a1ea7e07.png) it **does appear** that the dates are the **index** of the dataframe.  
(Maybe they did not get properly converted?)

It still makes sense to me that you should have `index_col=0` in your call.

If the `index_col=0` suggestion does _not_ work, then please provide the output from:

```python
print(type(data.index))
print(type(data.index[0]))
```

**Comment by sunilfussey** [comment]
> Sunil,
> 
> Thank you for your interest in mplfinance.
> It seems to me that you need to add `index_col` kwarg to your `read_sql()` call:
> 
> ```python
> Data = pd.read_sql(sql_query,conn,parse_dates=True)
> ```
> 
> becomes:
> 
> ```python
> Data = pd.read_sql(sql_query,conn,index_col=0,parse_dates=True)
> ```
> 
> **Please let me know if that works.**
> All the best. --Daniel

Hi Daniel,
As suggested made the changes, and got some error as given below:


import pandas as pd
import pyodbc 
import mplfinance as mpf


conn = pyodbc.connect('Driver={SQL Server};'
                      'Server=DESKTOP-G5HM9SK\SQLEXPRESS;'
                      'Database=NSESQL;'
                      'Trusted_Connection=yes;')

cursor = conn.cursor()

sql_query = '''SELECT TradeDate as Date,OpenPrice as [Open],HighPrice as High,LowPrice as Low,ClosePrice as [Close],TotalTradedQuantity as Volume 
             from dbo.SpotMarketData where tradedate>='01-Apr-2020' 
             and Symbol='BHEL' '''


Data = pd.read_sql(sql_query, conn,index_col=0,parse_dates=True)
Data.index.name = 'Date'
mpf.plot(pdata,type='candle')
Traceback (most recent call last):

  File "<ipython-input-2-c52aba8ea77d>", line 13, in <module>
    Data = pd.read_sql(sql_query, conn,index_col=0,parse_dates=True)

  File "C:\anaconda3\lib\site-packages\pandas\io\sql.py", line 406, in read_sql
    return pandas_sql.read_query(

  File "C:\anaconda3\lib\site-packages\pandas\io\sql.py", line 1649, in read_query
    frame = _wrap_result(

  File "C:\anaconda3\lib\site-packages\pandas\io\sql.py", line 129, in _wrap_result
    frame.set_index(index_col, inplace=True)

  File "C:\anaconda3\lib\site-packages\pandas\core\frame.py", line 4303, in set_index
    raise KeyError(f"None of {missing} are in the columns")

KeyError: 'None of [0] are in the columns'

**Comment by sunilfussey** [comment]
> Seems strange though as I look closer:
> Looking at [**your picture**](https://user-images.githubusercontent.com/71934449/94344097-943c1200-003a-11eb-8303-2ef9a1ea7e07.png) it **does appear** that the dates are the **index** of the dataframe.
> (Maybe they did not get properly converted?)
> 
> It still makes sense to me that you should have `index_col=0` in your call.
> 
> If the `index_col=0` suggestion does _not_ work, then please provide the output from:
> 
> ```python
> print(type(data.index))
> print(type(data.index[0]))
> ```


In [3]: print(type(data.index))
   ...: print(type(data.index[0]))
Traceback (most recent call last):

  File "<ipython-input-3-60803f764003>", line 1, in <module>
    print(type(data.index))

NameError: name 'data' is not defined


In [4]:

**Comment by sunilfussey** [comment]
also adding the error message for above if index_col=0 is removed from the syntax: as given below:

In [11]: 
    ...: sql_query = '''SELECT TradeDate as Date,OpenPrice as [Open],HighPrice as High,LowPrice as Low,ClosePrice as [Close],TotalTradedQuantity as Volume 
    ...:              from dbo.SpotMarketData where tradedate>='01-Apr-2020' 
    ...:              and Symbol='BHEL' '''
    ...: 
    ...: 
    ...: Data = pd.read_sql(sql_query, conn,parse_dates=True)
    ...: Data.index.name = 'Date'
    ...: mpf.plot(Data,type='candle')
    ...: 
    ...: print(type(Data.index))
    ...: print(type(Data.index[0]))
Traceback (most recent call last):

  File "<ipython-input-11-c224999e77b9>", line 8, in <module>
    mpf.plot(Data,type='candle')

  File "C:\anaconda3\lib\site-packages\mplfinance\plotting.py", line 275, in plot
    dates,opens,highs,lows,closes,volumes = _check_and_prepare_data(data, config)

  File "C:\anaconda3\lib\site-packages\mplfinance\_arg_validators.py", line 29, in _check_and_prepare_data
    raise TypeError('Expect data.index as DatetimeIndex')

TypeError: Expect data.index as DatetimeIndex


In [12]:

**Comment by sunilfussey** [comment]
Hi Daniel, 
I am providing below the table structure and attaching the txt file containing sample data so that you can debug and check it in your PC. Create below table in SQL server and thereafter import the txt file data.

CREATE TABLE [dbo].[SpotMarketData](
	[Symbol] [varchar](25) NULL,
	[TradeDate] [date] NULL,
	[OpenPrice] [decimal](8, 2) NULL,
	[HighPrice] [decimal](8, 2) NULL,
	[LowPrice] [decimal](8, 2) NULL,
	[ClosePrice] [decimal](8, 2) NULL,
	[TotalTradedQuantity] [bigint] NULL
) ON [PRIMARY]
GO


[BHEL.txt](https://github.com/matplotlib/mplfinance/files/5293194/BHEL.txt)

**Comment by DanielGoldfarb** [comment]
Sunil,

The new error message you are getting with `index_col=0` is _not_ similar.  The new error is coming from **Pandas.read_csv()** because there is apparently no column '0'.   (The first error message was coming from mplfinance.plot() complaining that the index on the dataframe was not a DatetimeIndex).

I took another look at the [**`pandas.read_sql()` documentation**](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_sql.html).  I have never used `read_sql` (only read_csv) and I had assumed it was similar to read_csv in that the `index_col` could be both integer or str, but apparently `read_sql()` requires a string that matches a column name.  Therefore since your query says `"SELECT TradeDate as Date"` perhaps you can try **`index_col='Date'`**.  Let me know if that works.  

---

Regarding [this printout ***without*** index_col=0](https://github.com/matplotlib/mplfinance/issues/268#issuecomment-699986179) 
> ```python
> print(type(Data.index))
> print(type(Data.index[0]))
> <class 'pandas.core.indexes.range.RangeIndex'>
> <class 'int'>
> ```


The output clearly shows that Pandas.read_csv() converted the Date data into a **pandas.RangeIndex** instead of what mplfinance wants: a **pandas.DatetimeIndex**.  It is poosible that using `index_col='Date'` as suggested above will fix that.  

If not, I would need to see some of the actual data values to guess how to convert from the RangeIndex to the DateIndex.  Perhaps provde output from:

```python
print(type(Data.index))
print(type(Data.index[0]))
print(len(Data.index))
print(Data.index[0:4])
print(Data.index[-4:-1])
```
---

**[Thank you for posting the table schema and data here](https://github.com/matplotlib/mplfinance/issues/268#issuecomment-700066451).  That was a good idea.  If I have time tomorrow I will try to reproduce on my end.**  I'm a little short on time right now, so I only wrote the above suggestions hoping they would help.

All the best.  --Daniel

**Comment by sunilfussey** [comment]
Hi Daniel, As suggested I had run the code after adding index_col='Date' but it didn't work and shows same error (given below).  Also output required is given below:


In [1]: 
   ...: import pandas as pd
   ...: import pyodbc 
   ...: import mplfinance as mpf
   ...: 
   ...: conn = pyodbc.connect('Driver={SQL Server};'
   ...:                       'Server=DESKTOP-G5HM9SK\SQLEXPRESS;'
   ...:                       'Database=NSESQL;'
   ...:                       'Trusted_Connection=yes;')
   ...: 
   ...: cursor = conn.cursor()
   ...: 
   ...: sql_query = '''SELECT TradeDate as Date,OpenPrice as [Open],HighPrice as High,LowPrice as Low,ClosePrice as [Close],TotalTradedQuantity as Volume 
   ...:              from dbo.SpotMarketData where tradedate>='01-Apr-2020' 
   ...:              and Symbol='BHEL' '''
   ...: 
   ...: 
   ...: Data = pd.read_sql(sql_query, conn,index_col='Date',parse_dates=True)
   ...: Data.index.name = 'Date'
   ...: mpf.plot(Data,type='candle')
Traceback (most recent call last):

  File "<ipython-input-1-bcfb5c94deb6>", line 19, in <module>
    mpf.plot(Data,type='candle')

  File "C:\anaconda3\lib\site-packages\mplfinance\plotting.py", line 275, in plot
    dates,opens,highs,lows,closes,volumes = _check_and_prepare_data(data, config)

  File "C:\anaconda3\lib\site-packages\mplfinance\_arg_validators.py", line 29, in _check_and_prepare_data
    raise TypeError('Expect data.index as DatetimeIndex')

TypeError: Expect data.index as DatetimeIndex


In [2]: 
   ...: print(type(Data.index))
   ...: print(type(Data.index[0]))
   ...: print(len(Data.index))
   ...: print(Data.index[0:4])
   ...: print(Data.index[-4:-1])
<class 'pandas.core.indexes.base.Index'>
<class 'str'>
123
Index(['2020-04-01', '2020-04-03', '2020-04-07', '2020-04-08'], dtype='object', name='Date')
Index(['2020-09-23', '2020-09-24', '2020-09-25'], dtype='object', name='Date')

In [3]:

**Comment by DanielGoldfarb** [comment]
Sunil, 

This is interesting.   Previously you were getting
```python
<class 'pandas.core.indexes.range.RangeIndex'>
<class 'int'>
```
Whereas now with `index_col='Date'` you are getting
```python
<class 'pandas.core.indexes.base.Index'>
<class 'str'>
```
Furthermore, the `<class 'str'>` objects **do** look like dates, so it should be relatively easy to convert them to a pandas.DatetimeIndex.

**Please try the following and let me know if it works**:
Add `Data.index = pd.DatetimeIndex(Data.index.values)` immediately after the `read_sql(index_col='Date')`, thus:
```python
Data = pd.read_sql(sql_query, conn,index_col='Date',parse_dates=True)
Data.index = pd.DatetimeIndex(Data.index.values)
Data.index.name = 'Date'  # This line possibly is not necessary, but keep it for now until get this working.
mpf.plot(Data,type='candle')
```

---

Meanwhile, later today, I may have time to try to reproduce:  I am curious to investigate why it appears that `pd.read_sql(sql_query, conn,index_col='Date',parse_dates=True)` is ***not*** converting the dates to a pandas.DatetimeIndex, despite the fact that `parse_dates=True` is set.

**Comment by sunilfussey** [comment]
Hi Daniel, 
I had run similar code in plotly and it works. Its output is in html file and screenshot attached herewith.  The code is given below for your reference and review. I liked mplfinance because of its chart quality and clarity.  If the issue that I observe is fixed then it would be very nice.  Thanks a lot for sparing your time and looking into this issue.  It would be great if you can look into this issue to resolve it or advise someone in your team to look into it. 


In [12]: 
    ...: import plotly.graph_objects as go
    ...: from plotly.offline import plot
    ...: import pandas as pd
    ...: from datetime import datetime
    ...: import pyodbc
    ...: 
    ...: conn = pyodbc.connect('Driver={SQL Server};'
    ...:                       'Server=DESKTOP-G5HM9SK\SQLEXPRESS;'
    ...:                       'Database=NSESQL;'
    ...:                       'Trusted_Connection=yes;')
    ...: 
    ...: cursor = conn.cursor()
    ...: 
    ...: sql_query = '''SELECT TradeDate as Date,OpenPrice as [Open],HighPrice as High,LowPrice as Low,ClosePrice as [Close],TotalTradedQuantity as Volume 
    ...:              from dbo.SpotMarketData where tradedate>='01-Apr-2020' 
    ...:              and Symbol='BHEL' '''
    ...: 
    ...: df = pd.read_sql(sql_query, conn,parse_dates=True)
    ...: df.index.name = 'Date'
    ...: 
    ...: fig = go.Figure(data=[go.Candlestick(x=df['Date'],
    ...:                 open=df['Open'],
    ...:                 high=df['High'],
    ...:                 low=df['Low'],
    ...:                 close=df['Close'])])
    ...: 
    ...: plot(fig, filename='basic1.html')
Out[12]: 'basic1.html'

In [13]: 

![image](https://user-images.githubusercontent.com/71934449/94580081-1e80b200-0297-11eb-9fa1-6a3806aec228.png)

**Comment by sunilfussey** [comment]
> Sunil,
> 
> This is interesting. Previously you were getting
> 
> ```python
> <class 'pandas.core.indexes.range.RangeIndex'>
> <class 'int'>
> ```
> 
> Whereas now with `index_col='Date'` you are getting
> 
> ```python
> <class 'pandas.core.indexes.base.Index'>
> <class 'str'>
> ```
> 
> Furthermore, the `<class 'str'>` objects **do** look like dates, so it should be relatively easy to convert them to a pandas.DatetimeIndex.
> 
> **Please try the following and let me know if it works**:
> Add `Data.index = pd.DatetimeIndex(Data.index.values)` immediately after the `read_sql(index_col='Date')`, thus:
> 
> ```python
> Data = pd.read_sql(sql_query, conn,index_col='Date',parse_dates=True)
> Data.index = pd.DatetimeIndex(Data.index.values)
> Data.index.name = 'Date'  # This line possibly is not necessary, but keep it for now until get this working.
> mpf.plot(Data,type='candle')
> ```
> 
> Meanwhile, later today, I may have time to try to reproduce: I am curious to investigate why it appears that `pd.read_sql(sql_query, conn,index_col='Date',parse_dates=True)` is _**not**_ converting the dates to a pandas.DatetimeIndex, despite the fact that `parse_dates=True` is set.

Hi Daniel,

Thanks a lot for looking into the issue.  Now it has resolved as it produces the expected chart.  I had also commented "Data.index.name = 'Date' " which is not necessary and it works. Below are the final code and its output.  Once again many many thanks!


In [2]: 
   ...: import pandas as pd
   ...: import pyodbc 
   ...: import mplfinance as mpf
   ...: 
   ...: conn = pyodbc.connect('Driver={SQL Server};'
   ...:                       'Server=DESKTOP-G5HM9SK\SQLEXPRESS;'
   ...:                       'Database=NSESQL;'
   ...:                       'Trusted_Connection=yes;')
   ...: 
   ...: cursor = conn.cursor()
   ...: 
   ...: sql_query = '''SELECT TradeDate as Date,OpenPrice as [Open],HighPrice as High,LowPrice as Low,ClosePrice as [Close],TotalTradedQuantity as Volume 
   ...:              from dbo.SpotMarketData where tradedate>='01-Apr-2020' 
   ...:              and Symbol='BHEL' '''
   ...: 
   ...: 
   ...: Data = pd.read_sql(sql_query, conn,index_col='Date',parse_dates=True)
   ...: Data.index = pd.DatetimeIndex(Data.index.values)
   ...: #Data.index.name = 'Date'
   ...: mpf.plot(Data,type='candle')

In [3]: 

![image](https://user-images.githubusercontent.com/71934449/94594711-70313880-02a7-11eb-9971-cc96297d2048.png)

**Comment by DanielGoldfarb** [comment]
Sunil,
That's great!  I'm glad it is working for you.

If you don't mind, I would like to ask you to try one more thing, to see if it works also.
I would like to know if this works, and if you can test it for me _then it will save me having to install sql server and load the data_:

Instead of:
```python
Data = pd.read_sql(sql_query, conn,index_col='Date',parse_dates=True)
Data.index = pd.DatetimeIndex(Data.index.values)
mpf.plot(Data,type='candle')
```
Please try this, if you don't mind taking the time, and please let me know if this works also:
```python
Data = pd.read_sql(sql_query, conn,index_col='Date',parse_dates=['Date'])
mpf.plot(Data,type='candle')
```
(The difference is setting `parse_dates` to a len=1 list of column names).

Thank you.  All the best.  --Daniel

**Comment by sunilfussey** [comment]
> ```python
> ['Date']
> ```

Hi Daniel,

Yes, It works well. Thanks! Below is the code and screenshot of the chart.


In [1]: 
   ...: import pandas as pd
   ...: import pyodbc 
   ...: import mplfinance as mpf
   ...: 
   ...: conn = pyodbc.connect('Driver={SQL Server};'
   ...:                       'Server=DESKTOP-G5HM9SK\SQLEXPRESS;'
   ...:                       'Database=NSESQL;'
   ...:                       'Trusted_Connection=yes;')
   ...: 
   ...: cursor = conn.cursor()
   ...: 
   ...: sql_query = '''SELECT TradeDate as Date,OpenPrice as [Open],HighPrice as High,LowPrice as Low,ClosePrice as [Close],TotalTradedQuantity as Volume 
   ...:              from dbo.SpotMarketData where tradedate>='01-Apr-2020' 
   ...:              and Symbol='BHEL' '''
   ...: 
   ...: 
   ...: Data = pd.read_sql(sql_query, conn,index_col='Date',parse_dates=['Date'])
   ...: #Data.index = pd.DatetimeIndex(Data.index.values)
   ...: mpf.plot(Data,type='candle')

In [2]: 

![image](https://user-images.githubusercontent.com/71934449/94694024-07eb6100-0352-11eb-8643-66b6518e61a9.png)

**Comment by DanielGoldfarb** [comment]
Sunil,
Excellent!  Good to know.  Thank you.  --Daniel
