### ISSUE TITLE
How to set time to close plot window?

### ISSUE THREAD

**Issue by Full4me** [matplotlib/mplfinance#273]
How to set time to close automatically plot window??

Regards

**Comment by DanielGoldfarb** [comment]
I do not understand your question.  Please provide more detail.

**Comment by Full4me** [comment]
On matplotlib You can:
```
plt.show(block=False)
plt.pause(3)
plt.close()
```
and chart will be closed automatically after n seconds.

**Comment by DanielGoldfarb** [comment]
```python
fig, axlist = mpf.plot(data,block=False,returnfig=True)
plt.pause(interval)
plt.close(fig)
```

Thanks for the idea.  I think I will add a kwarg to pause and close.  In the meantime, the above example code should work.
