### ISSUE TITLE
Bug Report:

### ISSUE THREAD

**Issue by ckalbach** [matplotlib/mplfinance#279]
**Describe the bug**
When calling Subplots() method for Mpf_Figure() class, the for loop that sets the axes styles fails.

**To Reproduce**
```python
fig = mplfinance.figure()
fig.subplots(nrows=2,ncols=1)

Error:
~\site-packages\mplfinance\_mplwraps.py in subplots(self, *args, **kwargs)
    110         self.mpfstyle = style
--> 111         if ax in axlist:
    112             ax.mpfstyle = style
    113         return fig, axlist
NameError: name 'ax' is not defined
```

**Expected behavior**
Should return a list of axes with ax.mpfstyle = style attribute

**Correction**
Change line 111 in _mplwraps.py from
     **if** ax in axlist:
to:
    **for** ax in axlist:

**Comment by DanielGoldfarb** [comment]
Thanks.  Looks correct.   **Do you want to make the change and submit a PR ?**  

This is embarassing.  ***Clearly*** i never tested `Mpf_Figure.subplots()` even once.

**Comment by DanielGoldfarb** [comment]
Hmm.  I'm running some tests, and it appears the fix may not be as simple as
>Change line 111 in _mplwraps.py from
>`    if ax in axlist:`
>to:
>`    for ax in axlist:`

Definitely the `if` is wrong; but depending on the other arguments `for` may or may not fix the issue.  
And there appears to be some other issues possibly as well.  Will investigate further.   
Still the offer stands, if you are interested in fixing this bug and submitting a PR, it will be greatly appreciated.

**Comment by DanielGoldfarb** [comment]
The fix looks more like this:

```python
if isinstance(axlist,mpl_axes.Axes):
    axlist.mpfstyle = style
elif isinstance(axlist,np.ndarray):
    for ax in axlist.flatten():
        ax.mpfstyle = style
    else:
        raise TypeError('Unexpected type ('+str(type(axlist))+') '+
        'returned from "matplotlib.figure.Figure.subplots()"')
return axlist
```

**Comment by DanielGoldfarb** [comment]
https://github.com/matplotlib/mplfinance/pull/280
