### ISSUE TITLE
module 'mplfinance' has no attribute 'figure'

### ISSUE THREAD

**Issue by fremaxter** [matplotlib/mplfinance#283]
Im having problems running the mpf_animation_demo1.py, it shows this eror module 'mplfinance' has no attribute 'figure'.
Just using mpf.plot() is working fine.

EDIT:
oke, just had problems with pip.

FIXED:
If anyone is having the same problem, maybe you have to manualy specify the pip version. 

For example

pip3 install  mplfinance==v0.12.7a 

did fix it for me.

**Comment by DanielGoldfarb** [comment]
@fremaxter  - Thank you for posting your fix.
