### ISSUE TITLE
How to add a label to lines.

### ISSUE THREAD

**Issue by fadeawaylove** [matplotlib/mplfinance#285]
Ask anything you want about mplfinance usage, project philosophy and/or priorities, or anything else related to mplfinance.
just like this:

![image](https://user-images.githubusercontent.com/38212718/97544007-f6a27c80-1a03-11eb-8c84-e22bd13878c1.png)

**Comment by DanielGoldfarb** [comment]
Regarding legends, see [**here**](https://github.com/matplotlib/mplfinance/issues/181#issuecomment-646329911) and  [**here**](https://github.com/matplotlib/mplfinance/issues/181#issuecomment-667252575).

See also discussion under [**this issue**](https://github.com/matplotlib/mplfinance/issues/276).  Not sure what the status is there.  In theory it is close to being finished.

All the best.  --Daniel

**Comment by fadeawaylove** [comment]
ok, thank you very much.
