### ISSUE TITLE
Bug Report: Docs do not Build, Examples Moved

### ISSUE THREAD

**Issue by studentbrad** [matplotlib/mplfinance#298]
**Describe the bug**
The docs do not build any longer, the examples have been moved to `original_flavor`.

**To Reproduce**
1. Clone the repository
2. Change the directory to `doc`
3. Run `make html`

**Expected behavior**
I expected the docs to build.

**Additional context**
If you update the paths in `doc/source/example/examples.rst` the docs build.

**Comment by DanielGoldfarb** [comment]
Please see response here: https://github.com/matplotlib/mplfinance/issues/119#issuecomment-623435548

**Comment by DanielGoldfarb** [comment]
Duplicate of #119
