### ISSUE TITLE
Error Handling with plot and addplot=apd

### ISSUE THREAD

**Issue by manuelwithbmw** [matplotlib/mplfinance#300]
Hi @DanielGoldfarb 
I have some code where I plot a chart enhanced with a very customised **apd** in the mpf.plot call **addplot=apd** as below indicated. This **apd** is a collection of graphics triggered by analytic signals calculated elsewhere in the code. This all work fine 99% of the time. In some very occasional situations those signals cannot be computed at all with certain time series, which would be ok If I could just avoid plotting them. The problem is the call of addplot=apd makes the final code execution crash with the ERROR MESSAGE shown at the bottom because of those not existing signals (I guess). The crash prevents further piece of code from execution, that is why it becomes annoying.
Is there a way to catch this error occurrence in the code itself? If I simply delete the **addplot=apd** for that special cases, all works well for the rest of the charting but I would like this to be handled by the code itself so that it can keep running ahead of that part when these rare situations occur. Maybe if the signal does not exist, I could force the relative Series in the components of my **apd** to be all NaNs and let the **addplot=apd** plot nothing, empty scatter graphics on top of the candles?

_fig, axlist = mpf.plot(df, type='candle', ylabel='Price', ylabel_lower='Volume', 
         mav=(21, 50, 200), volume=True, figscale=0.8, figsize=(12.5,6.5), addplot=apd, 
         scale_width_adjustment=dict(candle=1.25), style=s,
         returnfig=True)
...
plt.show()_

**ERROR MESSAGE:**
.
.
  File "<__array_function__ internals>", line 5, in amax
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 2705, in amax
    return _wrapreduction(a, np.maximum, 'max', axis, None, out,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 87, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation maximum which has no identity

Is there a way to catch this error occurrence in the code, in order not to make it crash when I use addplot=apd?
Looking for suggestions....I hope I explained myself.

Many thanks and happy holiday time.
Merry Christmas to everyone

**Comment by DanielGoldfarb** [comment]
Hi Manuel,
I had hoped to get a back to you sooner.  I guess you decided you have a workaround.   I not 100% sure what the issue was for you, since I cannot see the entire walkback from the exception, but it sounds to me similar to **[the issue for which I responded here](https://github.com/matplotlib/mplfinance/issues/259#issuecomment-688429294)**.

Please let me know if that is the case.

Thanks.  Wishing you all the best.  --Daniel

**Comment by manuelwithbmw** [comment]
@DanielGoldfarb Dear Daniel, sorry -did not mean to rush you- I closed this as I am not experiencing it at the moment: I have several signals added in my **apd** and I think some of them are (very occasionally) all NaN and make the overall call to addplot=apd fail. I think your workaround to check that _not all([x == np.nan for x in values]) before calling mpf.make_addplot() and call it only if not all is True"_ is the right solution for the single signal, I need to add this on each of them.
Thanks for your time, ATB --Manuel
