### ISSUE TITLE
Feature Request: make_addplot allow scatter colour

### ISSUE THREAD

**Issue by riodda** [matplotlib/mplfinance#310]
**Describe the bug**
On very high resolution and picture size the graphics are not painted well and the picture size are ignored.

**To Reproduce**
Usa a style like: `   s = mpf.make_mpf_style(base_mpf_style='yahoo',rc={'figure.figsize':[1024,256],'figure.dpi':1200})`
With a dataset about 8000 points
Also the size of the picture should be 1024inch*1200dpi = 1228800 pixels x 256inch*1200dpi=3072000pixels but the figure in output as you can see form the attach is 8183X6936

**Expected behavior**
The graphic features should not appear overlayed

**Screenshots**

![Immagine](https://user-images.githubusercontent.com/13453063/103785160-2ccf2e80-503b-11eb-974a-446d976c2de9.png)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by DanielGoldfarb** [comment]
Dario,
The figure size is controlled by kwargs to `mpf.plot()` and it defaults to a value of 8" x 5.75" if unspecified.  This is documented between cells [4]: and [5]: in the [plot customizations tutorial](https://github.com/matplotlib/mplfinance/blob/master/examples/plot_customizations.ipynb).  Because of the existence of these kwargs, the rcparams will not affect the figure size.

Can I assume you are talking about saving the figure to an image file?   If so, you can also specify the dpi as part of the savefig kwarg dictionary.  See "[Saving your plot to a file](https://github.com/matplotlib/mplfinance/blob/master/examples/savefig.ipynb)."  That's not to say that your setting of the dpi in the style rcparams won't also work; I expect that it will.  But figsize in rcparams *is* ignored by design.

Let me know if that helps.  And please confirm whether you are talking about saving the Figure to an image file.

Thanks. --Daniel

**Comment by riodda** [comment]
> Dario,
> The figure size is controlled by kwargs to `mpf.plot()` and it defaults to a value of 8" x 5.75" if unspecified. This is documented between cells [4]: and [5]: in the [plot customizations tutorial](https://github.com/matplotlib/mplfinance/blob/master/examples/plot_customizations.ipynb). Because of the existence of these kwargs, the rcparams will not affect the figure size.
> 
> Can I assume you are talking about saving the figure to an image file? If so, you can also specify the dpi as part of the savefig kwarg dictionary. See "[Saving your plot to a file](https://github.com/matplotlib/mplfinance/blob/master/examples/savefig.ipynb)." That's not to say that your setting of the dpi in the style rcparams won't also work; I expect that it will. But figsize in rcparams _is_ ignored by design.
> 
> Let me know if that helps. And please confirm whether you are talking about saving the Figure to an image file.
> 
> Thanks. --Daniel

Thanks I did not got reading the docs that figscale was the right parameter, I confirm that the dpi parameters makes a difference in the picture output.
Using the scale output the render is looking ok no more overlay of figures.
Frankly it's strange to have to deal with a scale from a fixed size of 8" x 5.75" and then play with the dpi as well, i think that the matplotlib way it's giving more control you set the size and dpi and you have full control.
Was is also messing me up is that some part are set as size and are not scaled in proportion (for example the scatter marker size), not a drama but it's a bit confusing.
Thanks for your help and i might suggest that the default size and dpi should be put someware in the example.

**Comment by DanielGoldfarb** [comment]
>Using the scale output the render is looking ok no more overlay of figures.

Glad to hear it!

> Frankly it's strange to have to deal with a scale from a fixed size ...

Perhaps the documentation is not clear enough:  There are **three** kwargs to `mpf.plot()` that affect size: **`figscale`** and **`figratio`** can be used.  Or alternatively you can just specify using kwarg **`figsize`** just like with matplotlib.  The reason for figscale (as opposed to figsize) is that once you choose your figratio, you may want to view some figures larger and some smaller.  It's just a convenient way to avoid doing the math yourself, by just scaling the specified ratio up or down.

> Was is also messing me up is that some part are set as size and are not scaled in proportion (for example the scatter marker size),

This is not mplfinance, but appears to be **matplotlib** defined behavior: I ran a few tests (with just matplotlib) and, as far as I can tell, changing the size of the Figure does not change figure elements such as marker size, line width, label font sizes, etc.

>  i might suggest that the default size and dpi should be put someware in the example.

Good idea.  I will look into that.  

Dario, Thanks for your interest in mplfinance.  All the best.  --Daniel

P.S.  If you don't mind, could you post one of your plots here that worked OK?   I love to see what people are doing with mplfinance.  Thanks.

**Comment by riodda** [comment]
Here is one of the graph i'm working on, it's a random forest classification to idenfiy uptrend downtrend and lateral. In the graph you can see blue dots is were the random forest has identyfied the market as lateral, red for downtrend and green for uptrend.
I'm trying to improve the classification accuracy to more than 85% but it's not that easy, i'm also thinking to use a TA confirm signal as support to the random forest classifyer but backtesting all this stuff is becoming a very big task for my coding ability, i'm a mechanical engineer and i've started  study trading and study python in march.
 
![Immagine](https://user-images.githubusercontent.com/13453063/103866400-030f1980-50c6-11eb-85d0-7cc4cfca2f1f.png)
