### ISSUE TITLE
matplotlib and mplfinance

### ISSUE THREAD

**Issue by david03kimo** [matplotlib/mplfinance#312]
Hi,thanks for your great work.

I am newbie to matplotlib and mplfinance.
How can I replace the line-charts to candlesticks charts with the hlines and scatter?I tried and produced 2 figures.

I did a chart by matplotlib with line-chart and entry point and exit point and TP/SL lines just like below,
![image](https://user-images.githubusercontent.com/58899692/104109517-b025a400-5309-11eb-8122-30e50612705c.png)

the code:
```python
plt.figure(figsize = (25, 8))
def trade_plot(df, trade, exit_price, exit_date):
    # df1=df[['Open','High','Low','Close']]
    # mpf.plot(df1,type='candle',mav=(30,100),block = False,returnfig = True)
    plt.plot(df['Close'][(trade['date_of_trade'] - timedelta(days = 100)): (trade['date_of_trade'] + timedelta(days = 30))], color = 'blue')
    plt.hlines(trade['TP'], xmin=trade['date_of_trade']-timedelta(minutes = 9),xmax=exit_date+timedelta(minutes = 9),color = 'green')
    plt.hlines(trade['SL'], xmin=trade['date_of_trade']-timedelta(minutes = 9),xmax=exit_date+timedelta(minutes = 9),color = 'red')
    if trade['signal']=='Sell':
        in_color='red'
        exit_color='green'
    elif trade['signal']=='Buy':
        in_color='green'
        exit_color='red'
    plt.scatter(trade['date_of_trade'], trade['entry_price'], color = in_color, s = 100)
    plt.scatter(exit_date, exit_price, color = exit_color, s = 100)
    return

plt.show()
```

and by the way, how can I set background black or dark mode?

I am so appreciated what you did.

**Comment by DanielGoldfarb** [comment]
Hi David,

Thanks for your appreciation and interest in mplfinance.  There are a number of [**mplfinance tutorials here**](https://github.com/matplotlib/mplfinance/blob/master/README.md#contents-and-tutorials) that are each realtively short and should not take much of your time.

In particular I would sugest you focus on:
- **[Basic Usage](https://github.com/matplotlib/mplfinance#usage)**
- **[Customizing the Appearance of Plots](https://github.com/matplotlib/mplfinance/blob/master/markdown/customization_and_styles.md)**
- **[Adding Your Own Technical Studies to Plots](https://github.com/matplotlib/mplfinance/blob/master/examples/addplot.ipynb)**
- **[Trends, Support, Resistance, and Trading Lines](https://github.com/matplotlib/mplfinance/blob/master/examples/using_lines.ipynb)**

**Within [Customizing the Appearance of Plots](https://github.com/matplotlib/mplfinance/blob/master/markdown/customization_and_styles.md) you will probably be most interested in [**Mplfinance Styles**](https://github.com/matplotlib/mplfinance/blob/master/examples/styles.ipynb) regarding finding a style which has the dark background or dark mode that you want**.

After reading the above items, it will be easier for me to answer any specific questions that you may still have.
Let me know.  All the best.   --Daniel

---

[Click here to reference the mplfinance styles from which you can choose](https://github.com/matplotlib/mplfinance/wiki/Mplfinance-Style-Sheets-Reference).

**Comment by david03kimo** [comment]
> After reading the above items, it will be easier for me to answer any specific questions that you may still have.
> Let me know. All the best. --Daniel
> 

Hi,Daniel,

Thanks for your guiding.I have finished the graph mostly as below.
![image](https://user-images.githubusercontent.com/58899692/104167007-9a61cd00-5436-11eb-981c-1d947dcd6b8f.png)

and then has to add TP/SL lines just like last post graph.
It seems I have to use tlines to draw the TP/SL lines rather than hlines for start and end point needed.Is it correct?Or hlines can setup start and end point?

Thanks again for your help.
Cheers,

David

**Comment by DanielGoldfarb** [comment]
David,

That *is* a very nice looking plot.  Thanks for sharing.  I always enjoy seeing what people are doing with mplfinance.

Regarding `subplots_adjust()`, mplfinance does *not* have a specific adjust method or kwarg, however I think for your use-case you can use the `scale_padding` kwarg, which can take either a single value to adjust the padding all sides of the Figure, or can take a `dict` to adjust the padding individually on one or more of each of the four sides of the figure.  [**Click here for information about using the `scale_padding` kwarg**](https://github.com/matplotlib/mplfinance/issues/212#issuecomment-655603896).  

Please let me know if that works for you (or if you feel you need a better solution).

All the best.  --Daniel
