### ISSUE TITLE
There is a problem in using ax.plot mpf.plot together

### ISSUE THREAD

**Issue by alphsky** [matplotlib/mplfinance#319]
```
df = pd.read_csv('kdata')
df = df.set_index('date',drop=False)
df = index2datetime(df.iloc[0:5,:])
fig = mpf.figure()
ax = fig.add_subplot(111)
s = pd.Series([2,5,8,3,9])
s.index = df.index[0:5]
mpf.plot(df,ax=ax,type='candle')
ax.plot(s)
plt.show()
```
Initially I wish to print lines on k data graph, but with smaller size. The function addplot is not available.Therefore, I use ax.plot instead.<br>
But there is a problem. In the code above, s and df have same index, but the graph shows different x-axis. k candle is on the upleft as well as line on the downright. Move mouse to the line, it shows 'x=y=...'.<br>
Is there anything wrong with the code?
![图片](https://user-images.githubusercontent.com/76871610/105577628-ca558c80-5db5-11eb-912c-6bb363ea6710.png)

**Comment by DanielGoldfarb** [comment]
Hi.  

1. The function `make_addplot()` ***is*** available, but *if you pass* `ax=<some_axes>` *into* `mpf.plot()` *then you* ***must also pass*** `ax=<some_axes>` ***into*** `mpf.make_addplot()`.

2. This line of code: `df = index2datetime(df.iloc[0:5,:])` doesn't seem right to me.  <br>Where is the code for `index2datetime()`?

3. If you would like me to try to reproduce the problem and determine what is happening, please provide the csv file `'kdata'`.

Finally, and this is most important:  Please describe exactly what you are trying to accomplish.  

It appears to me (from the small amount of information you have provided) that what you are trying to do can be done ***without*** resorting to *external axes mode*.  As a general rule, external axes mode *should be avoided whenever possible*.  It will complicate your code which can lead to making mistakes.
