### ISSUE TITLE
Can we customize `alines` (Arbitrary Lines)?

### ISSUE THREAD

**Issue by YashitM** [matplotlib/mplfinance#324]
I'm looking to customize `alines` to have a dotted structure, and preferably have different colors for each `aline`.

**Comment by DanielGoldfarb** [comment]
Yashit,
Thanks for your interest in mplfinance.  Please read through [**the tutorial**](https://github.com/matplotlib/mplfinance/blob/master/examples/using_lines.ipynb).  It's all there.  Should take only about 10 or 15 minutes of your time.  Let me know if you have any questions after that.
All the best.  --Daniel
