### ISSUE TITLE
add multiple figure

### ISSUE THREAD

**Issue by shamedsj** [matplotlib/mplfinance#325]
Daniel, you did awesome this is amazing and I appreciate.
I have 2 questions:
1- how can I add multiple plot in one frame with different size. to be clear, I want to see some candles in different time frames in one plot beside each other with their own indicators. for example one chart in daily and other in 4h and the other in 1h beside each other and below them their own indicators
2- how can I add label for each indicator.

sorry maybe you answer them before but i do really couldn't find them.

**Comment by DanielGoldfarb** [comment]
Sayed,

Thanks for your appreciation and interest in mplfinance.

---

> 1- how can I add multiple plot in one frame with different size. 

This can only be done with "[**external axes mode**](https://github.com/matplotlib/mplfinance/blob/master/markdown/subplots.md#external-axes-method)."  <-- Click here to read the documentation. 

---

> 2- how can I add label for each indicator.

**Legends**, **Text Annotations**, and **Labels** (other than axis labels, and plot title), are not yet directly supported in mplfinance.  

You can implement them by first gaining access to the Axes objects, and the using the various matplotlib methods that exist for doing these things.  (For example, [`Axes.text()`](https://matplotlib.org/3.3.3/api/_as_gen/matplotlib.axes.Axes.text.html), [`Axes.annotate()`](https://matplotlib.org/3.3.3/api/_as_gen/matplotlib.axes.Axes.annotate.html), [`Axes.legend()`](https://matplotlib.org/api/_as_gen/matplotlib.axes.Axes.legend.html)).

[**There are two ways to gain access to the Axes objects**](https://github.com/matplotlib/mplfinance/issues/219#issuecomment-671292326):
1. [**`returnfig=True`**](https://github.com/matplotlib/mplfinance/issues/219#issuecomment-671292326)
2. [**external axes mode**](https://github.com/matplotlib/mplfinance/blob/master/examples/external_axes.ipynb)

Click the above links for detail on these two ways:  
***Note, you must use one or the other***: `returnfig=True` and external axes mode ***cannot be used together***.


HTH.  All the best.  --Daniel
