### ISSUE TITLE
y axis to the 4th decimal place

### ISSUE THREAD

**Issue by david03kimo** [matplotlib/mplfinance#328]
Hi,Daniel,

How to adjust the y axis to the 4th decimal place?Forex use 0.0001 as a pips.Thank you.

![image](https://user-images.githubusercontent.com/58899692/106512711-ee7b4100-650c-11eb-9468-51cc401bca2f.png)

**Comment by DanielGoldfarb** [comment]
David,

Presently there is not a direct way to do this.  (If you would like to implement and contribute a `yformat` kwarg that would be greatly appreciated.)  In the meantime, you can *try* the following:

```python
from matplotlib.ticker import FormatStrFormatter

...

fig, axlist = mpf.plot(df,...,returnfig=True)
axlist[0].yaxis.set_major_formatter(FormatStrFormatter('%.4f'))
mpf.show()
```

Please let me know if this idea works.  (I didn't have time to test it out myself).
Thanks.  All the best.  --Daniel

**Comment by DanielGoldfarb** [comment]
i tested [this](https://github.com/matplotlib/mplfinance/issues/328#issuecomment-771139560) and it works
