### ISSUE TITLE
Scatter up shift 2 pips

### ISSUE THREAD

**Issue by david03kimo** [matplotlib/mplfinance#330]
Hi,Daniel,

How can I plot scatter and move up 2 pips more?
I use this but it didn't work:
`                        mpf.make_addplot(df[pair][strategy][risk][timeframe]['PivotHigh'],type='scatter',color='r',markersize=20),
`
Thank you.

**Comment by DanielGoldfarb** [comment]
Hi David,

Not sure I understand what you are getting at, but I'll take a guess that you want to put some scatter some signals either slightly above or slightly below the ohlc candles or bars, or something similar.

If my guess is correct, here's what I usually do:  I calculately the range of my data set, and then shift the signals, up or down, by add or subtracting approximately 2% of the data range.

[**You can see some example code by clicking here**](https://github.com/matplotlib/mplfinance/issues/306#issuecomment-752544405).

HTH.   --Daniel
