### ISSUE TITLE
Bug Report: mplfinance at raspberry pi - Gdk-CRITICAL

### ISSUE THREAD

**Issue by balku** [matplotlib/mplfinance#331]
Hi,
at running mplfinance on a headless Raspberry Pi 4 (Buster), I get the error message:

Unable to init server: Could not connect: Connection refused
Unable to init server: Verbindung ist gescheitert: Connection refused
```
(xxx.py:22348): Gdk-CRITICAL **: 14:17:13.940: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(xxx.py:22348): Gdk-CRITICAL **: 14:17:13.945: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
```
calling mplfinance:
```python
import mplfinance as mpf
def chart(data, title):
    mpf.plot(data, type='candle', style='yahoo', mav=(50,100,200),  \
             figsize=(16,8), panel_ratios=(10,6,2), \
             savefig='bilder/'+title+'.png',
             title=title, volume=True, volume_panel=1, ylabel='', ylabel_lower='')
```
```
OS-Version
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
```

pip show mplfinance (git cloned at 2021-02-09):

Name: mplfinance
Version: 0.12.7a5
Summary: Utilities for the visualization, and visual analysis, of financial data
Home-page: http://github.com/matplotlib/mplfinance
Author: MPL Developers
Author-email: matplotlib-users@python.org
License: BSD-style
Location: /home/pi/.local/lib/python3.7/site-packages
Requires: pandas, matplotlib
Required-by:

The problem exists with 0.11, also.

Many thanks for help

**Comment by DanielGoldfarb** [comment]
It seems to me possibly there is an issue with a **service needed to display graphics**, or with the matplotlib backend installation.

- Please try the following, in a separate file:
```python
import matplotlib.pyplot as plt
import random
print('matplotlib backend:',plt.get_backend())
x = [x for x in range(10)]
y = random.sample(range(10),10)
plt.plot(x,y)
plt.show()
```

The above is one of the simplest matplotlib plots you can make.  If that doesn't work then there is definitely something more low-level going on here.  Please let me know the results.   Thanks. --Daniel



- Do you have another system on which you can try to run this?

**Comment by DanielGoldfarb** [comment]
Please also indicate the result of:

```echo $DISPLAY```

at your linux prompt.

**Comment by DanielGoldfarb** [comment]
I've done some poking around online for your error message.  This definitely seems to be a general gui issue with your environment;  apparently you need to set up some kind of x11 forwarding or service.  

I'm not sure how to do that for your environment.   "Headless" by definition means there is no graphical user interface.  Not sure if there is any way to support headless and graphics at the same time.

One thing you can try, if you want to remain headless, is to set the matplotlib backend to "Agg" which is a non-gui based matplotlib backend, and then save your plot to a file, for example:  Actually, I just looked more closely at your code, and you are indeed saving to a file so ***this should work***:

- Run the following code ***before*** runing your `mplfinance` code:
```python
import matplotlib 
matplotlib.use('Agg')
```

**Comment by balku** [comment]
Hi Daniel,
many thanks for your very fast response.
Here the requested information:

Python 3.7.3 (default, Jul 25 2020, 13:03:44)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import matplotlib.pyplot as plt
Unable to init server: Could not connect: Connection refused
Unable to init server: Verbindung ist gescheitert: Connection refused

(.:23305): Gdk-CRITICAL **: 15:38:01.937: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(.:23305): Gdk-CRITICAL **: 15:38:01.940: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
>>> import random
>>> print('matplotlib backend:',plt.get_backend())
matplotlib backend: agg
>>> x = [x for x in range(10)]
>>> y = random.sample(range(10),10)
>>> plt.plot(x,y)
[<matplotlib.lines.Line2D object at 0xb1dbec90>]
>>> plt.show()
>>>


echo $DISPLAY

No output - only empty line.

------

After inserting matplotlib.use('Agg'), same result:

import mplfinance as mpf
import matplotlib
matplotlib.use('Agg')
def chart(data, title):
    mpf.plot(data, type='candle', style='yahoo', mav=(50,100,200),  \
             figsize=(16,8), panel_ratios=(10,6,2), \
             savefig='bilder/'+title+'.png',
             title=title, volume=True, volume_panel=1, ylabel='', ylabel_lower='')


result:
Unable to init server: Could not connect: Connection refused
Unable to init server: Verbindung ist gescheitert: Connection refused

(xxx.py:23378): Gdk-CRITICAL **: 15:41:08.400: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(xxx.py:23378): Gdk-CRITICAL **: 15:41:08.403: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

Could the reason be, running headless?
I use my Raspberry as a server, only.

Thanks 
Kurt

**Comment by DanielGoldfarb** [comment]
Kurt,
Yes, the issue is because you are running headless.  But according to everything I have seen, ***using backend 'Agg' and saving the plot to a file is supposed to be a workaround for headless***.

Try placing
```
import matplotlib
matplotlib.use('Agg')
```

At the very top of your script, before anything else.

**Comment by balku** [comment]
Hi Daniel,
export MPLBACKEND=Agg
solved the problem.
Many thanks
Kurt

PS: 
import matplotlib
matplotlib.use('Agg')
did not solve it.
Don't know why.

**Comment by balku** [comment]
Problem solved with:
export MPLBACKEND=Agg

**Comment by DanielGoldfarb** [comment]
Awesome.  Glad to hear it worked.  Thanks.
