### ISSUE TITLE
Is there anyway to set a manual specific price value for scaling?

### ISSUE THREAD

**Issue by danaman123** [matplotlib/mplfinance#332]
Ask anything you want about mplfinance usage, project philosophy and/or priorities, or anything else related to mplfinance.

**Comment by DanielGoldfarb** [comment]
Can you give a concrete example?  Ideally what do you want to set (maybe a kwarg called `price_scale`) to what value you would set it,  and ***exactly what you would like to see as a result of that setting***?

**Comment by DanielGoldfarb** [comment]
no response
