### ISSUE TITLE
Bug Report: Point-and-Figure Plotting Error

### ISSUE THREAD

**Issue by GenusGeoff** [matplotlib/mplfinance#335]
**Describe the bug**
The Point and Figure definition doesn't plot quite correctly. The only reason why a new column is created in a Point and Figure Chart is to avoid overwriting an existing box. So, a change in direction (X to O or vice-versa) doesn't result in a new column unless it would result in an overwriting of an existing data point. This helps to better show the trend and makes the chart more compact and readable.

**To Reproduce**
N/A

**Expected behavior**
The O or X, insofar as they're not overwriting an existing plot point should be in a single column.

**Screenshots**
Please see the screenshots from the documentation provided.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 

**Additional context**

**Comment by DanielGoldfarb** [comment]
@GenusGeoff 
Thank you for reporting this issue. 
I'm not sure if you forgot to complete your reproducibility instructions, or perhaps the tool you used then stripped out some information.   Please use a non-smartphone, standard web browser (chrome, firefox, edge, etc) and navigate to [**this page**](https://github.com/matplotlib/mplfinance/issues/335) and **edit [this comment](https://github.com/matplotlib/mplfinance/issues/335#issue-812493813)** to include all information needed for someone to reproduce the error in their own environment.  Thank you.

**Comment by DanielGoldfarb** [comment]
no response
