### ISSUE TITLE
Is it possible to apply mpf styles to other matplotlib plots?

### ISSUE THREAD

**Issue by BlackArbsCEO** [matplotlib/mplfinance#337]
I would like to use the themes for other matplotlib plots.

**Comment by DanielGoldfarb** [comment]
Yes, you can do this if you create the Figure with `mpf.figure(style=...)`
Keep in mind however, that a large part of mpf styles is how they color candlsticks and/or ohlc bars, therefore some of the styles may look very different when plotting candles, but very similar when plotting simple, non-financial data.  

For example, try the following code:
```python
import mplfinance as mpf
import math

y = [math.sin(x) for x in range(10)]
x = [x for x in range(10)]

fig = mpf.figure(style='mike')
ax = fig.add_subplot()
ax.bar(x,y)
mpf.show()
del fig

fig = mpf.figure(style='blueskies')
ax = fig.add_subplot()
ax.bar(x,y)
mpf.show()
del fig

fig = mpf.figure(style='brasil')
ax = fig.add_subplot()
ax.bar(x,y)
mpf.show()
del fig

fig = mpf.figure(style='yahoo')
ax = fig.add_subplot()
ax.bar(x,y)
mpf.show()
del fig

fig = mpf.figure(style='checkers')
ax = fig.add_subplot()
ax.bar(x,y)
mpf.show()
del fig
```

**Comment by DanielGoldfarb** [comment]
By the way, if you perhaps want to plot soem arbitrary time-series (_other than_ prices) this is an enhancement that is coming relatively soon.  In the meantime there is a work-around posted here: https://github.com/matplotlib/mplfinance/issues/333#issuecomment-778704516
