### ISSUE TITLE
Change plot color

### ISSUE THREAD

**Issue by geirak** [matplotlib/mplfinance#340]
Hi
I have an indicator where I would like to change plot color based on certain criteria indicating a bullish or bearish scenario. Is it possible to specify colors per bar with the mpf.make_addplot color parameter, or can only one color be passed in?
Regards
Geir

**Comment by DanielGoldfarb** [comment]
The `color` kwarg in `mpf.make_addplot()` is only for plot types `line`, `scatter` and `bar`.  Ohlc bars and candles are colored by "marketcolors", which are part of the mpf "style" that you pass in.

That said, I belive what you are looking for will be handled by the following enhancement: **https://github.com/matplotlib/mplfinance/issues/205#issuecomment-784656755**

Let me know if [that](https://github.com/matplotlib/mplfinance/issues/205) is what you are looking for.

**Comment by DanielGoldfarb** [comment]
@geirak  ... I just realized that you already commented on the above mentioned [enhancement](https://github.com/matplotlib/mplfinance/issues/205).  However you bring up an interesting point.  Until that enhancement is implemented, it may be possible to use `mpf.make_addplot()` as a work-around.  It's a little bit klunky but it may work:  Use `mpf.make_addplot(type='scatter',color=?)` with sparse data (set all data to `nan` except for where you want the scatter mark to appear) and choose a rectangle or square as a scatter mark and place it right on top of the candle.

**Comment by geirak** [comment]
@DanielGoldfarb 
Right :-)

Here is an example of what I am looking for:

Is if it is possible to control the color of a line plot on a bar by bar basis. See attached screen shot (Ninja Trader), where you can see that the slow line changes color when the fast yellow line crosses the slow line.

![Changing oscillator colors](https://user-images.githubusercontent.com/79531167/109181982-d05fd400-778c-11eb-8cf3-33a9a77a11aa.png)

**Comment by DanielGoldfarb** [comment]
@geirak 
Interesting.  You *may* be able to do that with **two** `mpf.make_addplot()` **`type=line`** plots, using two different colors, and where you place `nan` values in each line where you want to see the *other* line's color.

**Comment by geirak** [comment]
right - that would work for me. I'll give it a shot.

Thank you Daniel for your excellent help!!!

**Comment by geirak** [comment]
Daniel - I just wanted to give feedback to show that your proposal works.

Assuming that there are already columns for the plot value ("D") and a column for the plot color ("dcolor") I created two new columns "dbull" and "dbear", which were filled with values only for the corresponding color.

I noticed that there would always be a gap in the plot when the color changed, so I had to ensure that there was an overlap at the color change.

Below a couple of excerpts from how I solved it. I am very new to Python and pandas, so I am sure there are better ways to accomplish this
![2021-02-26_14-27-39](https://user-images.githubusercontent.com/79531167/109305982-d1513e00-783e-11eb-8132-f4973881c9d0.png)

Here is how I am plotting:
![2021-02-26_14-19-32](https://user-images.githubusercontent.com/79531167/109306126-0198dc80-783f-11eb-85ad-6dc01186fb80.png)

And here is the first plot
![2021-02-26_14-19-56](https://user-images.githubusercontent.com/79531167/109305236-baf6b280-783d-11eb-9719-8009b6bec39f.png)

Axis etc. still need some more work...

**Comment by DanielGoldfarb** [comment]
@geirak 
Awesome!   Thank you so much for sharing.  I love to see the creative things people are doing with mplfinance (both the code and the output).  I had done a little playing around and also came to the conclusion that a small overlap is needed to avoid a gap at the point of color change.  Looks great!  
Thanks again.  All the best.  --Daniel

**Comment by msperansky** [comment]
Hello,

I have also been trying to make the line color conditional and approached it in a different way without success but perhaps there is a solution:
![1](https://user-images.githubusercontent.com/77117916/110991398-a231e500-8385-11eb-941a-bcdf12b9eb14.jpg)



But I get the error that it is wrong type for data in make_addplot

Matt
