### ISSUE TITLE
Hope to provide complete user information

### ISSUE THREAD

**Issue by lyl1836** [matplotlib/mplfinance#349]
Mplfinance is very convenient! But can't find a valid user manual!

The CSV file provided on GitHub can't be downloaded, error opening ipynb file!

Can you provide a complete user manual in PDF or HTML?

**Comment by DanielGoldfarb** [comment]
[**Click here for the documentation**](https://github.com/matplotlib/mplfinance#contents-and-tutorials) and click the links there for more documentation.  

Most of the documentation is in the form of jupyter notebooks (some as markdown and wiki pages) **which you can view directly on github**, or, if you clone the package and install jupyter, you can open the .ipynb files with `jupyter notebook`.
