### ISSUE TITLE
hi , i meet a question,i use mpf.plot,but i want to see a more detail, can time axis strech,how can set it?

### ISSUE THREAD

**Issue by mathpopo** [matplotlib/mplfinance#350]
Ask anything you want about mplfinance usage, project philosophy and/or priorities, or anything else related to mplfinance.
hi , i meet a question,i use mpf.plot,but i want to see a more detail, can time axis strech,how can set it?

**Comment by DanielGoldfarb** [comment]
### If you call `mpf.plot()` **outside** of a notebook, depending on what you backend is set to, you will usually get something like this:

![image](https://user-images.githubusercontent.com/11164790/110799751-7c9fc100-8249-11eb-893b-43b79c78cecc.png)

---

### Notice that there are tools in the upper left corner.  

### If you click on the **magnifying glass** you can then use your mouse to draw a rectangle around the data for which you want to see more detail.  That will give you something that looks like this:

---

![image](https://user-images.githubusercontent.com/11164790/110799910-a953d880-8249-11eb-8697-7f578a01e636.png)

---

-  To go back to the original image, click the Home button, or Back button in the upper left corner. 
- Notice also that the upper right corner says "zoom rect" to tell you that you are in zoom/detail mode.

---

## Another possibility is to resample your data:  [For an example of resampling, click here](https://github.com/matplotlib/mplfinance/issues/307#issuecomment-752702973).

**Comment by mathpopo** [comment]
@DanielGoldfarb first thank you for your help, i just want to enlarge the red axis, hope to see more smaller time,
i just click the purperbox, no effect
![image](https://user-images.githubusercontent.com/21274466/110887298-04a6c900-8325-11eb-8d16-1c9d2dda0ac2.png)

**Comment by mathpopo** [comment]
@DanielGoldfarb  i can enlarge it ,select (click till draw a box) a part picture, show the small part,but if i want to enlarge from start time,i cannot know what i can set?

**Comment by DanielGoldfarb** [comment]
> but if i want to enlarge from start time,i cannot know what i can set?

@mathpopo 

- I do not understand.  Can you click and draw the box so that the left side of the box is at the start time??

- Another thing you can try is to just plot less data by slicing your data frame.  For example:
    ```python
    mpf.plot(df.loc['2008-05-16':'2010-01-01',:],volume=True)
    ```

Please let me know if either of the above helps, or if you have more questions.
