### ISSUE TITLE
Usage Question

### ISSUE THREAD

**Issue by RT-Tap** [matplotlib/mplfinance#352]
Hi, I'm trying to use your library but having a bit of difficulty.
So I am getting minute candles through a REST API and then placing them into a pandas datagram, parsing the date/time into a datetime object and then using set_index to my datetime column but I'm getting stuck getting the plot to show up.

The error is: 
    raise TypeError('Expect data.index as DatetimeIndex')
TypeError: Expect data.index as DatetimeIndex

I can provide more data if needed, any help is appreciated and I also want to mention I appreciate your work as well so I want to thank you in advance.

**Comment by RT-Tap** [comment]
Nevermind I have figure it out, good job on the project, works well.  
I didn't see anything as of yet but are there any technical analysis tools other than the moving average?  I just figured I'd ask while i'm here.  Either way thank you for your time.

**Comment by DanielGoldfarb** [comment]
@RT-Tap  Glad you figured out your issue.

There are no TA tools built into mplfinance.  There are many python TA packages out there.  

The idea is to try to make it easy for you to pass the TA results into mplfinance easily.   Some good starting places:
- **[Adding Your Own Technical Studies to Plots](https://github.com/matplotlib/mplfinance/blob/master/examples/addplot.ipynb)**
-  **[mplfinance documentation contents](https://github.com/matplotlib/mplfinance/blob/master/README.md#contents-and-tutorials)**
- [pandas-ta](https://github.com/twopirllc/pandas-ta)
