### ISSUE TITLE
Question: axhspan support within mplfinance

### ISSUE THREAD

**Issue by daveydaid** [matplotlib/mplfinance#356]
Hi Daniel,

Firstly, a massive thank you for putting this library out there! It has helped me a lot with an on-going project. 

I was wondering if there is any way to have axhspan() functionality from matplotlib? Preferably without using external axis mode.

i.e. 
![image](https://user-images.githubusercontent.com/78655767/111639667-5ce13d80-87f3-11eb-99e3-613557ca1117.png)

**Comment by DanielGoldfarb** [comment]
@daveydaid 
Thanks for expressing your appreciation and for your interest in mplfinance.

There are two things that I would suggest, in order of preference:
1. Use `hlines` kwarg: see the [using lines tutorial](https://github.com/matplotlib/mplfinance/blob/master/examples/using_lines.ipynb), particularly cell number **`In [8]`** where something similar is done with `vlines`; just do the analogous thing with `hlines`.

2. Without external axes mode, you can still gain access to the axes using `returnfig=True`.  (See item number **1** on [**this page**](https://github.com/matplotlib/mplfinance/wiki/Acessing-mplfinance-Figure-and-Axes-objects)).  The code might look something like this:
    ```python
    fig,axlist = mpf.plot(data,...,returnfig=True)
    axlist[0].axhspan(...)
    mpf.show()
    ```

HTH.  All the best.   --Daniel
