### ISSUE TITLE
How can I specify the color I need?

### ISSUE THREAD

**Issue by jaried** [matplotlib/mplfinance#362]
When I draw lines with different versions of mplfinance, the colors displayed are different. The previous version is 0.12.4a0, and the later version is 0.12.7a10.
How can I specify the color I need in version 0.12.7a10?
The relevant code for version 0.12.4a0 is as follows:
`      mpl.rcParams['axes.prop_cycle'] = cycler(
        color=['white', 'yellow',
               '#ff00ff', '#00ff00', '#c0c0c0', 'darkorange',
               'indigo'])`

**Comment by DanielGoldfarb** [comment]
I don't know which color you are talking about.   Candles?  Moving average lines?  Something else?

Can you show an image of a plot from 0.12.4a0 and and image from 0.12.7a10 and point out on the image where the colors are different and which colors you prefer?

Thank you.

**Comment by jaried** [comment]
The first image is ploted from 0.12.7a10, the second image is ploted 0.12.4a0 ,and my code is the same .
`mpl.rcParams['axes.prop_cycle'] = cycler( color=['white', 'yellow', '#ff00ff', '#00ff00', '#c0c0c0', 'darkorange', 'indigo'])`
I need the lines to be displayed as white, yellow, and purple .
Thank you.

![001_IC2106_daily_candle_line](https://user-images.githubusercontent.com/26672425/111890521-09563600-8a25-11eb-9c96-215d83abf27b.jpg)
![001_IC2106_daily_candle_line](https://user-images.githubusercontent.com/26672425/111890615-f4c66d80-8a25-11eb-94b8-032260f7b313.jpg)

**Comment by DanielGoldfarb** [comment]
OK.  I think I know what is going on here.

Mplfinance controls colors through [**mplfinance styles**](https://github.com/matplotlib/mplfinance/blob/master/examples/styles.ipynb).   

Prior to version 0.12.4a1 however it was possible that the exact same style might give a different appearance for different users.  This contradicts the entire idea of a style.  We eventually tracked the issue down to the fact the different users might have rcParams, resulting in the same mplfinance style looking different for two different users.

The solution is that, as of version 0.12.4a1, when mplfinance applies the user's selected mplfinance style, the first thing it does is set rcParams to the matplotlib default value, and then layer the mplfinance style on top of that.  This provides a consisten mplfinance style for all users.

Given the above, the correct way to apply your own rcParams values is to include them in your own custom mplfinance style (which you appear to be using anyway).  You do this with the **`rc=<dict>`** kwarg of **`mpf.make_mpf_style()`**.  For example:
```python
myrcparams = {'axes.prop_cycle' : cycler( color=['white', 'yellow', '#ff00ff','#00ff00',
                                                 '#c0c0c0', 'darkorange', 'indigo']) }

s = mpf.make_mpf_style(...,rc=myrcparams)

mpf.plot(data,style=s)
```

Try the above and let me know if it fixes your problem.
Thanks.  --Daniel

**Comment by DanielGoldfarb** [comment]
By the way, you may also notice, comparing your two plots above, that there is a change to some of the line widths.  

Begining with version 0.12.5, the widths of various lines, volume bars, and candles now behave differently.  

[**There is a tutorial here**](https://github.com/matplotlib/mplfinance/blob/master/examples/widths.ipynb) that explains: 
1. The changes that were made to the algorithm that calculates the widths of various elements on the plot,
2. How you can revert to the old algorithm, ***or***
3. How you can customize the widths of various elements on the plot if you are not satisfied with the behaviour of the new algorithm.

**Comment by jaried** [comment]
Thank you, I have successfully adjusted it.
