### ISSUE TITLE
Point and figure [pnf] - Reversal param

### ISSUE THREAD

**Issue by HeyTechVideos** [matplotlib/mplfinance#368]
Hello,

Is it possible to change the PNF param "reversal" the same way as i can do with "box_size"? Is it even possible?

`mpf.plot(df, type='pnf', pnf_params=dict(box_size=7))`

**Comment by DanielGoldfarb** [comment]
Presently the reversal amount is assumed to be 1 box, and not configurable.   Do you have any interest in making this enhancement to mplfinance?

**Comment by HeyTechVideos** [comment]
I am a TradingView user (where I can configure box size and reversal size separately) and am now trying to implement some strategy in Python but I couldn't find that. Thanks for the answer then.

**Comment by coffincw** [comment]
Hello @HeyTechVideos,

I'll look into implementing the reversal size override this weekend.

**Comment by HeyTechVideos** [comment]
Thanks alot @coffincw!

If you need to, I found a working but outdated (just replace the deprecated .ix() with pandas) PnF chart with a reversal parameter. `https://github.com/ChillarAnand/stocktrends/blob/master/stocktrends/indicators.py`

Greetings
