### ISSUE TITLE
How to number the candles?

### ISSUE THREAD

**Issue by ismailbayram** [matplotlib/mplfinance#372]
I would like to number the candles according to some indicators, but I do not know how to?

For example (TD Sequantial Indicator):
<img width="442" alt="Screen Shot 2021-04-05 at 13 44 46" src="https://user-images.githubusercontent.com/8135027/113571778-a61cf400-961f-11eb-95b5-fb848e26dca2.png">

**Comment by DanielGoldfarb** [comment]
@ismailbayram 
Ismail,

There are a couple of different ways to do this.  First make sure you are familiar with [mplfinance additional plot functionality](https://github.com/matplotlib/mplfinance/blob/master/examples/addplot.ipynb).

- The simplest method is to use `mpf.make_addplot(data,type=scatter)` to make a scatter plot where the scatter markers are the numbers that you want.  You can see [**examples of how to do this by clicking here**](https://github.com/matplotlib/mplfinance/blob/master/examples/scratch_pad/scatter_multiple_markers.ipynb).  <br><br>(Also, you can find several links for more information [about custom scatter markers in this comment to issue 97](https://github.com/matplotlib/mplfinance/issues/97#issuecomment-615124744)).

- Alternatively you can use `Axes.text()`.  This requires first that you [**gain access to mplfinance's Axes objects**](https://github.com/matplotlib/mplfinance/wiki/Acessing-mplfinance-Figure-and-Axes-objects).  After that, you can find an example in the following two comments: 
  - [example plot](https://github.com/matplotlib/mplfinance/issues/97#issuecomment-633266909) and
  - [code to generate example plot](https://github.com/matplotlib/mplfinance/issues/97#issuecomment-633205567) 

I hope that helps.   All the best.  
--Daniel

**Comment by ismailbayram** [comment]
Thank you very much. This reply is very helpful.

**Comment by fxhuhn** [comment]
@DanielGoldfarb the addplot / scatterplot is super easy to use, but unfortunately only for numbers under 10. 
So, @ismailbayram in case you need a decimal point or 2 digits, you have to use the test() method.

**Comment by DanielGoldfarb** [comment]
@fxhuhn , Yes it gets trickier with 2 or more digit numbers, or with decimal.  You can do it, for example setting scatter marker to **`$12$`** or to **`$123$`**, however then the scatter marker may get smaller and you have to increase its size to make it more visible.  At that point it may be just as easy to use `text()` which ultimately prints numbers more clearly anyway.
