### ISSUE TITLE
Fill Between for addplots

### ISSUE THREAD

**Issue by ismailbayram** [matplotlib/mplfinance#374]
Hi there,
Thank you for this great library. I have question. I would like to add `fill_between` param to add_plot, but there is no parameter for this. So I've tried like this, and it worked: 
```
add_plots = []
add_plots.append(mpf.make_addplot(rsi,
                                  title=f"RSI({rsi_length})",
                                  width=1, ylim=[0, 100],
                                  color="#000000", panel=2, ylabel=f"RSI({rsi_length})"))
plt, axes = mpf.plot(ticker.df.tail(LENGTH), type='candle', volume=True, title=f'{SYMBOL}({interval.value})',
               returnfig=True, style='charles', addplot=add_plots, figscale=2,
               main_panel=0, volume_panel=1, panel_ratios=(3,1.2))


rsi_ax = list(filter(lambda ax: ax.title._text == f"RSI({rsi_length})", axes))[0]
rsi_ax.fill_between([i for i in range(0, LENGTH)], y1=30, y2=70, alpha=0.5)
plt.savefig("chart.png", dpi=100, format='png')
```

But it would be great if I could do like this:
`mpf.make_addplot(..., fill_between=dict(y1=30, y2=70))`

**Comment by DanielGoldfarb** [comment]
@ismailbayram 
Yes, that's the correct workaround for now.   The current `fill_between` implementation is something that I just hastily threw together, but it is inadequate in that it only allows a single fill_between.  The plan is to allow multiple fill betweens (a list of fill between specifications) in both `mpf.plot()` and `mpf.make_addplot()`, [**as was discussed here**](https://github.com/matplotlib/mplfinance/issues/218#issuecomment-660073929).  Currently in the midst of a different major enhancement and hoping to get to this in a couple months (unless, of couse, you would like to code it; I can provide guidance).

**Comment by ismailbayram** [comment]
Ok, I see. Thanks a lot :)
