### ISSUE TITLE
ModuleNotFoundError: No module named 'mplfinance' 

### ISSUE THREAD

**Issue by lilly-chen** [matplotlib/mplfinance#376]
I am trying to install the the mlfinance package through !pip install --upgrade mplfinance

it was successfully installed

```
Requirement already satisfied: mplfinance in c:\users\chenl\anaconda3\lib\site-packages (0.12.7a12)
Requirement already satisfied: matplotlib in c:\users\chenl\anaconda3\lib\site-packages (from mplfinance) (3.2.1)
Requirement already satisfied: pandas in c:\users\chenl\anaconda3\lib\site-packages (from mplfinance) (0.25.3)
Requirement already satisfied: numpy>=1.11 in c:\users\chenl\anaconda3\lib\site-packages (from matplotlib->mplfinance) (1.15.4)
Requirement already satisfied: python-dateutil>=2.1 in c:\users\chenl\anaconda3\lib\site-packages (from matplotlib->mplfinance) (2.8.1)
Requirement already satisfied: cycler>=0.10 in c:\users\chenl\anaconda3\lib\site-packages (from matplotlib->mplfinance) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\chenl\anaconda3\lib\site-packages (from matplotlib->mplfinance) (1.1.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in c:\users\chenl\anaconda3\lib\site-packages (from matplotlib->mplfinance) (2.1.4)
Requirement already satisfied: six in c:\users\chenl\anaconda3\lib\site-packages (from cycler>=0.10->matplotlib->mplfinance) (1.10.0)
Requirement already satisfied: setuptools in c:\users\chenl\anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg (from kiwisolver>=1.0.1->matplotlib->mplfinance) (27.2.0)
Requirement already satisfied: pytz>=2017.2 in c:\users\chenl\anaconda3\lib\site-packages (from pandas->mplfinance) (2019.3)
```

import mplfinance as mpf

but i am getting an error for ModuleNotFoundError: No module named 'mplfinance'

how can i fix this Thanks!

**Comment by DanielGoldfarb** [comment]
I suggest you install from terminal or command prompt (not from inside a notebook nor ide).

Also if this is a conda environment, you need to make sure that the install location is part of your python import path:
```python
import sys
print(sys.path)
```

Or you may have better luck with `conda install mplfinance`

**Comment by lilly-chen** [comment]
> I suggest you install from terminal or command prompt (not from inside a notebook nor ide).
> 
> Also if this is a conda environment, you need to make sure that the install location is part of your python import path:
> 
> ```python
> import sys
> print(sys.path)
> ```
> 
> Or you may have better luck with `conda install -c conda-forge mplfinance`

Or you may have better luck with conda install -c conda-forge mplfinance this solve my problem. Thanks!!
