### ISSUE TITLE
Any reason for the limit of 10 panels?

### ISSUE THREAD

**Issue by mattsta** [matplotlib/mplfinance#377]
I added my 10th panel today and hit two places where the "validators" rejected the plot.

Easy fix: just increase (or remove) the upper limit check. I increased them to 20 in my local source and everything still works.

Any reason the limit is there in the first place?

https://github.com/matplotlib/mplfinance/blob/385b27c780855f50f76b5c7f2d6af5d6a1490c9c/src/mplfinance/_arg_validators.py#L304

https://github.com/matplotlib/mplfinance/blob/1cc114a56d2068cbb787d33f5bab06a67520f98a/src/mplfinance/plotting.py#L207-L209

**Comment by DanielGoldfarb** [comment]
No reason.  10 was arbitrary.  (I personally can't imagine needing more than 4 or 5).   Will up the limit next time I'm in the code.  Having ***some*** limit helps alert user to typos and similar errors, but i can see upping it to 20 or 30.

**Comment by mattsta** [comment]
Thanks for the quick confirmation!

(and I do admit my charts *are* a mess because I just keep appending more signal panels to compare different trade algorithms, but it works for quick visual comparisons—and thanks for making the library so useful!)

<img width="2806" alt="Screen Shot 2021-04-15 at 16 32 44" src="https://user-images.githubusercontent.com/15594/114950588-3faa8980-9e08-11eb-8fce-80389496b703.png">

<img width="2806" alt="Screen Shot 2021-04-15 at 16 34 02" src="https://user-images.githubusercontent.com/15594/114950723-8304f800-9e08-11eb-8ca9-5544fdfff427.png">

**Comment by DanielGoldfarb** [comment]
@mattsta 
Matt,
Thanks for sharing you charts.  I really enjoy seeing the creative things that people are doing with mpfinance.
All the best.  --Daniel
