### ISSUE TITLE
Feature Request: Extract as image incase of too much data !

### ISSUE THREAD

**Issue by ketav** [matplotlib/mplfinance#390]
**Is your feature request related to a problem? Please describe.**
As it is not possible to see more than 500 candles in the chart, it becomes tedious to analyze, especially if you are looking to backtest a year's data.

**Describe the solution you'd like**
Possibility of the image to be exported where the candles are at least visible.

**Describe alternatives you've considered**
I have otherwise need to extract and create tradingview HTML However that has too many limitations

**Comment by DanielGoldfarb** [comment]
- Have you read [**this information about plotting large amounts of data?**](https://github.com/matplotlib/mplfinance/wiki/Plotting-Too-Much-Data)

- Have you tried [**using kwarg `savefig`**](https://github.com/matplotlib/mplfinance/blob/master/examples/savefig.ipynb) and at the same time setting a high **` dpi `** in the `savefig` dict, *and setting* **`figscale`** to a large number such as 2.0 or 5.0 etc?  You might also try various formats (svg for example) to see if different formats give you better resolution.

Please let me know, after doing all of the above, if this is still an issue.
