### ISSUE TITLE
Is it possible to reduce the left margin on the candle chart?

### ISSUE THREAD

**Issue by piiq** [matplotlib/mplfinance#392]
Hi 👋,
Thanks for this nice tool. It really saves time doing routine things.

I ran into an issue with the candle chart. When I plot this chart using a qt backend there are some margins on the left and right. The one on the left is particularly annoying because it takes considerable amount of space even if I enable tight layout.

Here's how it looks with wight layout on
![image](https://user-images.githubusercontent.com/11668535/118378998-16844100-b5e0-11eb-89a4-db825ce26097.png)

And here's how it looks with regular layout
![image](https://user-images.githubusercontent.com/11668535/118379007-27cd4d80-b5e0-11eb-85db-8adb33b70e47.png)

Here's the code that generates the chart

```python
mc = mpf.make_marketcolors(
    up="green", down="red", edge="black", wick="black", volume="in", ohlc="i"
)

s = mpf.make_mpf_style(marketcolors=mc, gridstyle=":", y_on_right=False)

ap0 = []

if "OC_High_trend" in df_stock.columns:
    ap0.append(
        mpf.make_addplot(df_stock["OC_High_trend"], color="g"),
    )

if "OC_Low_trend" in df_stock.columns:
    ap0.append(
        mpf.make_addplot(df_stock["OC_Low_trend"], color="b"),
    )

fig, axlist = mpf.plot(
    df_stock,
    type="candle",
    mav=(20, 50),
    volume=True,
    title=f"\n{s_ticker} - Last 6 months",
    addplot=ap0,
    xrotation=10,
    style=s,
    figratio=(13, 7),
    figscale=1.10,
    figsize=(plot_autoscale()),
    update_width_config=dict(
        candle_linewidth=1.0, candle_width=0.8, volume_linewidth=1.0
    ),
    # tight_layout=True,
    returnfig=True
)
canvas = FigureCanvas(fig)
```

I've tried to go with `subplot_adjust`, but this wasn't the right direction...

Is there a way to make the plot take up more width, and most important is there a way to get rid of the annoying margin on the left?

**Comment by DanielGoldfarb** [comment]
[**use the `scale_padding` kwarg**](https://github.com/matplotlib/mplfinance/issues/212#issuecomment-655603896)

**Comment by piiq** [comment]
How could I miss that discussion =)
Thanks @DanielGoldfarb worked perfectly.
![image](https://user-images.githubusercontent.com/11668535/118388176-84098f00-b62b-11eb-9efa-b08a7e5496e4.png)
