### ISSUE TITLE
Alines

### ISSUE THREAD

**Issue by wkinn1078** [matplotlib/mplfinance#395]
I created a program for support and resistance with lines starting at point where peak or trough occurred. The program generates the following lists:
```python
s3 = [[('2021-03-04', 373.260009765625) , ('2021-05-17', 373.260009765625)], 
      [('2021-03-25', 385.3399963378906), ('2021-05-17', 385.3399963378906)], 
      [('2021-05-12', 406.3399963378906), ('2021-05-17', 406.3399963378906)]
     ]

r3 = [[('2021-03-17', 399.6499938964844) , ('2021-05-17', 399.6499938964844)], 
      [('2021-04-16', 419.4800109863281) , ('2021-05-17', 419.4800109863281)], 
      [('2021-04-23', 419.8399963378906) , ('2021-05-17', 419.8399963378906)], 
      [('2021-05-07', 424.42999267578125), ('2021-05-17', 424.42999267578125)]
     ]
```
When I run either of the following the plots work:
```python
mpf.plot(Total_Data, type='candle', alines=dict(alines=s3, colors='g'))
mpf.plot(Total_Data, type='candle', alines=dict(alines=r3, colors='r'))
```
However when I try them together, I receive the folowing error:
```python
raise TypeError('kwarg "'+key+'" validator returned False for value: "'+str(value)+'"\n    '+v)
```
using the following:
```python
mpf.plot(Total_Data, type='candle', alines=dict(alines=[s3,r3], colors=['g','r']))
```
Thoughts?
Thank you in advance!

**Comment by DanielGoldfarb** [comment]
Keep in mind the `alines` definition (from the [using lines documentation](https://github.com/matplotlib/mplfinance/blob/master/examples/using_lines.ipynb)):

    a sequence of two or more date/price pairs, or
    a sequence of sequences of two or more date/price pairs

It seems to me you have a "sequence of sequences of sequences ..."
That should be enough to help, but if you still can't figure it, let me know and I will take a closer look.

**Comment by DanielGoldfarb** [comment]
You should use a plus sign to combine s3 and r3, so that the result is a single list (instead of a list of lists).

In other words, instead of this:
```python
mpf.plot(Total_Data, type='candle', alines=dict(alines=[s3,r3], colors=['g','r']))
```

**do this:**
```python
g = ['g']*len(s3)
r = ['r']*len(r3)
mpf.plot(newdf,type='candle',alines=dict(alines=s3+r3,colors=g+r))
```

**Comment by wkinn1078** [comment]
David,

 

Awesome!

 

Thank you.

**Comment by MammadK** [comment]
##### First of all thanks for your great work and passionate support
I have almost the same issue. I want to plot 3 list of lines using `alines`:
```python
L1 = [('1993-05-09', 1.24127), ('1993-05-24', 1.21487), ('1993-05-26', 1.24327), ('1993-07-14', 1.14007)]

L2 = [('1994-07-10', 1.27097), ('1994-07-20', 1.21667), ('1994-10-23', 1.30407), ('1994-12-20', 1.22817)]

L3 = [[('1993-05-09', 1.24127), ('1993-05-26', 1.24127)], [('1993-05-24', 1.21487), ('1993-06-07', 1.21487)],
            [('1993-07-14', 1.14007), ('1993-07-21', 1.14007)], [('1993-07-15', 1.15387), ('1993-08-31', 1.15387)]]
```
for first two lists, I plotted them with this code and worked fine:

```python
lineList = [L1,L2]
mpf.plot(priceDf, type='candle', alines=dict(alines=lineList , colors=['r','b']))
```
after added `L3` to `lineList `, I've encountered the same error. I've tried your solution mentioned here but didn't work for me and raised the same error again. basically in `L3` I want to draw bounded HLines. I looked through docs but didn't find any solution to separate it from first two. how can I solve the problem?

**Comment by DanielGoldfarb** [comment]
@MammadK 
Keep in mind, as stated above, the `alines` definition (from the [using lines documentation](https://github.com/matplotlib/mplfinance/blob/master/examples/using_lines.ipynb)):

    a sequence of two or more date/price pairs, or
    a sequence of sequences of two or more date/price pairs

However `a ` **`sequence of sequences of sequences ...`** (i.e. three levels deep) ... is ***not*** valid.

In your example above, both `L1` and `L2` are `a sequence of two or more date/price pairs`, 
therefore `lineList  = [L1,L2]` is **`a sequence of sequences of two or more date/price pairs`** which is also valid.

However, as you have defined it above, `L3` is ***already*** **`a sequence of sequences of two or more date/price pairs`**, so when you place it into `lineList  = [L1,L2,L3]` you now have a **`sequence of sequences of sequences ...`** (three levels deep) which is **not** valid.  

It's not clear to me what you mean by `"after added L3 to lineList".  If you did this:
```python
lineList2 = lineList + L3
```
then lineList2 should be valid, but I'm not sure it's going to give the lines that you had in mind.  Again, it's not clear what you are trying to do, especially because I can't see any of the other data.

**Comment by MammadK** [comment]
@DanielGoldfarb 
thanks for your reply and apologize for not explained my issue in detail
I added `L3` to `lineList`  as blow:
```python
lineList = [L1,L2,L3]
```
I will try your suggestion:
```python
lineList2 = lineList + L3
```
and will post the result.

**Comment by MammadK** [comment]
@DanielGoldfarb 
Thank you so much. I edited my code based on what you suggested and now it works 

> ```python
> lineList2 = lineList + L3
> ```

`L3` are enclosed Horizontal lines:

![Figure_4](https://user-images.githubusercontent.com/16358451/182258873-e866e3ff-4a59-4d62-ac18-a1be158caf42.png)

**Comment by DanielGoldfarb** [comment]
@MammadK 
Nice plot!!   Thank you for sharing!

**Comment by MammadK** [comment]
@DanielGoldfarb 
thank you for your motivation! I'm trying to define and analyze minor and major swings and price behavior after they're broken. it still needs a lot of optimizations...
