### ISSUE TITLE
How to display Chinese title?

### ISSUE THREAD

**Issue by run27017** [matplotlib/mplfinance#399]
It seems cannot display Chinese well, following is the test code:

```python3
import mplfinance as mpf

mpf.plot(df, title="如何显示中文")
```

`df` is the stock trading code looks like:

```plain
                     open   high    low     close  pre_close  change  pct_chg        vol        amount
date
2021-05-24  23.48  23.60  23.19  23.48      23.49   -0.01  -0.0426  343935.63  8.060922e+05
2021-05-25  23.54  24.73  23.45  24.60      23.48    1.12   4.7700  972374.62  2.363146e+06
2021-05-26  24.64  25.12  24.50  25.01      24.60    0.41   1.6667  919263.78  2.286540e+06
2021-05-27  24.91  25.16  24.52  24.79      25.01   -0.22  -0.8796  504091.36  1.246712e+06
2021-05-28  24.68  24.71  24.16  24.50      24.79   -0.29  -1.1698  492400.73  1.200523e+06
```

My machine is openSUSE Tumbleeweed, and the python version is 3.8.10. The version of `mpf` lib is 0.12.7a17.

**Comment by DanielGoldfarb** [comment]
Ehen mplfinance applies its styles, it first appies a matplotlib style and these matplotlib styles modify rcParams.

The way to make this work would be to include the desired font.family in the style. For example, suppose you wanted to use style 'yahoo' , but with Chinese characters. You should be able to do so like this:
```python
rcpdict = { 'font.family' : 'Noto Sans CJK SC' }
s = mpf.make_mpf_style(base_mpf_style='yahoo',rc=rcpdict)
mpf.plot(data,...,style=s)
```
Please let me know if that works for you.
Thank you. All the best. --Daniel

**Comment by run27017** [comment]
But it doesn't works:

```python3
rcpdict = { 'font.family' : 'Noto Sans CJK SC' }
s = mpf.make_mpf_style(base_mpf_style='yahoo',rc=rcpdict)
mpf.plot(df, title="如何显示中文", style=s)
```

About the figure:

![Figure_1](https://user-images.githubusercontent.com/16550290/120157630-cdf69580-c225-11eb-8b7a-66b207a6fc7b.png)

What does 'Noto Sans CJK SC' mean? Is it related to specific machine or operating system?

**Comment by DanielGoldfarb** [comment]
@run27017 
Thank you very much for adding the details about the solution.   Have a great day!
