### ISSUE TITLE
Show two plots side by side

### ISSUE THREAD

**Issue by MHaefner555** [matplotlib/mplfinance#40]
I've been trying to create two plots and would like to show them side by side. I'm using jupyter but everytime I create the first plot, it stops. I have to close the window to show the second plot.

    mynewdf = mynewdf[['Open', 'High', 'Low', 'Close', periodname1, periodname2]]
    adpict = mpf.make_addplot(mynewdf[[periodname1, periodname2]])
    mpf.plot(mynewdf,type='candle',addplot=adpict) #works

Here, it shows the plot with mynewdf dataset. So far so good. The window opens and even though the code continues with:

    my5mdf = pd.read_csv(filenameM5, delimiter=";",index_col='Date', parse_dates=True, date_parser = mydateparser)
    my5mdf = my5mdf[['Open', 'High', 'Low', 'Close']]
    mpf.plot(my5mdf,type='candle')

I can only see this second plot, when closing the first window. What is the reason for that? I'm pretty sure, I'm doing something wrong here but I'm stuck. Thanks for any help!
regards,
Marco

**Comment by DanielGoldfarb** [comment]
@MHaefner555 
Marco,
  It's hard to tell exactly what you are doing.  Is all of the above code in one jupyter cell?  Also, _usually_ in jupyter the plots are inline, not in a separate window. 

  That said, you might try this:  In the call to the first call to `mpf.plot()`, add the kwarg `block=False`.  You should be able to do many plots, having `block=False` in all **except the last plot** (do NOT do `block=False` in the last plot).

Let me know if that helps.    
Thanks.   --Daniel

**Comment by DanielGoldfarb** [comment]
closing.  @MHaefner555 you can re-open this issue if you still have a question on this same issue.
