### ISSUE TITLE
I need to show near last candlestick a closing price of this candle.

### ISSUE THREAD

**Issue by lirem** [matplotlib/mplfinance#406]
I need to show near last candlestick a closing price of this candle. How i can make this?

**Comment by DanielGoldfarb** [comment]
Your best bet (for now) is to call [`Axes.text()`](https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.text.html).

See [this answer here](https://github.com/matplotlib/mplfinance/issues/387#issuecomment-828135146) for more complete information.
