### ISSUE TITLE
complete list of linestyles?

### ISSUE THREAD

**Issue by prRZ5F4LXZ** [matplotlib/mplfinance#407]
https://github.com/matplotlib/mplfinance/blob/master/examples/using_lines.ipynb

I see the above page mentions some linestyles. But I would like to have a complete list of available linestyles. Could anybody where is such a list? Thanks.

**Comment by DanielGoldfarb** [comment]
You can see a complete list here:
https://matplotlib.org/stable/api/_as_gen/matplotlib.lines.Line2D.html#matplotlib.lines.Line2D.set_linestyle
