### ISSUE TITLE
How do I draw daily horizontal lines?

### ISSUE THREAD

**Issue by esmesm20** [matplotlib/mplfinance#411]
Hello,

Thank you for this wonderful package. I looked through the issues and doc, but couldn't find how to draw horizontal lines that are restricted to certain time ranges. 
![ex](https://user-images.githubusercontent.com/65680255/124893142-7aa3ff80-dfa8-11eb-82aa-e65e21df9f86.png)
I uploaded an example where the bars are drawn for each week. 

Thank you!

**Comment by DanielGoldfarb** [comment]
For such date limited horizontal lines, you use the **`alines`** kwarg.   
See [**Using Lines**](https://github.com/matplotlib/mplfinance/blob/master/examples/using_lines.ipynb) documentation.

**Comment by fxhuhn** [comment]
Yes, alines works perfect in this case. I used it in my example.

![image](https://user-images.githubusercontent.com/49436733/124903336-27e83900-dfe4-11eb-860c-8560599db7de.png)

**Comment by esmesm20** [comment]
Thank you guy for replying.

I should have been clearer in my question.. Is there a way to have those lines restricted to single days?

![ex](https://user-images.githubusercontent.com/65680255/125031262-64ef1280-e05a-11eb-8485-7c8b6e344175.png)

**Comment by esmesm20** [comment]
I found out the solution! I was being stupid. Should use type='scatter' with marker="_"

**Comment by fxhuhn** [comment]
yes, in this case scatter plots are a better solution. alines starts and ends in the middle of a candle.

here is another example:
![image](https://user-images.githubusercontent.com/49436733/125037838-ef546800-e094-11eb-840a-e5cb625a599d.png)
