### ISSUE TITLE
horizontal rays

### ISSUE THREAD

**Issue by apptl** [matplotlib/mplfinance#412]
Hello, I am trying to draw horizontal rays for support and resistance from a certain point to the end date. but I am not sure how to do it. can someone please help? The attached files show my graph and desired graph. I am using this currently.

mf.plot(amzn, mav = (34, 50, 200), type = 'candle',hlines=dict(hlines=values,colors=color),
                volume = True, figratio = (10,5), 
                style = 'binance', title = name, 
                tight_layout = True,)

![Screen Shot 2021-07-08 at 10 53 09 PM](https://user-images.githubusercontent.com/20527350/125021088-99090a00-e03f-11eb-9015-67f9e866f5f3.png)
![Screen Shot 2021-07-08 at 10 53 42 PM](https://user-images.githubusercontent.com/20527350/125021092-99a1a080-e03f-11eb-8d64-7ebe1fca67eb.png)

**Comment by DanielGoldfarb** [comment]
`hlines` by definition go completely from one side of the plot to the other.

To do what you want, you need to [**use kwarg `alines`**](https://github.com/matplotlib/mplfinance/blob/master/examples/using_lines.ipynb) instead.
