### ISSUE TITLE
How to work with wxPython？

### ISSUE THREAD

**Issue by OceanHorn** [matplotlib/mplfinance#413]
Is there any method to show a figure in wxpython project？Thanks.

**Comment by DanielGoldfarb** [comment]
I am not familiar with wxpython, however there appear to be a couple of differnet ways to use wxpython with matplotlib.  
I suggest you search https://www.google.com/search?q=matplotlib+and+wxpython

You may also find [this mplfinance page](https://github.com/matplotlib/mplfinance/wiki/Acessing-mplfinance-Figure-and-Axes-objects) and the links therein useful.  

Sorry I can't provide more detail than that right now, but that should be enough information to get you going.
