### ISSUE TITLE
Add Weekly Data

### ISSUE THREAD

**Issue by tomas890628** [matplotlib/mplfinance#421]
I have a data is weekly data
It only Calculate once a week
Can I add it in the plot?

**Comment by DanielGoldfarb** [comment]
Of course you can plot weekly data.  Have you tried?

Your question is possibly ambiguous.   What do you mean **add it** in the plot?

**Comment by tomas890628** [comment]
Hi, first thanks for your reply,
My basic data (price,volume...etc.) is list so I put them in the dict  then use `pd.dataframe(dict)` so that mplfinance can read my data
I have been try two different solution:
1. I put the new weekly data in the dict , it  will say that the list length must be  same. 
2. I append the list to the dataframe before the plot, but it still can't work

The basic data and the new weekly data is from different webpages, I didn't crawl the date in the new weekly data page.
Sorry I'm new in Python and mplfinance, Thanks again for your help

**Comment by DanielGoldfarb** [comment]
Please upload your data here (csv files) and show your code to be able to reproduce the problem you are having.  Show what you have tried so far, and be sure to also post completely any error messages you are getting.

**Comment by tomas890628** [comment]
All of my data is crawl, I didn't use any csv file.
`#%%
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import Select
from selenium.common.exceptions import NoSuchElementException
from selenium.common.exceptions import NoAlertPresentException

from matplotlib import pyplot as plt
from pandas.io.formats import style
from bs4 import BeautifulSoup
from datetime import datetime
import requests
import re
import pandas as pd
import mplfinance as mpf
import random
import time
from talib import MACD
import numpy as np
import talib

##Format Date
def transform_date(date): 
        y, m, d = date.split('/')
        return str(int(y)+1911) + '/' + m  + '/' + d

## Create the List we'll need
date_lst=[]         ##日期
volume_lst=[]       ##成交量
opening_lst=[]      ##開盤價
highest_lst=[]      ##盤中高點
lowest_lst=[]       ##盤中低點
closing_lst=[]      ##收盤價
validips = []       ##proxypool

option_lst=[]
re_lst=[]
optiondate_lst=[]

getdate_url="https://www.tdcc.com.tw/portal/zh/smWeb/qryStock"

driver = webdriver.Chrome("G:\chromedriver_win32\chromedriver.exe")

driver.get(getdate_url)
Select(driver.find_element_by_name("scaDate")).select_by_visible_text("20200911")

driver_soup=BeautifulSoup(driver.page_source, 'html.parser')

options=driver_soup.find_all('option')

for op_text in options:
    option_lst.append(op_text.text)

re_lst=option_lst[::-1]

option_lst.clear()

for date in re_lst:
    optiondate_lst.append(date)
    driver.get(getdate_url)
    Select(driver.find_element_by_name("scaDate")).select_by_visible_text(date)
    driver.find_element_by_id("StockNo").clear()
    driver.find_element_by_id("StockNo").send_keys("4989")
    driver.find_element_by_xpath(u"//input[@value='查詢']").click()

    soup=BeautifulSoup(driver.page_source, 'html.parser')
    table=soup.find_all('table','table')

    for tr in table:
        trs=tr.find_all('tr')
        for td in trs:
            if(len(td.find_all('td'))!=0):
                tds=td.find_all('td')[1].text
                if tds=="1,000,001以上":
                    print(td.find_all('td')[2].text,"人")
                    option_lst.append(float(td.find_all('td')[2].text))

driver.close()
#The new data is crawl here
quandict={'Date':optiondate_lst,'Quan':option_lst}

## Init the date
months=["20200801","20200901","20201001","20201101","20201201","20210101","20210201","20210301","20210401","20210501","20210601"]
'''
for i in range(1,12):
    if i <10:
        months.append("20210"+str(i)+"01")
    else:
        months.append("2021"+str(i)+"01")
'''
print(months)

stockNo=[]
stockNo.append("4989")
# stockNo.append("2603")

def get_proxypool():
    res_ip = requests.get('https://free-proxy-list.net/')

    import re
    ip_list = re.findall('\d+\.\d+\.\d+\.\d+:\d+', res_ip.text)
    for ip in ip_list:
        try:
            res = requests.get('https://api.ipify.org?format=json',proxies = {'http':ip}, timeout = 5)
            validips.append({'ip':ip})
            ##print(ip)
        except:
            continue
    
        if len(validips)==5:
            break

get_proxypool()

## Init the url to add date、stock in next step
url_init = "https://www.twse.com.tw/exchangeReport/STOCK_DAY?response=html&date={}&stockNo={}"

## First for loop for all stock in stockNo List
for stock in stockNo:
    ## Second for loop for the date
    for month in months:

        ## Add the date、stock to format the url
        url=url_init.format(month,stock)

        proxy=validips[random.randint(0,4)]
       

        ## Analytics the html page
        proxies={"http": proxy}
        ##print(proxies)
        res=requests.get(url,proxies={"http": proxy})
        
        ##time.sleep(10)
    
        soup=BeautifulSoup(res.text,'html.parser')
        ## Get data in the tbody
        tbody=soup.find_all('tbody')
        ## Get tr  in the tbody
        for tr in tbody:
            trs=tr.find_all('tr')

            for td in trs:
                ## Get data we need in the tr
                
                ## First for the date
                date_txt=transform_date(td.find_all('td')[0].text)
                date_lst.append(datetime.strptime(date_txt,'%Y/%m/%d'))

                ## Second for the volume
                volume_txt=td.find_all('td')[1].text
                volume_lst.append(int(volume_txt.replace(',','')))
                
                ## Third for the opening price
                opening_txt=td.find_all('td')[3].text
                opening_lst.append(float(opening_txt))

                ## Fourth for the highest price 
                highest_txt=td.find_all('td')[4].text
                highest_lst.append(float(highest_txt))

                ## Fifth for the lowest price
                lowest_txt=td.find_all('td')[5].text
                lowest_lst.append(float(lowest_txt))

                ## Sixth is the closing price
                closing_txt=td.find_all('td')[6].text
                closing_lst.append(float(closing_txt))
                ##np.append(closingarray,float(closing_txt))

        res.close()
        time.sleep(3)



    ## List to dict

    dict={'Date':date_lst,'Volume':volume_lst,'Open':opening_lst,'High':highest_lst,'Low':lowest_lst,'Close':closing_lst}
    df=pd.DataFrame(dict)

    ## Dict to DF to mpf

    data = pd.DataFrame.from_dict(dict) 
    data.set_index('Date', inplace=True)

    data['Volume']=data['Volume']/10000

    # Get Closing Price Array
    closingarray=np.array(closing_lst)

    # Calculate the MACD
    data['macd'],data['macds'],data['macdh']=MACD(closingarray)

    # When Dif >0 it need to be green,beside is red
    dif_colors = ['r' if dif >= 0 else 'g' for dif in data["macdh"]]

    # Create the plot
    macd_panel_num=1
    macd_plot = mpf.make_addplot(data["macd"], panel=macd_panel_num, color='y', title="MACD")
    macds_plot = mpf.make_addplot(data["macds"], panel=macd_panel_num, color='b')
    macdh_plot = mpf.make_addplot(data["macdh"], type='bar', panel=macd_panel_num, color=dif_colors)
    

    #data=data.append(option_lst)
    #quan_plot = mpf.make_addplot(data["Quan"], panel=2, color='b')
    

    ## Customize the Style
    tw = mpf.make_marketcolors(up='r',down='g',volume={'up':'r','down':'g'})
    customize_style  = mpf.make_mpf_style(marketcolors=tw)

    ## Add plots to the list

    plots=[macd_plot,macdh_plot,macds_plot,quan_plot]


    mpf.plot(data,type='candle',style=customize_style,mav=(3,6,9),title=stock,addplot=plots,volume=True,volume_panel=2)


    ##print(proxy)
    
    ## Clear list to create the next stock
    date_lst.clear()      
    volume_lst.clear()     
    opening_lst.clear()     
    highest_lst.clear()       
    lowest_lst.clear()      
    closing_lst.clear()


quandf=pd.DataFrame.from_dict(quandict)

print(quandf)
`

Solution 1 Code:
`dict={'Date':date_lst,'Volume':volume_lst,'Open':opening_lst,'High':highest_lst,'Low':lowest_lst,'Close':closing_lst}`
You have to replace the code  to:
`dict={'Date':date_lst,'Volume':volume_lst,'Open':opening_lst,'High':highest_lst,'Low':lowest_lst,'Close':closing_lst,'Quan':option_lst}`
The ERROR will like this:
`---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
c:\Users\user\Desktop\專題檔案\Practice\Candlestick\data MACD stockquan.py in 
    178 
    179     dict={'Date':date_lst,'Volume':volume_lst,'Open':opening_lst,'High':highest_lst,'Low':lowest_lst,'Close':closing_lst,'Quan':option_lst}
--> 180     df=pd.DataFrame(dict)
    181 
    182     ## Dict to DF to mpf

C:\Python39\lib\site-packages\pandas\core\frame.py in __init__(self, data, index, columns, dtype, copy)
    612         elif isinstance(data, dict):
    613             # GH#38939 de facto copy defaults to False only in non-dict cases
--> 614             mgr = dict_to_mgr(data, index, columns, dtype=dtype, copy=copy, typ=manager)
    615         elif isinstance(data, ma.MaskedArray):
    616             import numpy.ma.mrecords as mrecords

C:\Python39\lib\site-packages\pandas\core\internals\construction.py in dict_to_mgr(data, index, columns, dtype, typ, copy)
    460         # TODO: can we get rid of the dt64tz special case above?
    461 
--> 462     return arrays_to_mgr(
    463         arrays, data_names, index, columns, dtype=dtype, typ=typ, consolidate=copy
    464     )

C:\Python39\lib\site-packages\pandas\core\internals\construction.py in arrays_to_mgr(arrays, arr_names, index, columns, dtype, verify_integrity, typ, consolidate)
    115         # figure out the index, if necessary
    116         if index is None:
--> 117             index = _extract_index(arrays)
    118         else:
    119             index = ensure_index(index)

C:\Python39\lib\site-packages\pandas\core\internals\construction.py in _extract_index(data)
    621             lengths = list(set(raw_lengths))
    622             if len(lengths) > 1:
--> 623                 raise ValueError("All arrays must be of the same length")
    624 
    625             if have_dicts:

ValueError: All arrays must be of the same length`



Solution 2 Code:
You need to unmarkdown this:
`    #data=data.append(option_lst)
     #quan_plot = mpf.make_addplot(data["option_lst"], panel=2, color='b')`

Then the error code is:
`---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
C:\Python39\lib\site-packages\pandas\core\indexes\base.py in get_loc(self, key, method, tolerance)
   3360             try:
-> 3361                 return self._engine.get_loc(casted_key)
   3362             except KeyError as err:

C:\Python39\lib\site-packages\pandas\_libs\index.pyx in pandas._libs.index.IndexEngine.get_loc()

C:\Python39\lib\site-packages\pandas\_libs\index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas\_libs\hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

pandas\_libs\hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 'option_lst'

The above exception was the direct cause of the following exception:

KeyError                                  Traceback (most recent call last)
c:\Users\賴俊諺\Desktop\專題檔案\Practice\Candlestick\data MACD stockquan.py in 
    204 
    205     data=data.append(option_lst)
--> 206     quan_plot = mpf.make_addplot(data["option_lst"], panel=2, color='b')
    207 
    208 

C:\Python39\lib\site-packages\pandas\core\frame.py in __getitem__(self, key)
   3453             if self.columns.nlevels > 1:
   3454                 return self._getitem_multilevel(key)
-> 3455             indexer = self.columns.get_loc(key)
   3456             if is_integer(indexer):
   3457                 indexer = [indexer]

C:\Python39\lib\site-packages\pandas\core\indexes\base.py in get_loc(self, key, method, tolerance)
   3361                 return self._engine.get_loc(casted_key)
   3362             except KeyError as err:
-> 3363                 raise KeyError(key) from err
   3364 
   3365         if is_scalar(key) and isna(key) and not self.hasnans:

KeyError: 'option_lst'`

**Comment by DanielGoldfarb** [comment]
Thank you.  In order to make it easier for me to play around with the code, and to see what's going on, regarding this section of code, can you please make the changes listed below as "### DUMP TO CSV FILE:" and then attach the resulting two csv files ("df.csv" and "data.csv")?  (Please make sure to dump data.csv ***after*** the MACD calculation).  Thank you.

```python
#List to dict

    dict={'Date':date_lst,'Volume':volume_lst,'Open':opening_lst,'High':highest_lst,'Low':lowest_lst,'Close':closing_lst}
    df=pd.DataFrame(dict)

    ### DUMP TO CSV FILE:
    df.to_csv("df.csv")

    #Dict to DF to mpf

    data = pd.DataFrame.from_dict(dict) 
    data.set_index('Date', inplace=True)

    data['Volume']=data['Volume']/10000

    #Get Closing Price Array
    closingarray=np.array(closing_lst)

    #Calculate the MACD
    data['macd'],data['macds'],data['macdh']=MACD(closingarray)

    ### DUMP TO CSV FILE:
    df.to_csv("data.csv")

```

**Comment by tomas890628** [comment]
I have been create the csv file but github said that I can't upload this type of the file
https://drive.google.com/drive/folders/1hZZ1FHpd1ghP2R6k4QmRxbN5QuNngnd4?usp=sharing
I upload it to google drive,
df.csv and data.csv is the file exclude and include macd data.
quan.csv is the new weekly data I want to add in the plot
