### ISSUE TITLE
ValueError: Invalid format string.  -> 1426             dateformat = mdates.num2date(date).strftime(self.fmt)

### ISSUE THREAD

**Issue by Stevearama** [matplotlib/mplfinance#423]
I am using windows 10.  Anaconda.

I'm inexperienced, and so I've made this a question rather than a bug.

I am having an issue with one of the examples in pandas-ta.  I reported it there and was told the issue was with mplfinance, so I'm reporting it here in the hope of getting a resolution.  

Thank you for your hard work.

---

```python
ValueError                                Traceback (most recent call last)
~\anaconda3\envs\test1\lib\site-packages\IPython\core\formatters.py in __call__(self, obj)
    339                 pass
    340             else:
--> 341                 return printer(obj)
    342             # Finally look for special method names
    343             method = get_real_method(obj, self.print_method)

~\anaconda3\envs\test1\lib\site-packages\IPython\core\pylabtools.py in <lambda>(fig)
    246 
    247     if 'png' in formats:
--> 248         png_formatter.for_type(Figure, lambda fig: print_figure(fig, 'png', **kwargs))
    249     if 'retina' in formats or 'png2x' in formats:
    250         png_formatter.for_type(Figure, lambda fig: retina_figure(fig, **kwargs))

~\anaconda3\envs\test1\lib\site-packages\IPython\core\pylabtools.py in print_figure(fig, fmt, bbox_inches, **kwargs)
    130         FigureCanvasBase(fig)
    131 
--> 132     fig.canvas.print_figure(bytes_io, **kw)
    133     data = bytes_io.getvalue()
    134     if fmt == 'svg':

~\anaconda3\envs\test1\lib\site-packages\matplotlib\backend_bases.py in print_figure(self, filename, dpi, facecolor, edgecolor, orientation, format, bbox_inches, pad_inches, bbox_extra_artists, backend, **kwargs)
   2191                            else suppress())
   2192                     with ctx:
-> 2193                         self.figure.draw(renderer)
   2194 
   2195                     bbox_inches = self.figure.get_tightbbox(

~\anaconda3\envs\test1\lib\site-packages\matplotlib\artist.py in draw_wrapper(artist, renderer, *args, **kwargs)
     39                 renderer.start_filter()
     40 
---> 41             return draw(artist, renderer, *args, **kwargs)
     42         finally:
     43             if artist.get_agg_filter() is not None:

~\anaconda3\envs\test1\lib\site-packages\matplotlib\figure.py in draw(self, renderer)
   1861 
   1862             self.patch.draw(renderer)
-> 1863             mimage._draw_list_compositing_images(
   1864                 renderer, self, artists, self.suppressComposite)
   1865 

~\anaconda3\envs\test1\lib\site-packages\matplotlib\image.py in _draw_list_compositing_images(renderer, parent, artists, suppress_composite)
    129     if not_composite or not has_images:
    130         for a in artists:
--> 131             a.draw(renderer)
    132     else:
    133         # Composite any adjacent images together

~\anaconda3\envs\test1\lib\site-packages\matplotlib\artist.py in draw_wrapper(artist, renderer, *args, **kwargs)
     39                 renderer.start_filter()
     40 
---> 41             return draw(artist, renderer, *args, **kwargs)
     42         finally:
     43             if artist.get_agg_filter() is not None:

~\anaconda3\envs\test1\lib\site-packages\matplotlib\cbook\deprecation.py in wrapper(*inner_args, **inner_kwargs)
    409                          else deprecation_addendum,
    410                 **kwargs)
--> 411         return func(*inner_args, **inner_kwargs)
    412 
    413     return wrapper

~\anaconda3\envs\test1\lib\site-packages\matplotlib\axes\_base.py in draw(self, renderer, inframe)
   2705                 artists.remove(spine)
   2706 
-> 2707         self._update_title_position(renderer)
   2708 
   2709         if not self.axison or inframe:

~\anaconda3\envs\test1\lib\site-packages\matplotlib\axes\_base.py in _update_title_position(self, renderer)
   2636                 if (ax.xaxis.get_ticks_position() in ['top', 'unknown']
   2637                         or ax.xaxis.get_label_position() == 'top'):
-> 2638                     bb = ax.xaxis.get_tightbbox(renderer)
   2639                 else:
   2640                     bb = ax.get_window_extent(renderer)

~\anaconda3\envs\test1\lib\site-packages\matplotlib\axis.py in get_tightbbox(self, renderer, for_layout_only)
   1107             return
   1108 
-> 1109         ticks_to_draw = self._update_ticks()
   1110 
   1111         self._update_label_position(renderer)

~\anaconda3\envs\test1\lib\site-packages\matplotlib\axis.py in _update_ticks(self)
   1020         """
   1021         major_locs = self.get_majorticklocs()
-> 1022         major_labels = self.major.formatter.format_ticks(major_locs)
   1023         major_ticks = self.get_major_ticks(len(major_locs))
   1024         self.major.formatter.set_locs(major_locs)

~\anaconda3\envs\test1\lib\site-packages\matplotlib\ticker.py in format_ticks(self, values)
    261         """Return the tick labels for all the ticks at once."""
    262         self.set_locs(values)
--> 263         return [self(value, i) for i, value in enumerate(values)]
    264 
    265     def format_data(self, value):

~\anaconda3\envs\test1\lib\site-packages\matplotlib\ticker.py in <listcomp>(.0)
    261         """Return the tick labels for all the ticks at once."""
    262         self.set_locs(values)
--> 263         return [self(value, i) for i, value in enumerate(values)]
    264 
    265     def format_data(self, value):

~\AppData\Roaming\Python\Python38\site-packages\mplfinance\_utils.py in __call__(self, x, pos)
   1424         else:
   1425             date = self.dates[ix]
-> 1426             dateformat = mdates.num2date(date).strftime(self.fmt)
   1427         #print('x=',x,'pos=',pos,'dates[',ix,']=',date,'dateformat=',dateformat)
   1428         return dateformat

ValueError: Invalid format string
```

**Comment by DanielGoldfarb** [comment]
The traceback is helpful.  But also need to see your data, **and code** up to the point of calling `mpf.plot()`

**Comment by lingsond** [comment]
Here's a link to the example notebook: https://github.com/twopirllc/pandas-ta/blob/main/examples/example.ipynb. I experienced the same problem, and I saw the issue posted by @Stevearama in pandas-ta github. According to the author, the problem lies in the mplfinance module, and Stevearama should open an issue here, thus I came here to look for the issue/solution. Since he hasn't replied yet, I'm posting the link to the example file used that create this issue to speed up the solving of this issue.
The notebook can be run just like that (with the required packages installed), and the code should be in the 'Chart' class.
I hope this information would help.

**Comment by DanielGoldfarb** [comment]
@lingsond  Just to confirm, are you saying if I run the example notebook, then I should be able to see/reproduce this error?

**Comment by DanielGoldfarb** [comment]
@lingsond  @Stevearama 
What I need to see is your call to `mpf.plot()` plus any code leading up to it that would have been involved in setting its parameters.  Alternatively, printing out the value of all parameters just prior to the `mpf.plot()` call would be adequate.

The complaint appears to be that the value of the `datetime_format` kwarg passed into `mpf.plot()` is **an invalid `strftime()` format string**.   

In the [example notebook that you provided](https://github.com/twopirllc/pandas-ta/blob/main/examples/example.ipynb), the kwarg is set as `datetime_format="%-m/%-d/%Y"` which is fine.  So somewhere, someone is likely passing an invalid format string.  

If you think otherwise, then please provide an minimally reproducible verifiable code example that exhibits this bug.

---

@twopirllc -
Kevin, if you suspect the issue is with mplfinance, please provide an minimally reproducible verifiable code example that exhibits this bug to support your suspicion.   Thanks.  --Daniel

**Comment by DanielGoldfarb** [comment]
Also, to everyone looking at this:   Try calling `mpf.plot()` with kwarg `show_nontrading=True` and tell me whether the problem goes away or not.  Thank you.

**Comment by lingsond** [comment]
Sorry for late reply.

@DanielGoldfarb yes, what I meant is you just need to run the example notebook to reproduce the error.

And I tried running mpf.plot() with show_nontrading=True, the result was still the same with the same error.

**Comment by DanielGoldfarb** [comment]
OK.  I have tried multiple times on multiple platforms running [**the entire example notebook**](https://github.com/twopirllc/pandas-ta/blob/main/examples/example.ipynb) and it runs fine.  I cannot reproduce this problem. 

As mentioned above, the final error message in the traceback that was included above, i.e.
```python
~\AppData\Roaming\Python\Python38\site-packages\mplfinance\_utils.py in __call__(self, x, pos)
   1424         else:
   1425             date = self.dates[ix]
-> 1426             dateformat = mdates.num2date(date).strftime(self.fmt)
   1427         #print('x=',x,'pos=',pos,'dates[',ix,']=',date,'dateformat=',dateformat)
   1428         return dateformat
ValueError: Invalid format string
```
indicates that a bad format string is being passed into `strftime()`

As you can see [**from here**](https://github.com/matplotlib/mplfinance/blob/master/src/mplfinance/_utils.py#L1409-L1413) mplfinance sets a valid default value for the format.  

In addition to that, in the [**example from pandas-ta**](https://github.com/twopirllc/pandas-ta/blob/main/examples/example.ipynb), if you search for the call to `mpf.plot()` you will see kwarg `datetime_format="%-m/%-d/%Y"` which is also valid.

I see no evidence that this is an mplfinance issue.  However I will point out this:  mplfinance is installing it's own "ticker formatter" class into matplotlib [**here**](https://github.com/matplotlib/mplfinance/blob/master/src/mplfinance/plotting.py#L373-L377), derived from `matplotlib.ticker` [**here**](https://github.com/matplotlib/mplfinance/blob/master/src/mplfinance/_utils.py#L1394-L1429).  We can hypothesize one possibility *may be* that somewhere, someone is calling matplotlib directly, with data or a format string that is incompatable with that ticker formatter.

---

At this point, the onus is upon whoever may think this is an mplfinance issue, to **prove** that it is an mplfinance issue, by providing actual code that is a minimal verifiable reproducible example demonstrating this issue.  Please note, by minimal I strongly suggest that you provide input data from a csv to call `mpf.plot()`, and keep your example indipendent of any packages that gather or analyze data (such as `yfinance` and/or `pandas-ta`).  That is the primary way to demonstrate that it is not the result of any of those other packages.  If you can provide code that reproduces the problem with nothing more than a csv file, plain pandas, and mplfinance, then I will look into this further.

Sorry I can't be of further assistence, but at this point if you want me to look into this any further you will have to help me to reproduce the problem.  Feel free to Re-open this issue *if you can provide both data and code for a minimal, reproducible example.*

**Comment by twopirllc** [comment]
Hello @DanielGoldfarb,

I apologize for not replying sooner to this Issue and discussion. I have been trying to find time to devote to this Issue and collect the requested data.

> At this point, the onus is upon whoever may think this is an mplfinance issue, to **prove** that it is an mplfinance issue, by providing actual code that is a minimal verifiable reproducible example demonstrating this issue.

I agree. I requested @Stevearama to post the Issue here to see if you had insight on what could cause this stack trace or had seen something similar in your Issues. I was hoping for guidance on how to debug this Issue which you have graciously provided.

<br/>

> Kevin, if you suspect the issue is with mplfinance, please provide an minimally reproducible verifiable code example that exhibits this bug to support your suspicion.

On my M1 MacBook that I develop on, I have never encountered this error nor can I replicate it.

However, I do get the ValueError on my Windows 10 Pro with virtualenv.
My Windows Python v3.7.4 packages are:
numpy v1.21.1
matplotlib v3.4.2
mplfinance 0.12.7a17
pandas v1.3.1
pandas-ta v0.3.14b0
yfinance 0.1.63

Similar ValueError from my Windows Box
```sh
------------------------------------------------------------------------
ValueError                             Traceback (most recent call last)
c:\users\appli\documents\github\pta-nberror\env\lib\site-packages\IPython\core\formatters.py in __call__(self, obj)
    339                 pass
    340             else:
--> 341                 return printer(obj)
    342             # Finally look for special method names
    343             method = get_real_method(obj, self.print_method)

c:\users\appli\documents\github\pta-nberror\env\lib\site-packages\IPython\core\pylabtools.py in <lambda>(fig)
    248 
    249     if 'png' in formats:
--> 250         png_formatter.for_type(Figure, lambda fig: print_figure(fig, 'png', **kwargs))
    251     if 'retina' in formats or 'png2x' in formats:
    252         png_formatter.for_type(Figure, lambda fig: retina_figure(fig, **kwargs))

c:\users\appli\documents\github\pta-nberror\env\lib\site-packages\IPython\core\pylabtools.py in print_figure(fig, fmt, bbox_inches, **kwargs)
    132         FigureCanvasBase(fig)
    133 
--> 134     fig.canvas.print_figure(bytes_io, **kw)
    135     data = bytes_io.getvalue()
    136     if fmt == 'svg':

c:\users\appli\documents\github\pta-nberror\env\lib\site-packages\matplotlib\backend_bases.py in print_figure(self, filename, dpi, facecolor, edgecolor, orientation, format, bbox_inches, pad_inches, bbox_extra_artists, backend, **kwargs)
   2228                        else suppress())
   2229                 with ctx:
-> 2230                     self.figure.draw(renderer)
   2231 
   2232             if bbox_inches:

c:\users\appli\documents\github\pta-nberror\env\lib\site-packages\matplotlib\artist.py in draw_wrapper(artist, renderer, *args, **kwargs)
     72     @wraps(draw)
     73     def draw_wrapper(artist, renderer, *args, **kwargs):
---> 74         result = draw(artist, renderer, *args, **kwargs)
     75         if renderer._rasterizing:
     76             renderer.stop_rasterizing()

c:\users\appli\documents\github\pta-nberror\env\lib\site-packages\matplotlib\artist.py in draw_wrapper(artist, renderer, *args, **kwargs)
     49                 renderer.start_filter()
     50 
---> 51             return draw(artist, renderer, *args, **kwargs)
     52         finally:
     53             if artist.get_agg_filter() is not None:

c:\users\appli\documents\github\pta-nberror\env\lib\site-packages\matplotlib\figure.py in draw(self, renderer)
   2779             self.patch.draw(renderer)
   2780             mimage._draw_list_compositing_images(
-> 2781                 renderer, self, artists, self.suppressComposite)
   2782 
   2783             for sfig in self.subfigs:

c:\users\appli\documents\github\pta-nberror\env\lib\site-packages\matplotlib\image.py in _draw_list_compositing_images(renderer, parent, artists, suppress_composite)
    130     if not_composite or not has_images:
    131         for a in artists:
--> 132             a.draw(renderer)
    133     else:
    134         # Composite any adjacent images together

c:\users\appli\documents\github\pta-nberror\env\lib\site-packages\matplotlib\artist.py in draw_wrapper(artist, renderer, *args, **kwargs)
     49                 renderer.start_filter()
     50 
---> 51             return draw(artist, renderer, *args, **kwargs)
     52         finally:
     53             if artist.get_agg_filter() is not None:

c:\users\appli\documents\github\pta-nberror\env\lib\site-packages\matplotlib\_api\deprecation.py in wrapper(*inner_args, **inner_kwargs)
    429                          else deprecation_addendum,
    430                 **kwargs)
--> 431         return func(*inner_args, **inner_kwargs)
    432 
    433     return wrapper

c:\users\appli\documents\github\pta-nberror\env\lib\site-packages\matplotlib\axes\_base.py in draw(self, renderer, inframe)
   2879                 artists.remove(spine)
   2880 
-> 2881         self._update_title_position(renderer)
   2882 
   2883         if not self.axison or inframe:

c:\users\appli\documents\github\pta-nberror\env\lib\site-packages\matplotlib\axes\_base.py in _update_title_position(self, renderer)
   2810                 if (ax.xaxis.get_ticks_position() in ['top', 'unknown']
   2811                         or ax.xaxis.get_label_position() == 'top'):
-> 2812                     bb = ax.xaxis.get_tightbbox(renderer)
   2813                 else:
   2814                     bb = ax.get_window_extent(renderer)

c:\users\appli\documents\github\pta-nberror\env\lib\site-packages\matplotlib\axis.py in get_tightbbox(self, renderer, for_layout_only)
   1079             return
   1080 
-> 1081         ticks_to_draw = self._update_ticks()
   1082 
   1083         self._update_label_position(renderer)

c:\users\appli\documents\github\pta-nberror\env\lib\site-packages\matplotlib\axis.py in _update_ticks(self)
   1022         """
   1023         major_locs = self.get_majorticklocs()
-> 1024         major_labels = self.major.formatter.format_ticks(major_locs)
   1025         major_ticks = self.get_major_ticks(len(major_locs))
   1026         self.major.formatter.set_locs(major_locs)

c:\users\appli\documents\github\pta-nberror\env\lib\site-packages\matplotlib\ticker.py in format_ticks(self, values)
    261         """Return the tick labels for all the ticks at once."""
    262         self.set_locs(values)
--> 263         return [self(value, i) for i, value in enumerate(values)]
    264 
    265     def format_data(self, value):

c:\users\appli\documents\github\pta-nberror\env\lib\site-packages\matplotlib\ticker.py in <listcomp>(.0)
    261         """Return the tick labels for all the ticks at once."""
    262         self.set_locs(values)
--> 263         return [self(value, i) for i, value in enumerate(values)]
    264 
    265     def format_data(self, value):

c:\users\appli\documents\github\pta-nberror\env\lib\site-packages\mplfinance\_utils.py in __call__(self, x, pos)
   1424         else:
   1425             date = self.dates[ix]
-> 1426             dateformat = mdates.num2date(date).strftime(self.fmt)
   1427         #print('x=',x,'pos=',pos,'dates[',ix,']=',date,'dateformat=',dateformat)
   1428         return dateformat

ValueError: Invalid format string
```

<br/>

> Try calling ```mpf.plot()``` with kwarg ```show_nontrading=True``` and tell me whether the problem goes away or not.

Works for me either ```True``` or ```False``` on my MacBook. However on my Windows box, neither work and still creates the ValueError.

Also removing the import ```import matplotlib.ticker as ticker``` at the top of [example.ipynb](https://github.com/twopirllc/pandas-ta/blob/main/examples/example.ipynb) did not resolve the Issue either. (I thought it might be a potential conflict.)

<br/>

> What I need to see is your call to mpf.plot() plus any code leading up to it that would have been involved in setting its parameters. Alternatively, printing out the value of all parameters just prior to the mpf.plot() call would be adequate.

Requested data from my Windows 10 Example Notebook:
These are the parameters prior to ```mpf.plot()``` in the Chart Class of the Example Notebook. [chart_class_inputs.txt](https://github.com/matplotlib/mplfinance/files/6949459/chart_class_inputs.txt)
This is the data downloaded using _yfinance_ in the 7th cell of the Example Notebook [SPY_D_yfinance.csv](https://github.com/matplotlib/mplfinance/files/6949460/SPY_D_yfinance.csv)

I hope the data provided can give us additional insight into this Issue. Please let me know if I am missing anything or need to include additional data.

<br/>

Thanks again for your time and patience on this Issue @DanielGoldfarb. I appreciate the work you have put into making _mplfinance_ and awesome Charting package.

Kind Regards,
KJ

**Comment by saif-ellafi** [comment]
Is there a chance to keep this issue open? I would be also investigating this.

**Comment by DanielGoldfarb** [comment]
@saif-ellafi  Saif, sure.  I meant to reopen this after Kevin ( @twopirllc ) commented and gave us some stuff to go on.

I am very busy presently and probably won't have any time to look at this for the next few weeks.   Anyone else who wants to look into this please do.  Much appreciated!

**Comment by DanielGoldfarb** [comment]
#### I finally got around to trying this on my windows machine, and am able to reproduce in a simple call to Python's datetime module:
```bash
In [1]: from datetime import datetime

In [2]: datetime.now().strftime("%m/%d/%Y")
Out[2]: '12/16/2021'

In [3]: datetime.now().strftime("%-m/%-d/%Y")
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-3-24560f124cad> in <module>
----> 1 datetime.now().strftime("%-m/%-d/%Y")

ValueError: Invalid format string
```

---

#### Ultimately I found [**a good answer here**](https://stackoverflow.com/a/41191435/1639359).  To partially quote:

#### **`%-*`** to skip padding is a GNU libc extension. It's **not part of POSIX strftime**, and **thus not guaranteed to be portable** to systems where your time-formatting calls aren't eventually backed by GNU's `strftime` C library function.

---

Therefore, Kevin, it seems if you want pandas-ta to be fully portable (POSIX compliant) you may want to change the format to:
```python
 datetime_format="%m/%d/%Y",
```

All the best.   --Daniel

**Comment by DanielGoldfarb** [comment]
I suppose if you want to use that format whenever you can, then *before* calling `mpf.plot()` you can test it with python's datetime module:

```python
fmt="%-m/%-d/%Y"
try:
    datetime.now().strftime(fmt)
except:
    fmt="%m/%d/%Y"
...
...
mpf.plot(...,datetime_format=fmt,...)
```

**Comment by twopirllc** [comment]
Hi @DanielGoldfarb,

Awesome! Thanks for your time and expertise in helping to resolve this issue.

Thanks,
KJ
