### ISSUE TITLE
Bug Report:  tlines() error 

### ISSUE THREAD

**Issue by TheGrowingPlant443** [matplotlib/mplfinance#424]
I may have done something wrong but I think this is a bug. 

I have data from yahoofinance of the ticker symbol AMC from (2021-07-22 09:30:00-04:00 to 2021-07-28 15:59:00-04:00). I want to use the function tlines() but I get an error. 

Code: 
```
import yfinance as yf
import pandas as pd
import mplfinance as mpf

tickername = "AMC"

Ticker = yf.Ticker(tickername)

df = Ticker.history(period='1d', interval='1m', start='2021-07-22', end='2021-07-28')

datapairs = [('2021-07-22 09:38:00-04:00', '2021-07-22 09:58:00-04:00'), ('2021-07-22 09:58:00-04:00', '2021-07-22 10:02:00-04:00'), ('2021-07-22 10:02:00-04:00', '2021-07-22 10:15:00-04:00'), ('2021-07-22 10:15:00-04:00', '2021-07-22 10:24:00-04:00'), ('2021-07-22 10:24:00-04:00', '2021-07-22 10:33:00-04:00'), ('2021-07-22 10:33:00-04:00', '2021-07-22 10:36:00-04:00'), ('2021-07-22 10:36:00-04:00', '2021-07-22 11:22:00-04:00')]

mpf.plot(df, tlines=[dict(tlines=datapairs,tline_use='high',colors='g')])
```

Error Message:
`` 
ValueError: User specified line date "2021-07-22 09:38:00+00:00" is before (less than) range of plotted data (2021-07-22 09:30:00-04:00 to 2021-07-28 15:59:00-04:00).
``
But "2021-07-22 09:38:00+00:00" is not before "2021-07-22 09:30:00" so I don't get why I get this error. 

If I change all the dates to "2021-07-23" it does not crash and it gives me a plot but there is no trendline on it to be seen only one vertical line in the middel of nowhere.  

Code for dates with "2021-07-23".
``
datapairs = [('2021-07-23 09:38:00', '2021-07-23 09:58:00'), ('2021-07-23 09:58:00', '2021-07-23 10:02:00'), ('2021-07-23 10:02:00', '2021-07-23 10:15:00'), ('2021-07-23 10:15:00', '2021-07-23 10:24:00'), ('2021-07-23 10:24:00', '2021-07-23 10:33:00'), ('2021-07-23 10:33:00', '2021-07-23 10:36:00'), ('2021-07-23 10:36:00', '2021-07-23 11:22:00')]
``

![2021-07-22 09 38 00-2021-07-22 09 58 00](https://user-images.githubusercontent.com/57142309/127475827-b6d350e5-a5bc-4fc6-8e55-5584469b4b48.png)

**Comment by DanielGoldfarb** [comment]
@TheGrowingPlant443 
Were you able to get it to work?
