### ISSUE TITLE
multiple dicts for fill_between in same plot

### ISSUE THREAD

**Issue by davidm2k** [matplotlib/mplfinance#426]
I have two dicts that I want to supply to fill_between inside the mpf.plot function call.  Is this possible? Reason being - I want to fill an area above and below the same group of candles, but not fill the candles themselves. Can this be done? Many thanks!

**Comment by DanielGoldfarb** [comment]
Please read the following:
- https://github.com/matplotlib/mplfinance/issues/291#issuecomment-726957293
- https://github.com/matplotlib/mplfinance/issues/260

Enhancement is in progress, hoping to have it complete in another month or two.

**Comment by DanielGoldfarb** [comment]
When you say
> above and below the same group of candles, but not fill the candles themselves.

Can you give an *example* (even a manually edited picture) of what you want the plot to look like?

**Comment by davidm2k** [comment]
Hi Daniel, sorry I should have attached a picture earlier.  Here is what I mean:

![candle channel](https://user-images.githubusercontent.com/5743666/127726718-ef3f46e6-5271-45d1-8a6f-d90b9a0b126c.jpg)

Like could I fill the "red" and "blue" areas?  The idea is to fill areas inside a channel, the blank space above and below the candles.  The green lines are already calculated so I know the y values (price) of the green lines at any candle. 

So something like this:

fill_between=dict(y1=greenline1values,y2=candlehighvalues,where=(june20 to july22),alpha=0.5,color='RED')
fill_between=dict(y1=greenline2values,y2=candlelowvalues, where=(july5 to aug6), alpha=0.5,color='BLUE')

I want to fill_between twice to the same plot like this, is it doable?

Thanks in advance,
David

**Comment by davidm2k** [comment]
Hi Daniel,

Actually I just went into the plotting.py and copied the fill_between and made a fill_between2 under the functions _valid_plot_kwargs() and plot(), eg:

for _valid_plot_kwargs() I did
        'fill_between'              : { 'Default'     : None,
                                        'Validator'   : lambda value: _num_or_seq_of_num(value) or 
                                                                     (isinstance(value,dict) and 'y1' in value and
                                                                       _num_or_seq_of_num(value['y1'])) },
        '**fill_between2**'             : { 'Default'     : None,
                                        'Validator'   : lambda value: _num_or_seq_of_num(value) or 
                                                                     (isinstance(value,dict) and 'y1' in value and
                                                                       _num_or_seq_of_num(value['y1'])) },

and then in plot() I did:

    # fill_between is NOT supported for external_axes_mode
    # (caller can easily call ax.fill_between() themselves).
    if config['fill_between'] is not None and not external_axes_mode:
        fb    = config['fill_between']
        panid = config['main_panel']
        if isinstance(fb,dict):
            if 'x' in fb:
                raise ValueError('fill_between dict may not contain `x`')
            if 'panel' in fb:
                panid = fb['panel']
                del fb['panel']
        else:
            fb = dict(y1=fb)
        fb['x'] = xdates
        ax = panels.at[panid,'axes'][0]
        ax.fill_between(**fb)

    if config['fill_between2'] is not None and not external_axes_mode:
        fb    = config['**fill_between2**']
        panid = config['main_panel']
        if isinstance(fb,dict):
            if 'x' in fb:
                raise ValueError('fill_between dict may not contain `x`')
            if 'panel' in fb:
                panid = fb['panel']
                del fb['panel']
        else:
            fb = dict(y1=fb)
        fb['x'] = xdates
        ax = panels.at[panid,'axes'][0]
        ax.fill_between(**fb)

This did the trick and it has met my needs!  I suppose you could write a validator for list of dicts or dicts of dicts and use that for the fill_between arg, but I am not familiar with the code, perhaps that is possible?

Thanks,
David
