### ISSUE TITLE
Panel

### ISSUE THREAD

**Issue by foolsden** [matplotlib/mplfinance#430]
Hi! First i want to say thank you for the hard work for creating a wonderful charting library!
I'm new to python and have been using mplfinance for about 2 months (and i also never use matploblib before this), some of my code are copy-paste-modified from some sources, so i hope you don't mind the messiness.

I have a few question about the panels:
1. Is there a way to add paddings between panels? I'm using 5 panels, i somehow managed to 'hack' with fill_between all the area to make it clearer. Also i tried setting y limit manually but this usually caused uneven space.

2. Or maybe perhaps creating a box around the panels only? so far i use style to draw bounding box, but the main panel is also styled (I like the cleanliness main panel of yahoo panel)

3. How can i draw hline, vlines etc in the panels? i tried putting in the mpf.make_addplot command it return 'Unrecognized kwarg="hline"'. I would like to make the y=0 lines stands out a little more

4. I try make a line at y=0 bolder by using this hack:
     mpf.make_addplot([0]*len(tempdb4), panel=5, width=3, linestyle='-', color='black')
    i noticed sometime the line is off (not on the y=0), is the code wrong?
![Screener](https://user-images.githubusercontent.com/88649171/128679079-314354fa-ed3b-4349-8cdd-dbd8ea144651.jpg)
please look at the line on the lowest panel, the line is not on the y=0

Help is much appreciated

My Code:
```python
import pandas as pd
import yfinance as yf
import numpy
import pandas_ta as ta
import mplfinance as mpf
import matplotlib

def set_col_chart(db):
    tempdb = db.copy()
    conditions = [
        tempdb.gt(0) & tempdb.ge(tempdb.shift()),
        tempdb.gt(0) & tempdb.lt(tempdb.shift()),
        tempdb.lt(0) & tempdb.le(tempdb.shift()),
        tempdb.lt(0) & tempdb.ge(tempdb.shift()),
        tempdb == 0
    ]

    choices = ['green','palegreen', 'red', 'lightcoral', 'black']

    return numpy.select(conditions, choices)

## Single stock viewer

ticker = 'MPMX'
length = 125

tempdb = yf.download(ticker + '.JK', start='2021-01-01')
tempdb1 = tempdb.copy()
tempdb1 = tempdb1.ta.supertrend(multiplier=1.0)
tempdb2 = tempdb.copy()
tempdb2 = tempdb2.ta.adx()
tempdb3 = tempdb.copy()
tempdb3 = tempdb3.ta.rsi()
tempdb4 = tempdb.copy()
tempdb4 = tempdb4.ta.squeeze()
tempdb5 = tempdb.copy()
tempdb5 = tempdb5.ta.macd()
tempdb6 = tempdb.copy()
tempdb6 = tempdb6.ta.bbands(length=20)

tempdb4['Colors'] = set_col_chart(tempdb4['SQZ_20_2.0_20_1.5'])
tempdb5['Colors'] = set_col_chart(tempdb5['MACDh_12_26_9'])

tempdb['MA10'] = tempdb['Close'].rolling(window=10).mean()
tempdb['MA50'] = tempdb['Close'].rolling(window=50).mean()
tempdb['MA200'] = tempdb['Close'].rolling(window=200).mean()
tempdb['Change'] = round(tempdb['Close'].pct_change() * 100, 2)
tempdb['Max5'] = tempdb['High'].rolling(window=5).max()
tempdb['Min5'] = tempdb['Low'].rolling(window=5).min()

tempdb = tempdb.tail(length)
tempdb1 = tempdb1.tail(length)
tempdb2 = tempdb2.tail(length)
tempdb3 = tempdb3.tail(length)
tempdb4 = tempdb4.tail(length)
tempdb5 = tempdb5.tail(length)
tempdb6 = tempdb6.tail(length)

tempdb['Split'] = tempdb.MA10.ge(tempdb.MA10.shift())
tempdb['TrendDown'] = tempdb['MA10'].loc[~tempdb['Split']]

apds = [mpf.make_addplot(tempdb['MA10'], color='green', linestyle='dotted'),
        mpf.make_addplot(tempdb['TrendDown'], color='red', linestyle='dotted'),
        mpf.make_addplot(tempdb['MA50'], color='purple', linestyle='dashdot', width=.75),
        mpf.make_addplot(tempdb['Max5'], width=.75, color='chocolate'),
        mpf.make_addplot(tempdb['Min5'], width=.75, color='chocolate'),
        mpf.make_addplot(tempdb6['BBL_20_2.0'], color='lightblue', width=.75),
        mpf.make_addplot(tempdb6['BBU_20_2.0'], color='lightblue', width=.75),
        mpf.make_addplot(tempdb['Volume'], color=['g' if v >= 0 else '#aa0000' for v in tempdb["Change"]],
                         type='bar', width=.3, alpha=.5, ylim=(int(0), int(tempdb['Volume'].max() * 5))),        
        mpf.make_addplot(tempdb['Change'], color=['g' if v >= 0 else 'r' for v in tempdb['Change']],
                         panel=1, width=.75, type='bar', ylim=(-6,25)),
        mpf.make_addplot(tempdb2['ADX_14'], panel=2, ylim=(int(0), int(100)), width=.5),
        mpf.make_addplot(tempdb3, panel=3, color='black', width=.75, ylim=(int(0), int(100))),
        mpf.make_addplot(tempdb4['SQZ_20_2.0_20_1.5'], color=tempdb4['Colors'].values,
                         panel=4, type='bar', ylim=(int(-50 if tempdb4['SQZ_20_2.0_20_1.5'].min() > -50 else tempdb4['SQZ_20_2.0_20_1.5'].min()),
                                                    int(50 if tempdb4['SQZ_20_2.0_20_1.5'].max() < 50 else tempdb4['SQZ_20_2.0_20_1.5'].max()))),
        mpf.make_addplot(tempdb5['MACD_12_26_9'], panel=5, color='black', width=.75),
        mpf.make_addplot([0]*len(tempdb5), panel=5, width=2, linestyle='-', color='black'),
        mpf.make_addplot(tempdb5['MACDs_12_26_9'], panel=5, color='red', width=.75),
        mpf.make_addplot(tempdb5['MACDh_12_26_9'], panel=5, color=tempdb5['Colors'].values,
                         type='bar', width=.75, alpha=.5)]

if not (tempdb['MA200'].dropna().empty):
        apds.append(mpf.make_addplot(tempdb['MA200'], color='blue', width=.75))

if not (tempdb1['SUPERTl_7_1.0'].dropna().empty):
        apds.append(mpf.make_addplot(tempdb1['SUPERTl_7_1.0'], color='green'))

if not (tempdb1['SUPERTs_7_1.0'].dropna().empty):
         apds.append(mpf.make_addplot(tempdb1['SUPERTs_7_1.0'], color='grey'))

s  = mpf.make_mpf_style(base_mpf_style='yahoo', edgecolor='#666666')

fig, ax = mpf.plot(tempdb, addplot=apds, type='candle', style=s, panel_ratios=(5, .5, .5, 1, .75, 1.25),
                   figsize=(14, 7), title=ticker, returnfig=True,
                   fill_between=dict(y1=tempdb6['BBL_20_2.0'].values, y2=tempdb6['BBU_20_2.0'].values, color='grey', alpha=0.20),
                   ylim=(tempdb['Close'].min() * .8, tempdb['Close'].max() * 1.05),
                   tight_layout=True)

ax[0].yaxis.label.set_visible(False)

ax[1].tick_params(left=False, right=False, labelleft=False, labelright=False)
ax[1].yaxis.set_major_formatter(matplotlib.ticker.FormatStrFormatter('%d'))

ax[2].set_ylabel('% CHG', fontsize=8)
ax[2].tick_params(labelleft=False, labelright=False)
ax[2].fill_between(range(length), y1=100, y2=-6, facecolor='peachpuff', alpha=0.5)

ax[4].set_ylabel('ADX', fontsize=8)
ax[4].tick_params(labelleft=False, labelright=False)
ax[4].set_yticks((0, 25, 50, 75, 100))

ax[6].set_ylabel('RSI', fontsize=8)
ax[6].set_yticks((0, 20, 80, 100))
ax[6].fill_between(range(length), 100, facecolor='peachpuff', alpha=0.5)
ax[6].fill_between(range(length), 80, 20, facecolor='lightgrey', alpha=0.5)
ax[6].tick_params(labelleft=False, labelright=False)

ax[8].tick_params(labelleft=False, labelright=False)
ax[8].set_ylabel('SQUEEZE', fontsize=8)

ax[11].tick_params(left=False, right=False, labelleft=False, labelright=False)
ax[10].tick_params(labelleft=False, labelright=False)
ax[10].tick_params(axis='x', labelsize=8)

ax[10].set_ylabel('MACD', fontsize=8)
for tick in ax[10].get_xticklabels():
    tick.set_rotation(0)

ax[10].xaxis.set_major_locator(matplotlib.ticker.MultipleLocator(10))
```

**Comment by chuckf201** [comment]
The easiest way to plot h-lines is to define a pandas column with a constant. For RSI (30 and 70) I use:
`df2['rsi_upper']=30
df2['rsi_lower']=70
`
I can also control line style such as color and line width.
Hope this help.

**Comment by DanielGoldfarb** [comment]
@foolsden 
First of all, sorry for taking so long to respond.  I've had quite a few distractions with other projects in the past several months.

Second, Thank you for posting all your code.  It took me less than a minute to be able to produce your chart on my machine.  Great job!  And beautiful chart!

Regarding your questions:
> 1. Is there a way to add paddings between panels? I'm using 5 panels, i somehow managed to 'hack' with fill_between all the area to make it clearer. Also i tried setting y limit manually but this usually caused uneven space.

- I will think about this some more, but what comes to mind initially is that you can put empty panels between panels where you want more space.   See **`In [13]`** and **`In [14]`** in [**the panels tutorial**](https://github.com/matplotlib/mplfinance/blob/master/examples/panels.ipynb)

---

> 2. Or maybe perhaps creating a box around the panels only? so far i use style to draw bounding box, but the main panel is also styled (I like the cleanliness main panel of yahoo panel)

- I tried the following with your code and it seems to have helped.  
  In the call to `mpf.make_mpf_style()` add kwarg `rc={'axes.linewidth':3.0}` ...

  ```python
  s  = mpf.make_mpf_style(base_mpf_style='yahoo', edgecolor='#666666',rc={'axes.linewidth':3.0})
  ```
- You can also add `axes.edgecolor` to the `rc=` dict if you want.

---

> 3. How can i draw hline, vlines etc in the panels? i tried putting in the mpf.make_addplot command it return 'Unrecognized kwarg="hline"'. I would like to make the y=0 lines stands out a little more

- Unfortunately the various `lines` kwargs are not yet available to `mpf.make_addplot()`.  If you would like to contribute the code change to support this it will be welcomed.  What you are doing below should work.

---

> 4. I try make a line at y=0 bolder by using this hack:
     mpf.make_addplot([0]*len(tempdb4), panel=5, width=3, linestyle='-', color='black')
    i noticed sometime the line is off (not on the y=0), is the code wrong?

- In theory this should work.  It is possible that sometimes `make_addplot()` is automatically deciding that y=0 is of a different order of magnitude than your data, and therefore decides to put it on a secondary y-axis (which would then have possibly a different zero location).  Try adding kwarg `secondary_y=False` to force it onto the same y-axis as your other data for that panel.

---

Please let me know if any of these suggestions help.   Again appologies for the long delay in responding.  And kudos for the amazing chart!  Thanks.  All the best.  --Daniel
