### ISSUE TITLE
Matplotlib / Mplfinance - how to change colour of lines and bars

### ISSUE THREAD

**Issue by cwfmoore** [matplotlib/mplfinance#431]
Been using Mplfinance and its great. I have been struggled with changing the colours of some of the subplots.

I successfully used the 'mpf.make_addplot' method from the [docs ](https://github.com/matplotlib/mplfinance/blob/master/examples/external_axes.ipynb )using the external axes method. And I have read the [docs ](https://github.com/matplotlib/mplfinance/blob/master/examples/styles.ipynb) regarding styles. But how do you apply a style to one of the sublots and not just the plot as a whole?

I have added my code and an image of the chart that it produces, the function is passed props with tha chart data.

I have labelled the image 'A' where there is a line I would like to change the colour of, this is the df['counts'] add plot, labelled 'Tweets'. Also the part labelled 'B', i would like to change the colour of the bar and if possible make it a different colour depending on it being positive or negative.

[image](https://imgur.com/WoB3Obv)

`
          def makeCharts_CountsOHLC(self, props):

        fig = props['fig']
        df = props['df']
        symbol = props['symbol']
        start = props['min_date']
        end = props['max_date']

        # Configure the axes
        ax1 = fig.add_subplot(5,1,(1,2))
        ax2 = fig.add_subplot(5,1,3, sharex=ax1)
        ax3 = fig.add_subplot(5,1,4, sharex=ax1)
        ax4 = fig.add_subplot(5,1,5, sharex=ax1)

        aps = [
            mpf.make_addplot(
            df['count_s'], 
            ax=ax2, 
            ylabel='Tweets',
            ),
            
            mpf.make_addplot(
            df['sentiment'], 
            type='bar',
            ax=ax3,
            ylabel='Sentiment',            
            )]
        
        ax1.tick_params(labelbottom=False)
        ax2.tick_params(labelbottom=False)
        ax3.tick_params(labelbottom=False)

        # Functions to add a day to date and format dates 
        date_p1 = lambda x: dt.strftime(pd.to_datetime(x) + td(days=1), '%d %b %y')
        fmt_date = lambda x: dt.strftime(pd.to_datetime(x), '%d %b %y')

        title = f'{symbol} Price and Volume Traded from {fmt_date(start)} until {date_p1(end)}'

        # Plot the chart
        mpf.plot(
            df,
            type='candle',
            ax = ax1,
            volume = ax4,
            addplot = aps,
            xrotation = 0,
            datetime_format = '%b %d',
            axtitle = title,
            ylabel = 'Price ($USD)',
            tight_layout = True
            )

        # Format the prive of the y axis 
        mkfunc = lambda x, pos: '%1.1fM' % (x * 1e-6) if x >= 1e6 else '%1.1fK' % (x * 1e-3) if x >= 1e3 else '%1.1f' % x
        mkformatter = matplotlib.ticker.FuncFormatter(mkfunc)
        ax1.yaxis.set_major_formatter(mkformatter)

        # Adjustments to plot and save
        plt.subplots_adjust(hspace=0)
        plt.savefig(fname=props['save_path'], dpi=self.cconf.get('RESOLUTION'))
        plt.close('all')
        fig.clear()`

**Comment by foolsden** [comment]
I think you can put a color parameter on the mpf.make_addplot function e.g.:
```python
    mpf.make_addplot(
        df['count_s'], 
        ax=ax2, 
        ylabel='Tweets',
        color ='green' #Use hex or name color on https://matplotlib.org/stable/gallery/color/named_colors.html
        )
```

To make it change on single condition or multiple simple condition you can use list generators e.g.:
```python
    colors = ['g' if val >= 0 else 'r' for val in df["Change"]]
```

For a little complex condition e.g.:
![color](https://user-images.githubusercontent.com/88649171/128793603-a2763bd1-8e9a-40df-a200-a5d0a00a8266.jpg)
try to define it first in the one of the dataframe's column (recommended) or just use a list e.g.:
```python
    colors = df['Colors'].value # or colors = list_colors
```

**Comment by DanielGoldfarb** [comment]
@foolsden   Thank you for contributing the answer.

**Comment by furkanbr** [comment]
@foolsden Looks like this solution only working with bars. Im trying to make color changing on MA but it gives me error, is there any solution for this? 

`    ap = mplfinance.make_addplot(df["EMA"], ylabel="EMA", color=df["emaColor"])`

I added a column for color codes but not working.

**Comment by DanielGoldfarb** [comment]
@furkanbr just to be clear on what you are trying to do ... you want a *single EMA line that is different colors at different parts of the line* (something like this https://matplotlib.org/stable/gallery/lines_bars_and_markers/multicolored_line.html )  Is that correct??

**Comment by furkanbr** [comment]
@DanielGoldfarb Yes correct, i want to show uptrend, downtrend on ema linee with two different color. But didnt work when i try to run with color codes on dataframe.
