### ISSUE TITLE
Bug Report: Issues with EMAs

### ISSUE THREAD

**Issue by mmoheeka** [matplotlib/mplfinance#435]
**Describe the bug**
all the other emas work well but as soon as I use the 200ema, its very incorrect. Not sure what is happening. Pasted my code and examples of mine and TOS charts below 200ema is the dark brown line above vwap in my mlpchart and in TOS is the dark brown line lowest to all the others.

``` python
vwap = (intradayDF['volume'] * (intradayDF['high'] + intradayDF['low']) / 2).cumsum() / intradayDF['volume'].cumsum()

exp200 = intradayDF['close'].ewm(span=200, adjust=False).mean()
exp50 = intradayDF['close'].ewm(span=50, adjust=False).mean()
exp20 = intradayDF['close'].ewm(span=20, adjust=False).mean()
exp9 = intradayDF['close'].ewm(span=9, adjust=False).mean()


addplot = [mpf.make_addplot(exp200, color='#8D641D'),
    mpf.make_addplot(exp50, color='#ffff00'),
    mpf.make_addplot(exp20, color='#009999'),
    mpf.make_addplot(exp9, color='#33ffff'),
    mpf.make_addplot(vwap, color='#b266ff')]

dates = pd.Series([d.date() for d in intradayDF.index]).unique()

octimes = []
colors = []
for d in dates:
    dt = pd.Timestamp(d)
    octimes.append(dt.replace(hour=9, minute=30))
    octimes.append(dt.replace(hour=16, minute=0))
    colors.append('#959595')
    colors.append('#959595')

mc = mpf.make_marketcolors(up='#00ff00', down='#ff0000', inherit=True)

s = mpf.make_mpf_style(base_mpf_style='mike', marketcolors=mc, gridcolor='#555555', gridstyle="--",
    rc={'axes.edgecolor': 'white', 'axes.linewidth': 1, 'font.size': 8, 'lines.linewidth': 1})

mydpi = 100
fname = "sample_2.png"

fig1, _ = mpf.plot(intradayDF, type='candle', volume=True, title=ticker+" "+timeFrame, addplot=addplot, style=s, vlines=dict(vlines=octimes, colors=colors, linewidths=(.2), alpha=0.4,),
        figsize=(4000/mydpi, 1800/mydpi), returnfig=True, scale_padding=1)

# fig1.savefig(fname, dpi=mydpi)
fig1.savefig(fname) 
```

![sample_2](https://user-images.githubusercontent.com/43290346/129788697-e0c16078-12f6-4455-b83e-abb873ba514f.png)
![Screenshot 2021-08-17 123123](https://user-images.githubusercontent.com/43290346/129788786-8d3a2207-af12-465f-a109-6bd0001ba6c5.png)

**Comment by DanielGoldfarb** [comment]
Please provide you `intradayDF` dataframe as a csv file somewhere that we can access it.  To look into this we will need everything necessary to be able to reproduce.  

Also, please clarify **"it's very incorrect."**   What do you see on the chart that you don't want to see, and/or what don't you see that you *do* want to see?  

Please show the output from your code without the 200EMA, and with the 200EMA and indicate what is different to make you think that something is wrong with mplfinance, and what specifically you see mplfinance doing or not doing that you think is wrong.

**Comment by DanielGoldfarb** [comment]
closed due to lack of information and inactivity.
