### ISSUE TITLE
UserWarning

### ISSUE THREAD

**Issue by youyj-tech** [matplotlib/mplfinance#438]
/Applications/PyCharm.app/Contents/plugins/python/helpers/pycharm_matplotlib_backend/backend_interagg.py:68: UserWarning: This figure includes Axes that are not compatible with tight_layout, so results might be incorrect.
  self.figure.tight_layout()

**Comment by DanielGoldfarb** [comment]
[**This code**](https://github.com/matplotlib/mplfinance/issues/438#issuecomment-906857718) runs fine for me when run as a script, both under linux and under windows power shell.  I can only think that PyCharm must be doing something with the Figure and Axes objects.  I am not familiar with PyCharm, so I don't think there is anything more I can do to help.
