### ISSUE TITLE
Coinex style

### ISSUE THREAD

**Issue by mablue** [matplotlib/mplfinance#449]
Hi I love much coinex style cuz of ... Eeemmm I dont know i tested all other styles but this dark mode of coinex have very beautiful colors and I need to have it without other configuration on mplfinace. Can you please add it on your styles?!:)
Also if you can make it with  some styling statments please share it with me thanks.
![Screenshot_2021-09-24-10-23-42-309_com coinex trade play](https://user-images.githubusercontent.com/5004900/134631673-215a17e1-292d-4b46-94bc-17b35f985f54.jpg)

**Comment by DanielGoldfarb** [comment]
@mablue Masoud,

You can do this yourself.  Suggested steps:
1. Read thoroughly and carefully the [**"styles" tutorial**](https://github.com/matplotlib/mplfinance/blob/master/examples/styles.ipynb), *especially the bottom half*, to learn how to make your own custom styles.  You can even clone the repository and play with the code in that tutorial to gain experience.
2. Look at [**`_styledata` files**](https://github.com/matplotlib/mplfinance/tree/master/src/mplfinance/_styledata) in the repository, just to get an idea of what they look like.
3. Use the bottom half of the [**"styles" tutorial**](https://github.com/matplotlib/mplfinance/blob/master/examples/styles.ipynb) as a guide to create your own **coinex** style.  
Note: you can save the above [**coinex image**](https://user-images.githubusercontent.com/5004900/134631673-215a17e1-292d-4b46-94bc-17b35f985f54.jpg) to a file, and then upload a file to a web site like https://html-color-codes.info/colors-from-image/# to determine the exact hex color codes for the coinex colors.  For example, when I do this I see that the green candles are  #17B49F and the red candles are #D14B64, the background is #141F31 and the moving averages are #FBC622, and #1FB09F, and #6D6BBF.
4. After your write the code to create your own style (using `mpf.make_marketcolors()` and `mpf.make_mpf_style()` ) then you can call **`mpf.write_style_file( customstyle, 'coinex.py')`** (where `customstyle` is the variable containing the return value from calling `mpf.make_mpf_style()`).  This will generate file coinex.py which you will place in the styledata directory (see steps below).
5. [Fork and clone the mplfinance directory](https://guides.github.com/activities/forking/)
6. In your cloned repository add coinex.py to [the _styledata directory](https://github.com/matplotlib/mplfinance/tree/master/src/mplfinance/_styledata)
7. Edit https://github.com/matplotlib/mplfinance/tree/master/src/mplfinance/_styledata/__init__py and add the line:
    ```python
    from mplfinance._styledata import coinex
    ```
8. Test that you can now call `mpf.plot(data,...,style='coinex')`.
9. If working, push to your fork.
10. Create a Pull Request on github to add coinex style to mplfinance.
11. Wait for me to accept the pull request (sometimes takes a couple weeks if I am busy).

Thank you for contributing to mplfinance.  If you have an questions with the above, let me know.  All the best.  --Daniel

**Comment by mablue** [comment]
Wow thanks 🙏:)
I will work on it
