### ISSUE TITLE
Where can I find help documentation of mplfinance parameters?

### ISSUE THREAD

**Issue by sunjar2020** [matplotlib/mplfinance#450]
Hi, I saw other people mentioning "mpf.plot(df, type='pnf', pnf_params=dict(box_size=7))" parameters in other issue, but I did not find any documents containing these parameters on the mplfinance webpage(including github and pypi.org). Where did these parameters come from? Are there any more optional parameters can use of mplfinance? 

Thank you !

**Comment by DanielGoldfarb** [comment]
Almost all (about 98%) of the documentation on mplfinance [**can be found in the table of contents here**](https://github.com/matplotlib/mplfinance#contents-and-tutorials) **and in the links therein**.  

The section you are looking for, in the above mentioned table of contents, is **[Price-Movement Plots (Renko, P&F, etc)](https://github.com/matplotlib/mplfinance/blob/master/examples/price-movement_plots.ipynb)** where you will see the various optional renko and pnf arguments explained, as well as examples in the tutorial.

Beyond that [**there are a few wiki pages here**](https://github.com/matplotlib/mplfinance/wiki) containing some additional documentation, which I will soon add to the above mentioned table of contents.

There are a few (**very few**) undocumented kwargs in mplfinance, which you can see by looking in the code [**here**](https://github.com/matplotlib/mplfinance/blob/master/src/mplfinance/plotting.py#L86-L277) and [**here**](https://github.com/matplotlib/mplfinance/blob/master/src/mplfinance/plotting.py#L1023-L1092).  (The vast majority of kwargs however ***are*** documented in the above mentioned documentation).  There is [an enhancement in the works](https://github.com/matplotlib/mplfinance/pull/416) which will soon make it possible to access information on all possible kwargs by simply calling a function in the mplfinance library.  Hoping to have that enhancement released before the end of this year.

All the best.  --Daniel
