### ISSUE TITLE
How to make and save multiple timeframes in a file

### ISSUE THREAD

**Issue by mablue** [matplotlib/mplfinance#455]
I have a data provider named "ccxt"
And can get all timeframes with a for loop:
```
def plot(m):
  tflist=exchange.timeframes
  df = pd.DataFrame()
  plots = []
  
  for tf in tflist:
    indicator = exchange.fetch_ohlcv(symbol=m, timeframe=tf, limit=250)
    start_dt = datetime.fromtimestamp(indicator[0][0]/1000)
    end_dt = datetime.fromtimestamp(indicator[-1][0]/1000)
  
    
    # convert it into Pandas DataFrame
    df = pd.DataFrame(indicator, columns = ['time', 'open', 'high', 'low', 'close', 'volume'])
    df['time'] = [datetime.fromtimestamp(float(time)/1000) for time in df['time']]
    #df['date']=df['time']
    df.set_index('time', inplace=True)
    

```
How can I add them into the mpl as seperated tiles of candlestick charts and than save all as a file after ending for loop?!
I seen bunch of issues and examples but cant do it.
I need make and than save something like that as file:
<img width="1053" alt="128610159-5f2a7cce-b41c-45bb-acad-c703524e3fd4" src="https://user-images.githubusercontent.com/5004900/137851108-8ae61fb9-880f-4cc6-9d26-ed7bc2be6bf4.png">

**Comment by mablue** [comment]
![SUSHIUSDT1d](https://user-images.githubusercontent.com/5004900/138165134-990d6e0e-f031-45b7-8d2a-9037674b7f97.png)
![WAXPBTC1d](https://user-images.githubusercontent.com/5004900/138165143-e6dbfcea-841a-468a-8ec7-944f5b2f45d6.png)
![ETCBTC1d](https://user-images.githubusercontent.com/5004900/138165146-f81aad26-9272-494b-97ed-a884e7746f8a.png)
![PBXUSDT1d](https://user-images.githubusercontent.com/5004900/138165147-550f5ad5-d08f-4800-976a-7cbab58f1c59.png)
[csv.zip](https://github.com/matplotlib/mplfinance/files/7384055/csv.zip)

**Comment by DanielGoldfarb** [comment]
Thanks.  I will play with the data and see what I can come up with in terms of making the plots look correct.

**Comment by mablue** [comment]
You are one of fuking lovely peopleI known befour.
Thanks for your responses amd support I will be happy to know you more.
I use mpl as a full exchange filter on my phone as a folder that contains new charts with date of create sort to get the mostly good coins to trade.
But I have one big idea too.
Making photo of everything. To show it to some Svml algo to classify the probability of trend direction (barish, bullish, range).
You know My mind generates 3 or two ideas every day butwhen i think to that how I can do them in 24hour? lazyness attacks me.

**Comment by mablue** [comment]
![MSWAPUSDT2h](https://user-images.githubusercontent.com/5004900/146295173-ea56e7ef-352f-4682-86b7-bdc94587fbec.png)
![GHSTUSDT2h](https://user-images.githubusercontent.com/5004900/146295174-aa4e5679-f65f-4b69-b045-6ae3a7e0cf39.png)
![VLXUSDT2h](https://user-images.githubusercontent.com/5004900/146295177-d3da1514-660c-4b99-89ca-04dada69428b.png)
