### ISSUE TITLE
Add option for plot function to return figure and not display the figure itself.

### ISSUE THREAD

**Issue by MikeAMCloud** [matplotlib/mplfinance#46]
I desire to use mplfinance with tkinter.

To do this most straight forwardly I desire an option to return the figure.

So adding an option returnfig, using code something like the below:

Adding to vkwargs:

        'returnfig': {'Default': False,'Validator': lambda value: isinstance(value, bool)},

And extending the "savefig" code something like the below:
Code something like the below:

    if config['savefig'] is not None:
        save = config['savefig']
        if isinstance(save,dict):
            plt.savefig(**save)
        else:
            plt.savefig(save)
    else:
        if config['returnfig'] is not None:
            save = config['returnfig']
            if save:
                return (fig)            
        # https://stackoverflow.com/a/13361748/1639359 suggests plt.show(block=False)
        plt.show(block=config['block'])

**Comment by DanielGoldfarb** [comment]
Your code above looks fine;  I think you can simplify the `else` block as:

    else:
        if config['returnfig']:
            return (fig)            
        # https://stackoverflow.com/a/13361748/1639359 suggests plt.show(block=False)
        plt.show(block=config['block'])

(the validator is already ensuring that `config['returnfig']` is a `bool`, so there is no worry it's `None`).  

I have never used **tkinter** so I don't know enough to say if returning the Figure will accomplish what you want it to.   I suggest, if you feel comfortable, you can make the above change in your own fork, and then test it with your tkiniter code and let me know how it works out.  If it accomplishes what you want it to accomplish with tkiniter, then I will consider merging it in.

**Comment by MikeAMCloud** [comment]
Yes the above code does work.

An example with tkinter follows:

[DrawPlot.docx](https://github.com/matplotlib/mplfinance/files/4303287/DrawPlot.docx)

**Comment by DanielGoldfarb** [comment]
OK.   There are enough people asking for this.  I will include it in the next release.  (Maybe a week; maybe two weeks).   Thanks for getting back to me.

**Comment by MikeAMCloud** [comment]
Thanks for the quick responses.

Although I have not tried this, it seems that if one desired to add additional subplots, one could return the figure from mplfinance and then add as many subplots as one wanted using figure.add_subplot

**Comment by DanielGoldfarb** [comment]
> Thanks for the quick responses.
> 
> Although I have not tried this, it seems that if one desired to add additional subplots, one could return the figure from mplfinance and then add as many subplots as one wanted using figure.add_subplot

I don't think that will work, because by default the subplots that `mpf.plot()` creates (main panel and lower [volume] panel) take up the entire Figure (except to leave _some_ room for the axis labels). 

However, I am now 95% certain that I will implement [something like what I outlined here](https://github.com/matplotlib/mplfinance/issues/17#issuecomment-591712493) which should allow users to create as many subplots as desire in whatever configuration they desire.  (The only uncertainty is not knowing what, if any, issues I may encounter while testing it; but my preliminary experiments seem to indicate that it will work OK).

**Comment by DanielGoldfarb** [comment]
[wip](https://github.com/DanielGoldfarb/mplfinance/commit/70816415ee57d18a9d8d29be738cfbf2e53fa9af)
