### ISSUE TITLE
How to overlay a circle (plus text) at a point on a dataframe plot?

### ISSUE THREAD

**Issue by p-i-** [matplotlib/mplfinance#460]
I am plotting several price charts.

I want to overlay a 🟢  over the priceline on a chart at a certain date.

Here's my first attempt:

```
from matplotlib import pyplot as plt

import arrow

N = len(df_coins)
fig, axes = plt.subplots(N, figsize=(10, 5*N), sharex=True)

for (coin, df), ax in zip(df_coins.items(), axes):
    mpf.plot(df, ax=ax, axtitle=coin, type='line',  show_nontrading=True)  # volume=True,

axes[0].plot_date(arrow.get('2021-10-20T00:00:00Z'), 'og', fillstyle='full', ms=10.0)
```

![Screenshot 2021-10-31 at 13 08 32](https://user-images.githubusercontent.com/693495/139570436-fa2e826c-29ea-4c7d-8cc6-bc9482a1578e.png)

The circle is not green, and also it is sitting on the x-axis.

How to fix the color and position it to the price value for that particular date?

Do I need to manually extract the price from the dataframe for the date of interest (and the date might be between two date-values in the dataframe) and use a different matplotlib API call to plot the circle at a particular x,y?

I tried `axes[0].plot((arrow.get('2021-10-20T00:00:00Z'), 4), 'og', fillstyle='full', ms=10.0)` but got "TypeError: float() argument must be a string or a real number, not 'Arrow'" so maybe I can't use a datetime object here, in which case do I need to convert to Unix timestamp?

**Comment by DanielGoldfarb** [comment]
I recommend using `mpf.make_addplot(data,type='scatter').  It can be done along the lines of what you are doing (and probably better to do it *without* `arrow`) but I think it will be simpler with `make_addplot()`.   

Take a look at the [**addplot tutorial here**](https://github.com/matplotlib/mplfinance/blob/master/examples/addplot.ipynb) particularly at and around **`In [10]`**.   

The data passed into `make_addplot()` (list, array, or series) *must be the same length as your dataframe*.   

What I recommend is creating new a column in your dataframe for the circles.  Initialize it with all `float('nan')` values.   Then using the dataframe's datatime index and `.loc[]` on the dataframe, you can place at specific datetime locations any value you want (specifically it sounds like you want to just copy the price at that datetime over into the "circle" column.  Then you can pass this circle column into the call to `make_addplot()`

For example, something like this:
```python
df['circle'] = [float('nan')]*len(df)
df.loc['2021-10-20']['circle'] = df.loc['2021-10-20']['Close']
ap = mpf.make_addplot(df['circle'],type=scatter,marker='o',markersize=200,color='g')
mpf.plot(df,...,addplot=ap)
```

**Comment by DanielGoldfarb** [comment]
`make_addplot()` now ***does*** support passing `edgecolors=` kwarg.  
(See https://github.com/matplotlib/mplfinance/releases/tag/v0.12.8b6)

Let me know if you have further questions.

**Comment by fxhuhn** [comment]
![ice_aapl_us](https://user-images.githubusercontent.com/49436733/146639819-79f98ab4-1ce6-4f6a-9d39-16f25cdfed17.png)
something similar like this?
