### ISSUE TITLE
Is there a way to close the mpf and display new data after pause for another ticker

### ISSUE THREAD

**Issue by ram-gudapati** [matplotlib/mplfinance#463]
I want to check multiple tickers, say SPY and QQQ after pause say 10 secs, without user interaction. I would like create fig reading the new data each time.
Is there any functionality like that. I tried block and closefig. But not working as expected
Any help is appreciated.

**Comment by DanielGoldfarb** [comment]
Have you looked at the animation examples?
- [**Animation Support in mplfinance**](https://github.com/matplotlib/mplfinance/blob/master/markdown/animation.md)

- **Examples:**
  - [**`python mpf_animation_demo1.py`**](https://github.com/matplotlib/mplfinance/blob/master/examples/mpf_animation_demo1.py)
   - [**`python mpf_animation_demo2.py`**](https://github.com/matplotlib/mplfinance/blob/master/examples/mpf_animation_demo2.py)
   - [**`python mpf_animation_macd.py`**](https://github.com/matplotlib/mplfinance/blob/master/examples/mpf_animation_macd.py)
   - [**`mpf_animation_growingcandle.py`**](https://github.com/matplotlib/mplfinance/blob/master/examples/mpf_animation_growingcandle.py)

**Comment by DanielGoldfarb** [comment]
no response.  it's easy enough to close and plot something new every 10 seconds if that is what you want.  re-open or post if you still have questions.
