### ISSUE TITLE
Control the bar color

### ISSUE THREAD

**Issue by poeticlinuxer** [matplotlib/mplfinance#470]
In China，if the stock 's **Open Price** =**High Price** =**Low Price** =**Close Price**  ，How can I control the bar color ?
I want to draw red when the percentage change in the **Close Price** is positive .
I want to draw green when the percentage change in the **Close Price** is negative .
How can I  do ?

**Comment by poeticlinuxer** [comment]
[https://github.com/matplotlib/mplfinance/blob/master/src/mplfinance/_styles.py](url)

**Comment by poeticlinuxer** [comment]
[API PATH](https://github.com/matplotlib/mplfinance/blob/master/src/mplfinance/_styles.py)

**Comment by poeticlinuxer** [comment]
[matplotlib/mplfinance/blob/master/src/mplfinance/_styles.py](https://github.com/matplotlib/mplfinance/blob/master/src/mplfinance/_styles.py)

**Comment by DanielGoldfarb** [comment]
There is an [enhancement in progress](https://github.com/matplotlib/mplfinance/pull/451) to be able to set the color of individual candles.  However due to other work also in progress it may be another month or two before that enhancement is complete and released to production.

In the meantime, there is a work-around posted here: https://github.com/matplotlib/mplfinance/issues/378#issuecomment-821918248

Let me know if that helps.

**Comment by poeticlinuxer** [comment]
import mplfinance as mpf
import pandas as pd


def draw_line():
    print("draw_line")
    path = r"C:\Users\IMO_0117\PycharmProjects\DoubleW\release\output\SP500_NOV2019_Hist.csv"
    df = pd.read_csv(path,
                     index_col=0,
                     parse_dates=True)
    print(df)
    # Customize market colors, and place inside style you intend to use:
    mc = mpf.make_marketcolors(up='yellow',
                               down='yellow')
    s = mpf.make_mpf_style(base_mpf_style='yahoo',
                           marketcolors=mc)

    # Create an all `nan` values dataframe, same size, and same index as the first:
    nans = [float('nan')] * len(df)
    cdf = pd.DataFrame(dict(Open=nans,
                            High=nans,
                            Low=nans,
                            Close=nans),
                       index=df.index)
    print(cdf)
    # Copy in the specific candles that you want to color:
    cdf.loc['2019-11-08'] = df.loc['2019-11-08']
    cdf.loc['2019-11-15'] = df.loc['2019-11-15']
    cdf.loc['2019-11-19'] = df.loc['2019-11-19']

    # cdf.loc['2019-11-08'] = df.loc['2019-11-08'].copy()
    # cdf.loc['2019-11-15'] = df.loc['2019-11-15'].copy()
    # cdf.loc['2019-11-19'] = df.loc['2019-11-19'].copy()
    # df.loc['2019-11-08'] = nans[0]
    # df.loc['2019-11-15'] = nans[0]
    # df.loc['2019-11-19'] = nans[0]

    # Call `mpf.plot()` twice with the two dataframes and two styles:
    fig, axlist = mpf.plot(df, type='candle', style='yahoo', returnfig=True)
    mpf.plot(cdf, type='candle', style=s, ax=axlist[0])


if __name__ == '__main__':
    draw_line()

**Comment by poeticlinuxer** [comment]
`import mplfinance as mpf
import pandas as pd


def draw_line():
    print("draw_line")
    path = r"C:\Users\IMO_0117\PycharmProjects\DoubleW\release\output\SP500_NOV2019_Hist.csv"
    df = pd.read_csv(path,
                     index_col=0,
                     parse_dates=True)
    print(df)
    # Customize market colors, and place inside style you intend to use:
    mc = mpf.make_marketcolors(up='yellow',
                               down='yellow')
    s = mpf.make_mpf_style(base_mpf_style='yahoo',
                           marketcolors=mc)

    # Create an all `nan` values dataframe, same size, and same index as the first:
    nans = [float('nan')] * len(df)
    cdf = pd.DataFrame(dict(Open=nans,
                            High=nans,
                            Low=nans,
                            Close=nans),
                       index=df.index)
    print(cdf)
    # Copy in the specific candles that you want to color:
    cdf.loc['2019-11-08'] = df.loc['2019-11-08']
    cdf.loc['2019-11-15'] = df.loc['2019-11-15']
    cdf.loc['2019-11-19'] = df.loc['2019-11-19']

    # cdf.loc['2019-11-08'] = df.loc['2019-11-08'].copy()
    # cdf.loc['2019-11-15'] = df.loc['2019-11-15'].copy()
    # cdf.loc['2019-11-19'] = df.loc['2019-11-19'].copy()
    # df.loc['2019-11-08'] = nans[0]
    # df.loc['2019-11-15'] = nans[0]
    # df.loc['2019-11-19'] = nans[0]

    # Call `mpf.plot()` twice with the two dataframes and two styles:
    fig, axlist = mpf.plot(df, type='candle', style='yahoo', returnfig=True)
    mpf.plot(cdf, type='candle', style=s, ax=axlist[0])


if __name__ == '__main__':
    draw_line()
`

**Comment by poeticlinuxer** [comment]
`mc = mpf.make_marketcolors(
    # base_mpf_style='nightclouds',
    up='red',  # up = color for close >= open
    down='green',  # down = color for close  < open
    # edge={'up': 'red',
    #       'down': 'green'},
    # wick={'up': 'red',
    #       'down': 'green'},
    # ohlc={'up': 'red',
    #       'down': 'green'},
    volume='inherit'
)

s = mpf.make_mpf_style(
    # base_mpl_style='yahoo',
    # Y轴在右边
    y_on_right=True,
    # 均线的颜色
    mavcolors=['#696969',
               '#DA70D6',
               '#4682B4',
               '#8B4500'
               ],
    marketcolors=mc,
    rc={'font.family': 'SimHei'}
)`


Finally, I do this .

**Comment by poeticlinuxer** [comment]
mc = mpf.make_marketcolors(
    # base_mpf_style='nightclouds',
    up='red',  # up = color for close >= open
    down='green',  # down = color for close  < open
    # edge={'up': 'red',
    #       'down': 'green'},
    # wick={'up': 'red',
    #       'down': 'green'},
    # ohlc={'up': 'red',
    #       'down': 'green'},
    volume='inherit'
)

s = mpf.make_mpf_style(
    # base_mpl_style='yahoo',
    # Y轴在右边
    y_on_right=True,
    # 均线的颜色
    mavcolors=['#696969',
               '#DA70D6',
               '#4682B4',
               '#8B4500'
               ],
    marketcolors=mc,
    rc={'font.family': 'SimHei'}
)

**Comment by poeticlinuxer** [comment]
mc = mpf.make_marketcolors(
    up='red', 
    down='green', 
)

s = mpf.make_mpf_style(
    y_on_right=True,
    mavcolors=['#696969',
               '#DA70D6',
               '#4682B4',
               '#8B4500'
               ],
    marketcolors=mc,
    rc={'font.family': 'SimHei'}
)


I use another way to do it .
