### ISSUE TITLE
Bug Report: fig.suptitle, AttributeError: 'NoneType' object has no attribute 'suptitle'

### ISSUE THREAD

**Issue by sevenseablue** [matplotlib/mplfinance#473]
code
```code
ap = mpf.make_addplot(res[['MA5', 'MA10', 'MA20', 'MA60']], ax=ax1)

mpf.plot(
    data=res,
    type='candle',
    title=code,
    ax=ax1,
    volume=ax2,
    addplot=ap,
    show_nontrading=False,
    style=my_style)
```

error
```text
Traceback (most recent call last):
  File "/home/wangdawei/github/stock/stock/paint.py", line 65, in <module>
    style=my_style)
  File "/home/wangdawei/anaconda3/envs/py37/lib/python3.7/site-packages/mplfinance/plotting.py", line 738, in plot
    fig.suptitle(title,**title_kwargs)
AttributeError: 'NoneType' object has no attribute 'suptitle'
```

solve:

modify /home/wangdawei/anaconda3/envs/py37/lib/python3.7/site-packages/mplfinance/plotting.py

```patch
737+        if not external_axes_mode:
738            fig.suptitle(title,**title_kwargs)
```

it solved

**Comment by DanielGoldfarb** [comment]
> solve:
> modify /home/wangdawei/anaconda3/envs/py37/lib/python3.7/site-packages/mplfinance/plotting.py
> 737+        if not external_axes_mode:
> 738            fig.suptitle(title,**title_kwargs)

This is ***not*** a bug.  The true correct solution would be to [*add a warning* **in this section of code here**](https://github.com/matplotlib/mplfinance/blob/master/src/mplfinance/plotting.py#L308-L323).

**Please note** that "external axes mode" (or even accessing the Figure and Axes objects directly) is [**strongly discouraged, as noted here**](https://github.com/matplotlib/mplfinance/wiki/Acessing-mplfinance-Figure-and-Axes-objects) ***unless what you are trying to accomplish cannot be done in any other way.***   From the small amount of code you have posted it appears that access to the Figure and Axes objects may ***not*** be necessary.

(See also [List of Features Not Supported in External Axes Mode](https://github.com/matplotlib/mplfinance/wiki/List-of-Features-Not-Supported-in-External-Axes-Mode).)
