### ISSUE TITLE
linux use plot error

### ISSUE THREAD

**Issue by nanshens** [matplotlib/mplfinance#477]
when i use it in linux, i will show it.
![image](https://user-images.githubusercontent.com/29112598/144783349-3a4b7fb1-6654-4ca6-8b49-b1d56a38906c.png)

**Comment by DanielGoldfarb** [comment]
That is a very vague question you have posted.

Looks like you are using **tkinter**.  If you have not already gone through at least the first 3 or 4 tutorials on using mplfinance *without* tkinter or any other gui package, then I strongly recommend you **do that first!**

After you have learned the basic tutorials, here are several links about using tkinter with mpfinance.  I suggest you read through them carefully and also follow the links in each of these to other postings that may help you:
- https://github.com/matplotlib/mplfinance/issues/178#issuecomment-645750460
- https://github.com/matplotlib/mplfinance/issues/304#issuecomment-751532329
- https://github.com/matplotlib/mplfinance/issues/440#issuecomment-911653228

Good luck.
