### ISSUE TITLE
How can I remove y axis ticker

### ISSUE THREAD

**Issue by ryzryztc** [matplotlib/mplfinance#481]
by setting datetime_format='' " i remove tickers on X axis. how can i do the same to the y axis? like in matplotlib plt.yticks([])

**Comment by DanielGoldfarb** [comment]
Depending exactly what you want to accomplish, you can try one of the following:

Given the following plot:
```python
mpf.plot(df,type='candle',volume=True)
```
![image](https://user-images.githubusercontent.com/11164790/145976893-ff8f9b5a-150a-4c12-a975-164b149bfb36.png)

---
- Use kwarg **`axisoff=True`** to accomplish the folowing:
```python
mpf.plot(df,type='candle',volume=True,axisoff=True)
```
![image](https://user-images.githubusercontent.com/11164790/145977083-80f9cf7f-6aa1-4796-9c33-e7888ac88029.png)

---

- Or use `returnfig=True` and `Axes.set_[xy]ticklabels()` to accomplish the following:
```python
fig, axlist = mpf.plot(df,type='candle',volume=True,returnfig=True)
axlist[0].set_xticklabels([])
axlist[0].set_yticklabels([])
axlist[2].set_yticklabels([])
mpf.show()
```
![image](https://user-images.githubusercontent.com/11164790/145978371-e26cb1c8-e951-4eab-9a8a-90e4bee9f350.png)

---

- or alternatively:
```python
fig, axlist = mpf.plot(df,type='candle',volume=True,returnfig=True)
axlist[0].set_xticklabels([])
axlist[0].set_yticklabels([])
axlist[0].set_ylabel('')
axlist[2].set_yticklabels([])
axlist[2].set_ylabel('')
mpf.show()
```

![image](https://user-images.githubusercontent.com/11164790/145977620-97d9a192-175f-4bc1-b249-3c32eb39a78b.png)

---

- If you are not familiar with `returnfig=True` [**click here**](https://github.com/matplotlib/mplfinance/wiki/Acessing-mplfinance-Figure-and-Axes-objects)
- If you are working inside jupyter notebook, then replease `mpf.show()` with simply `fig`

**Comment by Anshika91** [comment]
please assign this work to me ...

**Comment by Anshika91** [comment]
To remove the tickers on the y-axis, tick_params() method has an attribute named left and we can set its value to False and pass it as a parameter inside the tick_params() function. It removes the tick on the y-axis.
