### ISSUE TITLE
How to avoid 2 y axis?

### ISSUE THREAD

**Issue by banhao** [matplotlib/mplfinance#486]
I used the following code to generate the plot.  But I'm having a very weird issue that in some serial data, the y axis will be 2.
This is the error one, the "BOLLINGER_HBAND" and "BOLLINGER_LBAND" are not using the same y Axis.
<img src="https://github.com/banhao/CoinBasePro-Trading-Simulator/blob/main/screenshot/XRPUSDT_1d.jpg">
https://github.com/banhao/CoinBasePro-Trading-Simulator/blob/main/screenshot/XRPUSDT_1d.jpg

But this one, it became correct, the code is exactly the same. 
<img src="https://github.com/banhao/CoinBasePro-Trading-Simulator/blob/main/screenshot/XRPUSDT_4h.jpg">
https://github.com/banhao/CoinBasePro-Trading-Simulator/blob/main/screenshot/XRPUSDT_4h.jpg

```
mc = mpf.make_marketcolors(up='#5ac390',down='#fd6a6c',volume='in',edge='None',)
s  = mpf.make_mpf_style(base_mpl_style='fivethirtyeight',marketcolors=mc)
mpf.plot( serial_data, type='candle', style=s, addplot=TA_plot, title=item+' '+interval, volume=True, panel_ratios=(4,1), ylabel='Price', ylabel_lower='Volume', returnfig=True, savefig=dict(fname=variable.plot_path+'/'+item+'_'+interval+'.png',dpi=300) )
```

And another question, how to keep the font size the same as the plot shown on the screen. When I show the plots on screen they are beautiful but when I saved them as .png files, the font size changed and became ugly.

**Comment by DanielGoldfarb** [comment]
The images above are not available nor visible.  If you can please paste the actual text output that will be helpful to try to understand what you are talking about.

**Comment by banhao** [comment]
Hello Daniel,
I updated the url of the plots. Hope it can help you to understand my issue. I used "ta" library to generate these indicators.
https://github.com/bukosabino/ta

The following are the code, just copy/paste to python command line can generate the issue .png file(with 2 y axis). But if you changed the "interval = '4h' "  it will generate the .png file is good.(1 y axis) 

```
import ta,requests
import pandas as pd
import numpy as np
import dateutil.parser as dp
import matplotlib as mpl
import matplotlib.pyplot as plt
import mplfinance as mpf
item = 'XRPUSDT'
interval = '1d'
limit = '300'
api_url = 'https://api.binance.com'
regress_history_data_price = requests.get(api_url + '/api/v3/klines?symbol='+item+'&interval='+interval+'&limit='+limit,timeout=5)
df = regress_history_data_price.json()
labels = ['Timestamp', 'Open', 'High', 'Low', 'Close', 'Volume', 'Close_Time', 'Quote_Asset_Volume', 'Number_of_Trades', 'Taker_Buy_Base_Asset_Volume', 'Taker_Buy_Quote_Asset_Volume', 'Ignore']
df = pd.DataFrame.from_records(df, columns=labels)
df['Timestamp'] = pd.to_datetime(df['Timestamp']//1000, unit='s')
df = df.sort_values(by = 'Timestamp',ascending=True)
df = df.set_index('Timestamp')
df = df.apply(pd.to_numeric) 
indicator_BOLLINGER = ta.volatility.BollingerBands(df['Close'], window=21,window_dev=2,fillna=False)
df['BOLLINGER_HBAND'] = indicator_BOLLINGER.bollinger_hband()
df['BOLLINGER_LBAND'] = indicator_BOLLINGER.bollinger_lband()
TA_plot = []
TA_plot.append(mpf.make_addplot(df['BOLLINGER_HBAND'], color='Fuchsia'))
TA_plot.append(mpf.make_addplot(df['BOLLINGER_LBAND'], color='blue'))
mc = mpf.make_marketcolors(up='#5ac390',down='#fd6a6c',volume='in',edge='None',)
s  = mpf.make_mpf_style(base_mpl_style='fivethirtyeight',marketcolors=mc)
mpf.plot( df, type='candle', style=s, addplot=TA_plot, title=item+' '+interval, volume=True, panel_ratios=(4,1), ylabel='Price', ylabel_lower='Volume', returnfig=True, savefig=dict(fname=item+'_'+interval+'.png',dpi=300) )

```

Thanks for your helping! Merry Christmas and Happy New Year!

**Comment by DanielGoldfarb** [comment]
@banhao 
Regarding the HBand and LBand being on different axes, you may want to set `secondary_y=False` in both calls to `mpf.make_addplot()`.   From [the addplot documentation](https://github.com/matplotlib/mplfinance/blob/master/examples/addplot.ipynb):

---
- mpf.make_addplot() has a keyword argument called `secondary_y` which can have three possible values: **`True`**, **`False`**, and **`'auto'`**.
  - The default value is `'auto'` which means if you don't specify `secondary_y`, or if you specify `secondary_y='auto'`, then mpf.plot() will attempt to decide whether a secondary y-axis is needed, by comparing the order of magnitude of the addplot data with the order of magnitude of the data that is already on the plot.
  - If `mpf.plot()` gets it wrong, you can always override by setting **`secondary_y=True` or `secondary_y=False`**.
---

Regarding the font size changing when you use the `savefig` kwarg, I have not seen this problem before.  When I have some time I will play with the code and see if I can reproduce.  In the meantime, I would suggest that you can play with the following kwargs, tweaking them this way and that to see if it helps:
- the `dpi` kwarg of the `savefig` dict (which I see you are already using; perhaps making it larger or smaller will help).
- the `figscale` kwarg of `mpf.plot()` to scale the Figure size either up or down by setting it to a float that is either larger than 1.0 or smaller than 1.0.
- the `fontscale` kwarg of `mpf.plot()` to scale the Fonts sizes on the Figure either up or down by setting it to a float that is either larger than 1.0 or smaller than 1.0.
Please let me know if any of these ideas help.  Thanks.   All the best.  --Daniel

**Comment by DanielGoldfarb** [comment]
Actually I was curious about this font issue, so I started playing with it:

- Changing `dpi` did *not* make any significant difference.
- **Setting **`figscale=1.25`** seems to fix the problem** (at least for the data that I am playing with) so that with **`figscale=1.25`** the fonts on the saved plot are approximately the same size as those on the screen plot.   (As you increase `figscale`, the Figure itself gets larger but the fonts do not, so the fonts will *appear* smaller and smaller as you gradually increase `figscale`.)

**Comment by banhao** [comment]
Hello Daniel,
Thank you very much. 
The final plot looks like this: 
https://github.com/banhao/CoinBasePro-Trading-Simulator/blob/main/screenshot/XRPUSDT_1d_fixed.png 

It's perfect.
I used "figscale=1.3, fontscale=0.5" kwargs of mpf.plot(), and dpi=120 which will generate a plot with 1248pix*897pix. 

Thanks again!

**Comment by DanielGoldfarb** [comment]
Great!   Thanks for sharing your plot.  I really enjoy seeing the great things people are doing with mplfinance.
All the best.
