### ISSUE TITLE
Bug Report: high and low tick marks inverse

### ISSUE THREAD

**Issue by spicker22** [matplotlib/mplfinance#489]
**Describe the bug**
Sometimes the high and low tick marks are inverted. For example, instead of the high marker being on top of the candlebox, it is within the candlebox. 

**To Reproduce**
use this code 
```
for start, end in r.items():
            image = fplt.plot(
                    df2.loc[start : end],
                    type="candle",
                    #mav=(2),
                    figratio=(12,8),
                    volume=False,
                    axisoff=True,
                    show_nontrading=False,  
                    style='classic',
                    savefig=path1 + str(f) + str(start) + str(end)+ ".png"
                    ) 
```
**Expected behavior**
It is expected that all the candleboxes will have the high and low tick markers on top or below the box. Not within it. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser chrome

**Smartphone (please complete the following information):**

**Additional context**
<img width="687" alt="Screen Shot 2022-01-05 at 9 20 51 PM" src="https://user-images.githubusercontent.com/96645673/148327633-9cdb5f58-7e2e-4b52-a6af-1ea30d390ff3.png">

**Comment by DanielGoldfarb** [comment]
Please provide data (entire contents of df2.loc[start : end], ideally in csv format) to reproduce.

**Comment by DanielGoldfarb** [comment]
I am 99.44% sure that ***the problem is with your data*** ... most likely, on the day in question, your High and Low values are switched with the Open and Close, or at the very least they are in between the Open and Close (so they are not the actual High and Low).
