### ISSUE TITLE
Bug Report: type='ohlc' not work

### ISSUE THREAD

**Issue by GF-Huang** [matplotlib/mplfinance#503]
![image](https://user-images.githubusercontent.com/4510984/155901341-82cdb148-6919-4bcf-8cdc-ef3d0aac157f.png)
![image](https://user-images.githubusercontent.com/4510984/155901346-dce8483a-71b4-4647-bdf3-6ef24415ec19.png)

**Comment by DanielGoldfarb** [comment]
The plot looks fine to me for `type='ohlc'`.  

First, please read all of https://github.com/matplotlib/mplfinance/wiki/Plotting-Too-Much-Data and be certain that is not your issue.   If not, then please explain in detail what you think should be different about the plot.

**Comment by GF-Huang** [comment]
Another question, how to make the plot interaction? e.g. show the crosshair and price label.
