### ISSUE TITLE
Feature Request: Can we please have 'ema' plotting similarly to mav

### ISSUE THREAD

**Issue by swargamr** [matplotlib/mplfinance#506]
**Is your feature request related to a problem? Please describe.**
I would like to plot the Exponential Moving Average in mplfinance 
we have Simple moving average, but ema would also help for number of stratergies.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by alexandrepal** [comment]
Since you are dealing with DataFrames we can use something like
data['Close'].ewm(span=50.0,adjust=False).mean()
to get a 50 EMA.
In order to plot it you can explore alines
