### ISSUE TITLE
如何在mplfinance 图中增加备注文本

### ISSUE THREAD

**Issue by lyl1836** [matplotlib/mplfinance#520]
Mplfinance is great and brings great convenience to our work! Thank you for your hard work!

I want to check the details on the K-line diagram. Since mplfinance does not support picking events, I want to add text annotation on the diagram, as shown in the figure:

![img](https://user-images.githubusercontent.com/48607893/162904954-87fa4b08-5d9d-4cdd-83d5-22a06b657db8.png)

How to realize this function?

**Comment by lyl1836** [comment]
Or to put it another way: to read the value of OHLC, what scheme does mplfinance recommend?

**Comment by DanielGoldfarb** [comment]
We are planning (hopefully by the end of this year) to build this feature into mplfinance, which will make it much simpler for you to do.  In the meantime, if you want to do this, you have to use matplotlib methods together with mplfinance.

The first step is to [**gain access to mplfinance's Axes objects**](https://github.com/matplotlib/mplfinance/wiki/Acessing-mplfinance-Figure-and-Axes-objects).  I recommend using the `returnfig=True` technique to keep things simpler.

After you have the Axes objects, you call matplotlib Axes method [`Axes.text()`](https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.text.html) or [`Axes.annotate()`](https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.annotate.html)

- **You can see a good explanation of how to do this, [along with a code example, by clicking here](https://stackoverflow.com/a/70342687/1639359).**

(That [code example](https://stackoverflow.com/a/70342687/1639359) uses [`Axes.text()`](https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.text.html) but the same idea works for [`Axes.annotate()`](https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.annotate.html)).

[Additional information may be found here](https://github.com/matplotlib/mplfinance/issues/387#issuecomment-828135146).

Please let me know if you have any questions on the above.

**Comment by lyl1836** [comment]
@DanielGoldfarb 
Thank you. Let me test it!
