### ISSUE TITLE
Draw chart without date

### ISSUE THREAD

**Issue by a-Rahmati** [matplotlib/mplfinance#521]
Hello,

Is it possible to not have a date index in DataFrame?

Thaks

**Comment by DanielGoldfarb** [comment]
What kind of a chart do you want to draw?   
- What data is on your x-axis?
- What data is on your y-axis?

**Comment by a-Rahmati** [comment]
I have a DataFrame like this:
![Selection_324](https://user-images.githubusercontent.com/52320192/163664948-cb0e49b8-76c8-4aed-a25d-69f85a735d8e.png)

There's no date index So I get an error:
```python
TypeError: Expect data.index as DatetimeIndex
```

I want to draw a plot like this:
![Selection_325](https://user-images.githubusercontent.com/52320192/163665166-02878d38-f42f-47f6-be58-ecae191b9a2a.png)

**Comment by DanielGoldfarb** [comment]
Just to clarify, 
1. Do you have any column that includes date or time?
2. Are you saying that ***even if you have a datetime column you would still prefer to display row numbers on the x-axis?***
