### ISSUE TITLE
How to draw a hidden K-line with mplfinance?

### ISSUE THREAD

**Issue by lyl1836** [matplotlib/mplfinance#523]
@DanielGoldfarb :
When there are many K-line data, the drawing is not intuitive. I want to draw a hidden K-line.

The following figure shows the effect drawn with Matplotlib.

How to draw such an effect with mplfinance?

![tBU2](https://user-images.githubusercontent.com/48607893/164360146-8d1eb16e-b185-4b73-88c3-238be8c8add0.jpg)

**Comment by DanielGoldfarb** [comment]
@lyl1836 
You should be able to do that with the **`alines`** kwarg of mplfinance.  
[**Click here for more details**](https://github.com/matplotlib/mplfinance/blob/master/examples/using_lines.ipynb) and read through the entire tutorial to understand how best to use **`alines`**.

**Comment by lyl1836** [comment]
@DanielGoldfarb 
Thank you.

**Comment by lyl1836** [comment]
@DanielGoldfarb ：

I clearly remember that you had a new reply to this question last time, but now why can't you find it? Is the data lost?

Can you give me the last answer again?

**Comment by DanielGoldfarb** [comment]
Is this what you are looking for?
[**Does mplfinance support simple line diagram without K line?**](https://github.com/matplotlib/mplfinance/issues/524)
