### ISSUE TITLE
Request: the code to display the graphics of mplfinance in pyqt5!

### ISSUE THREAD

**Issue by lyl1836** [matplotlib/mplfinance#525]
@DanielGoldfarb ：

I want to put the candle diagram generated by mplfinance in pyqt5. 

After testing, I can save the file with mplfinance and then load the file into pyqt5.

Can I directly display the image generated by mplfinance in pyqt5 without file transfer?

Please also give me a sample code!

Thank you.

**Comment by DanielGoldfarb** [comment]
I am not very familiar with PyQT5.

I suggest you do a web search on ["Embed Matplotlib in PyQT5"](https://www.google.com/search?q=embed+matplotlib+in+pyqt5&rlz=1C1SQJL_enUS917US917&oq=embed+matplotlib+in+pyqt5) or something similar.

You will need [**access to mplfinance's Figure object**](https://github.com/matplotlib/mplfinance/wiki/Acessing-mplfinance-Figure-and-Axes-objects) ... I recommend using the `returnfig=True` method (however either method will work).
