### ISSUE TITLE
Is there way to remove space between candles?

### ISSUE THREAD

**Issue by Batja39** [matplotlib/mplfinance#531]
Is there any way to remove space (gap) between candlesticks?

**Comment by DanielGoldfarb** [comment]
@Batja39 
The space between candlesticks depends on how wide you make the candlesticks.

I reccomend that you read very carefully through the entire [**widths tutorial**](https://github.com/matplotlib/mplfinance/blob/master/examples/widths.ipynb) till the very end.  That should be enough to help you figure it out, but let me know if you have any questions after that.

**Comment by Batja39** [comment]
> @Batja39 The space between candlesticks depends on how wide you make the candlesticks.
> 
> You can adjust the candlestick width by setting the following kwarg:
> 
> ```python
> scale_width_adjustment=dict(candle=<w>)
> ```
> 
> where <w> is a float somewhat larger than 1.0
> 
> For example, to make the candles 50% wider you would write:
> 
> ```python
> mpf.plot(data,type='candle',...,scale_width_adjustment=dict(candle=1.5))
> ```
> 
> That should be enough to help you figure it out, but let me know if you have any questions after that. For more details, you can also read through the [**widths tutorial**](https://github.com/matplotlib/mplfinance/blob/master/examples/widths.ipynb).
