### ISSUE TITLE
How can I add cursor in mplfinance?

### ISSUE THREAD

**Issue by JLTG2018** [matplotlib/mplfinance#533]
I want to add cursor in main panel, How can I do it?

**Comment by DanielGoldfarb** [comment]
There may be several ways to do this.  

I suggest using [**matplotlib's `MultiCursor` class**](https://matplotlib.org/stable/api/widgets_api.html#matplotlib.widgets.MultiCursor).   
- You can control whether the cursor is a vertical bar (default), or horizontal, or both, using `Multicusor()` kwargs `horizOn` and/or `VertOn`, and ...
- You can control on which panel(s) the cursor appears by passing one or more Axes objects to the `MultiCursor()` constructor.

To do this with mplfinance, you will have to [**use `returnfig=True`**](https://github.com/matplotlib/mplfinance/wiki/Acessing-mplfinance-Figure-and-Axes-objects) to gain access to mplfinance's Figure and Axes objects.

[**Click here for an example of using `MultiCursor` with mplfinance**](https://github.com/matplotlib/mplfinance/issues/303#issuecomment-751514821).

All the best.
