### ISSUE TITLE
Issue with the feature that changes candle colors (marketcolor_overrides)

### ISSUE THREAD

**Issue by TraderMan999** [matplotlib/mplfinance#535]
I'm trying to use the feature rolled out in December of 2021 that allows me to make a single candle a different color.  

I'm using the MCOveride example that works with big data sets.

At a high level (detailed code etc below), I create a csv file with date, OHLC, and MCOverride columns.

If i want the candle to be handled normally, i note "None" in the MCOverride column.  For the date that I want the candle to be handled differently, i set it to an "mc" value.

Here's my CSV:

date,open,high,low,close,MCOOverrides
2021-01-12,378.89,379.86,376.36,378.77,None
2021-01-13,378.69,380.86,377.85,379.79,None
2021-01-14,380.59,381.13,378.10,378.46,None
2021-01-15,376.72,377.58,373.70,375.70,None
2021-01-19,378.34,379.23,376.75,378.65,None
2021-01-20,381.11,384.79,380.69,383.89,None
2021-01-21,384.49,384.95,383.25,384.24,None
2021-01-22,382.25,384.13,381.83,382.88,None
2021-01-25,383.67,384.77,378.46,384.39,None
2021-01-26,385.41,385.85,383.54,383.79,None
2021-01-27,380.22,380.32,372.01,374.41,red
2021-01-28,376.36,381.93,375.89,377.63,None
2021-01-29,375.63,376.67,368.27,370.07,None
2021-02-01,373.72,377.34,370.38,376.23,None

here's my code:

                mc = mpf.make_marketcolors(base_mpf_style='yahoo')

                                for ts in data.index:
                    if data.loc[ts, 'MCOverrides'] == 'None':
                        data.loc[ts, 'MCOverrides'] = [mc]
                    else:
                        data.loc[ts, 'MCOverrides'] = 'black'

                mco = data['MCOverrides'].values

                mpf.plot(data, type='candle',style='yahoo',marketcolor_overrides=mco,title=title,savefig=savedPlotFileName, figscale=1.4)

My data frames before the above for loop and after:

          date    open    high     low   close MCOverrides
0   2021-01-12  378.89  379.86  376.36  378.77        None
1   2021-01-13  378.69  380.86  377.85  379.79        None
2   2021-01-14  380.59  381.13  378.10  378.46        None
3   2021-01-15  376.72  377.58  373.70  375.70        None
4   2021-01-19  378.34  379.23  376.75  378.65        None
5   2021-01-20  381.11  384.79  380.69  383.89        None
6   2021-01-21  384.49  384.95  383.25  384.24        None
7   2021-01-22  382.25  384.13  381.83  382.88        None
8   2021-01-25  383.67  384.77  378.46  384.39        None
9   2021-01-26  385.41  385.85  383.54  383.79        None
10  2021-01-27  380.22  380.32  372.01  374.41         red
11  2021-01-28  376.36  381.93  375.89  377.63        None
12  2021-01-29  375.63  376.67  368.27  370.07        None
13  2021-02-01  373.72  377.34  370.38  376.23        None
data.columns =  Index(['date', 'open', 'high', 'low', 'close', 'MCOverrides'], dtype='object')
data               open  ...                                        MCOverrides
date                ...                                                   
2021-01-12  378.89  ...  [{'candle': {'up': '#00b060', 'down': '#fe3032...
2021-01-13  378.69  ...  [{'candle': {'up': '#00b060', 'down': '#fe3032...
2021-01-14  380.59  ...  [{'candle': {'up': '#00b060', 'down': '#fe3032...
2021-01-15  376.72  ...  [{'candle': {'up': '#00b060', 'down': '#fe3032...
2021-01-19  378.34  ...  [{'candle': {'up': '#00b060', 'down': '#fe3032...
2021-01-20  381.11  ...  [{'candle': {'up': '#00b060', 'down': '#fe3032...
2021-01-21  384.49  ...  [{'candle': {'up': '#00b060', 'down': '#fe3032...
2021-01-22  382.25  ...  [{'candle': {'up': '#00b060', 'down': '#fe3032...
2021-01-25  383.67  ...  [{'candle': {'up': '#00b060', 'down': '#fe3032...
2021-01-26  385.41  ...  [{'candle': {'up': '#00b060', 'down': '#fe3032...
2021-01-27  380.22  ...                                              black
2021-01-28  376.36  ...  [{'candle': {'up': '#00b060', 'down': '#fe3032...
2021-01-29  375.63  ...  [{'candle': {'up': '#00b060', 'down': '#fe3032...
2021-02-01  373.72  ...  [{'candle': {'up': '#00b060', 'down': '#fe3032...

Just for this exercise, I made every "None" column have an MC value  and the 'red' MCOverride value i changed to 'black'

I get this exception stack trace:

[14 rows x 5 columns]
mco =  [list([{'candle': {'up': '#00b060', 'down': '#fe3032'}, 'edge': {'up': '#00b060', 'down': '#fe3032'}, 'wick': {'up': '#606060', 'down': '#606060'}, 'ohlc': {'up': '#00b060', 'down': '#fe3032'}, 'volume': {'up': '#4dc790', 'down': '#fd6b6c'}, 'vcedge': {'up': '#1f77b4', 'down': '#1f77b4'}, 'vcdopcod': False, 'alpha': 0.9}])
 list([{'candle': {'up': '#00b060', 'down': '#fe3032'}, 'edge': {'up': '#00b060', 'down': '#fe3032'}, 'wick': {'up': '#606060', 'down': '#606060'}, 'ohlc': {'up': '#00b060', 'down': '#fe3032'}, 'volume': {'up': '#4dc790', 'down': '#fd6b6c'}, 'vcedge': {'up': '#1f77b4', 'down': '#1f77b4'}, 'vcdopcod': False, 'alpha': 0.9}])
 list([{'candle': {'up': '#00b060', 'down': '#fe3032'}, 'edge': {'up': '#00b060', 'down': '#fe3032'}, 'wick': {'up': '#606060', 'down': '#606060'}, 'ohlc': {'up': '#00b060', 'down': '#fe3032'}, 'volume': {'up': '#4dc790', 'down': '#fd6b6c'}, 'vcedge': {'up': '#1f77b4', 'down': '#1f77b4'}, 'vcdopcod': False, 'alpha': 0.9}])
 list([{'candle': {'up': '#00b060', 'down': '#fe3032'}, 'edge': {'up': '#00b060', 'down': '#fe3032'}, 'wick': {'up': '#606060', 'down': '#606060'}, 'ohlc': {'up': '#00b060', 'down': '#fe3032'}, 'volume': {'up': '#4dc790', 'down': '#fd6b6c'}, 'vcedge': {'up': '#1f77b4', 'down': '#1f77b4'}, 'vcdopcod': False, 'alpha': 0.9}])
 list([{'candle': {'up': '#00b060', 'down': '#fe3032'}, 'edge': {'up': '#00b060', 'down': '#fe3032'}, 'wick': {'up': '#606060', 'down': '#606060'}, 'ohlc': {'up': '#00b060', 'down': '#fe3032'}, 'volume': {'up': '#4dc790', 'down': '#fd6b6c'}, 'vcedge': {'up': '#1f77b4', 'down': '#1f77b4'}, 'vcdopcod': False, 'alpha': 0.9}])
 list([{'candle': {'up': '#00b060', 'down': '#fe3032'}, 'edge': {'up': '#00b060', 'down': '#fe3032'}, 'wick': {'up': '#606060', 'down': '#606060'}, 'ohlc': {'up': '#00b060', 'down': '#fe3032'}, 'volume': {'up': '#4dc790', 'down': '#fd6b6c'}, 'vcedge': {'up': '#1f77b4', 'down': '#1f77b4'}, 'vcdopcod': False, 'alpha': 0.9}])
 list([{'candle': {'up': '#00b060', 'down': '#fe3032'}, 'edge': {'up': '#00b060', 'down': '#fe3032'}, 'wick': {'up': '#606060', 'down': '#606060'}, 'ohlc': {'up': '#00b060', 'down': '#fe3032'}, 'volume': {'up': '#4dc790', 'down': '#fd6b6c'}, 'vcedge': {'up': '#1f77b4', 'down': '#1f77b4'}, 'vcdopcod': False, 'alpha': 0.9}])
 list([{'candle': {'up': '#00b060', 'down': '#fe3032'}, 'edge': {'up': '#00b060', 'down': '#fe3032'}, 'wick': {'up': '#606060', 'down': '#606060'}, 'ohlc': {'up': '#00b060', 'down': '#fe3032'}, 'volume': {'up': '#4dc790', 'down': '#fd6b6c'}, 'vcedge': {'up': '#1f77b4', 'down': '#1f77b4'}, 'vcdopcod': False, 'alpha': 0.9}])
 list([{'candle': {'up': '#00b060', 'down': '#fe3032'}, 'edge': {'up': '#00b060', 'down': '#fe3032'}, 'wick': {'up': '#606060', 'down': '#606060'}, 'ohlc': {'up': '#00b060', 'down': '#fe3032'}, 'volume': {'up': '#4dc790', 'down': '#fd6b6c'}, 'vcedge': {'up': '#1f77b4', 'down': '#1f77b4'}, 'vcdopcod': False, 'alpha': 0.9}])
 list([{'candle': {'up': '#00b060', 'down': '#fe3032'}, 'edge': {'up': '#00b060', 'down': '#fe3032'}, 'wick': {'up': '#606060', 'down': '#606060'}, 'ohlc': {'up': '#00b060', 'down': '#fe3032'}, 'volume': {'up': '#4dc790', 'down': '#fd6b6c'}, 'vcedge': {'up': '#1f77b4', 'down': '#1f77b4'}, 'vcdopcod': False, 'alpha': 0.9}])
 'black'
 list([{'candle': {'up': '#00b060', 'down': '#fe3032'}, 'edge': {'up': '#00b060', 'down': '#fe3032'}, 'wick': {'up': '#606060', 'down': '#606060'}, 'ohlc': {'up': '#00b060', 'down': '#fe3032'}, 'volume': {'up': '#4dc790', 'down': '#fd6b6c'}, 'vcedge': {'up': '#1f77b4', 'down': '#1f77b4'}, 'vcdopcod': False, 'alpha': 0.9}])
 list([{'candle': {'up': '#00b060', 'down': '#fe3032'}, 'edge': {'up': '#00b060', 'down': '#fe3032'}, 'wick': {'up': '#606060', 'down': '#606060'}, 'ohlc': {'up': '#00b060', 'down': '#fe3032'}, 'volume': {'up': '#4dc790', 'down': '#fd6b6c'}, 'vcedge': {'up': '#1f77b4', 'down': '#1f77b4'}, 'vcdopcod': False, 'alpha': 0.9}])
 list([{'candle': {'up': '#00b060', 'down': '#fe3032'}, 'edge': {'up': '#00b060', 'down': '#fe3032'}, 'wick': {'up': '#606060', 'down': '#606060'}, 'ohlc': {'up': '#00b060', 'down': '#fe3032'}, 'volume': {'up': '#4dc790', 'down': '#fd6b6c'}, 'vcedge': {'up': '#1f77b4', 'down': '#1f77b4'}, 'vcdopcod': False, 'alpha': 0.9}])]
Traceback (most recent call last):
  File "C:\main.py", line 4345, in <module>
    main()
  File "C:\main.py", line 4166, in main

  File "C:\main.py", line 613, in earningsWithMCOOverrides
    processCSVWithMCOOverrides(x + "-FOMCPressers")
  File "C:\main.py", line 4046, in processCSVWithMCOOverrides
    mpf.plot(data, type='candle',style='yahoo',marketcolor_overrides=mco,title=title,savefig=savedPlotFileName, figscale=1.4)
  File "C:\venv\lib\site-packages\mplfinance\plotting.py", line 389, in plot
    config = _process_kwargs(kwargs, _valid_plot_kwargs())
  File "C:\venv\lib\site-packages\mplfinance\_arg_validators.py", line 322, in _process_kwargs
    raise TypeError('kwarg "'+key+'" validator returned False for value: "'+str(value)+'"\n    '+v)
TypeError: kwarg "marketcolor_overrides" validator returned False for value: "[list([{'candle': {'up': '#00b060', 'down': '#fe3032'}, 'edge': {'up': '#00b060', 'down': '#fe3032'}, 'wick': {'up': '#606060', 'down': '#606060'}, 'ohlc': {'up': '#00b060', 'down': '#fe3032'}, 'volume': {'up': '#4dc790', 'down': '#fd6b6c'}, 'vcedge': {'up': '#1f77b4', 'down': '#1f77b4'}, 'vcdopcod': False, 'alpha': 0.9}])
 list([{'candle': {'up': '#00b060', 'down': '#fe3032'}, 'edge': {'up': '#00b060', 'down': '#fe3032'}, 'wick': {'up': '#606060', 'down': '#606060'}, 'ohlc': {'up': '#00b060', 'down': '#fe3032'}, 'volume': {'up': '#4dc790', 'down': '#fd6b6c'}, 'vcedge': {'up': '#1f77b4', 'down': '#1f77b4'}, 'vcdopcod': False, 'alpha': 0.9}])
 list([{'candle': {'up': '#00b060', 'down': '#fe3032'}, 'edge': {'up': '#00b060', 'down': '#fe3032'}, 'wick': {'up': '#606060', 'down': '#606060'}, 'ohlc': {'up': '#00b060', 'down': '#fe3032'}, 'volume': {'up': '#4dc790', 'down': '#fd6b6c'}, 'vcedge': {'up': '#1f77b4', 'down': '#1f77b4'}, 'vcdopcod': False, 'alpha': 0.9}])
 list([{'candle': {'up': '#00b060', 'down': '#fe3032'}, 'edge': {'up': '#00b060', 'down': '#fe3032'}, 'wick': {'up': '#606060', 'down': '#606060'}, 'ohlc': {'up': '#00b060', 'down': '#fe3032'}, 'volume': {'up': '#4dc790', 'down': '#fd6b6c'}, 'vcedge': {'up': '#1f77b4', 'down': '#1f77b4'}, 'vcdopcod': False, 'alpha': 0.9}])
 list([{'candle': {'up': '#00b060', 'down': '#fe3032'}, 'edge': {'up': '#00b060', 'down': '#fe3032'}, 'wick': {'up': '#606060', 'down': '#606060'}, 'ohlc': {'up': '#00b060', 'down': '#fe3032'}, 'volume': {'up': '#4dc790', 'down': '#fd6b6c'}, 'vcedge': {'up': '#1f77b4', 'down': '#1f77b4'}, 'vcdopcod': False, 'alpha': 0.9}])
 list([{'candle': {'up': '#00b060', 'down': '#fe3032'}, 'edge': {'up': '#00b060', 'down': '#fe3032'}, 'wick': {'up': '#606060', 'down': '#606060'}, 'ohlc': {'up': '#00b060', 'down': '#fe3032'}, 'volume': {'up': '#4dc790', 'down': '#fd6b6c'}, 'vcedge': {'up': '#1f77b4', 'down': '#1f77b4'}, 'vcdopcod': False, 'alpha': 0.9}])
 list([{'candle': {'up': '#00b060', 'down': '#fe3032'}, 'edge': {'up': '#00b060', 'down': '#fe3032'}, 'wick': {'up': '#606060', 'down': '#606060'}, 'ohlc': {'up': '#00b060', 'down': '#fe3032'}, 'volume': {'up': '#4dc790', 'down': '#fd6b6c'}, 'vcedge': {'up': '#1f77b4', 'down': '#1f77b4'}, 'vcdopcod': False, 'alpha': 0.9}])
 list([{'candle': {'up': '#00b060', 'down': '#fe3032'}, 'edge': {'up': '#00b060', 'down': '#fe3032'}, 'wick': {'up': '#606060', 'down': '#606060'}, 'ohlc': {'up': '#00b060', 'down': '#fe3032'}, 'volume': {'up': '#4dc790', 'down': '#fd6b6c'}, 'vcedge': {'up': '#1f77b4', 'down': '#1f77b4'}, 'vcdopcod': False, 'alpha': 0.9}])
 list([{'candle': {'up': '#00b060', 'down': '#fe3032'}, 'edge': {'up': '#00b060', 'down': '#fe3032'}, 'wick': {'up': '#606060', 'down': '#606060'}, 'ohlc': {'up': '#00b060', 'down': '#fe3032'}, 'volume': {'up': '#4dc790', 'down': '#fd6b6c'}, 'vcedge': {'up': '#1f77b4', 'down': '#1f77b4'}, 'vcdopcod': False, 'alpha': 0.9}])
 list([{'candle': {'up': '#00b060', 'down': '#fe3032'}, 'edge': {'up': '#00b060', 'down': '#fe3032'}, 'wick': {'up': '#606060', 'down': '#606060'}, 'ohlc': {'up': '#00b060', 'down': '#fe3032'}, 'volume': {'up': '#4dc790', 'down': '#fd6b6c'}, 'vcedge': {'up': '#1f77b4', 'down': '#1f77b4'}, 'vcdopcod': False, 'alpha': 0.9}])
 'black'
 list([{'candle': {'up': '#00b060', 'down': '#fe3032'}, 'edge': {'up': '#00b060', 'down': '#fe3032'}, 'wick': {'up': '#606060', 'down': '#606060'}, 'ohlc': {'up': '#00b060', 'down': '#fe3032'}, 'volume': {'up': '#4dc790', 'down': '#fd6b6c'}, 'vcedge': {'up': '#1f77b4', 'down': '#1f77b4'}, 'vcdopcod': False, 'alpha': 0.9}])
 list([{'candle': {'up': '#00b060', 'down': '#fe3032'}, 'edge': {'up': '#00b060', 'down': '#fe3032'}, 'wick': {'up': '#606060', 'down': '#606060'}, 'ohlc': {'up': '#00b060', 'down': '#fe3032'}, 'volume': {'up': '#4dc790', 'down': '#fd6b6c'}, 'vcedge': {'up': '#1f77b4', 'down': '#1f77b4'}, 'vcdopcod': False, 'alpha': 0.9}])
 list([{'candle': {'up': '#00b060', 'down': '#fe3032'}, 'edge': {'up': '#00b060', 'down': '#fe3032'}, 'wick': {'up': '#606060', 'down': '#606060'}, 'ohlc': {'up': '#00b060', 'down': '#fe3032'}, 'volume': {'up': '#4dc790', 'down': '#fd6b6c'}, 'vcedge': {'up': '#1f77b4', 'down': '#1f77b4'}, 'vcdopcod': False, 'alpha': 0.9}])]"
    def _mco_validator(value):        # marketcolor overrides validator
    if isinstance(value,dict):    # not yet supported, but maybe we will have other
        if 'colors' not in value: # kwargs related to mktcolor overrides (ex: `mco_faceonly`)
            raise ValueError('`marketcolor_overrides` as dict must contain `colors` key.')
        colors = value['colors']
    else:
        colors = value
    if not isinstance(colors,(list,tuple,np.ndarray)):
        return False
    return all([(c is None or 
                 _mpf_is_color_like(c) or
                 _is_marketcolor_object(c) ) for c in colors])

Any suggestions?  I'm at a roadblock.  I re-downloaded the latest version as well.

**Comment by TraderMan999** [comment]
To add to this, what I was originally doing was following these instructions noted at the link here:

https://github.com/matplotlib/mplfinance/blob/master/examples/marketcolor_overrides.ipynb

Users can color one or more specific candlesticks (or ohlc bars) differently than others.
Users may choose to do this in order to highlight a specific pattern or technical signal.
The marketcolor_overrides kwarg is used to specify individual candle colors.
marketcolor_overrides must be set it to an interable (list,tuple,ndarray) that is the same length as the dataframe being plotted.
The simplest way to do this is to create a "marketcolor overrides" column in the dataframe.
Rows where the user wants to override the candle color must contain a "color-like" object:
Examples of color-like objects include:
a string such as 'yellow' or '#ffff00'
an rgb or rgba tuple such as (1.0, 1.0, 0) or (1.0, 1.0, 0, 0.75), or (255, 255, 0) or (255, 255, 0, 0.75)
an mplfinance marketcolor object, created with mpf.make_marketcolors()
Rows where the user does NOT want to override the candle color MUST contain None values.

To keep it simple i did NOT have any volume data in my CSV file.

Also, I didnt use this function:

 mc = mpf.make_marketcolors(base_mpf_style='yahoo')

i simply took this data:

          date    open    high     low   close MCOverrides
0   2021-01-12  378.89  379.86  376.36  378.77        None
1   2021-01-13  378.69  380.86  377.85  379.79        None
2   2021-01-14  380.59  381.13  378.10  378.46        None
3   2021-01-15  376.72  377.58  373.70  375.70        None
4   2021-01-19  378.34  379.23  376.75  378.65        None
5   2021-01-20  381.11  384.79  380.69  383.89        None
6   2021-01-21  384.49  384.95  383.25  384.24        None
7   2021-01-22  382.25  384.13  381.83  382.88        None
8   2021-01-25  383.67  384.77  378.46  384.39        None
9   2021-01-26  385.41  385.85  383.54  383.79        None
10  2021-01-27  380.22  380.32  372.01  374.41         red
11  2021-01-28  376.36  381.93  375.89  377.63        None
12  2021-01-29  375.63  376.67  368.27  370.07        None
13  2021-02-01  373.72  377.34  370.38  376.23        None
data.columns =  Index(['date', 'open', 'high', 'low', 'close', 'MCOverrides'], dtype='object')

and where it was 'red', i changed it to 'blue'.

here's my code snippet:

 for ts in data.index:
                    if data.loc[ts, 'MCOverrides'] == 'None':
                        continue
                    else:
                        data.loc[ts, 'MCOverrides'] = 'blue'

               

                mco = data['MCOverrides'].values

               
                mpf.plot(data,type='candle',style='yahoo',title=title,savefig=savedPlotFileName, figscale=1.4)

this gives me a chart PNG file that looks like this:

![image](https://user-images.githubusercontent.com/105173625/170847539-e551005d-8099-4af5-a842-8a29d9dca3df.png)

As you can see, all the candles that had an MCO Override of 'None' are missing and i have 1 blue candle.

This is with mco =  ['None' 'None' 'None' 'None' 'None' 'None' 'None' 'None' 'None' 'None'
 'None' 'blue' 'None' 'None' 'None'] and passing in 'marketcolor_overrides=mco'

if i dont pass in this 'marketcolor_overrides=mco' kwarg, i get a normal yahoo chart, like this:

![image](https://user-images.githubusercontent.com/105173625/170847643-69bc8f4b-4103-49a6-8f9a-2b30972fa8e4.png)

**Comment by DanielGoldfarb** [comment]
[**This image**](https://user-images.githubusercontent.com/105173625/170847539-e551005d-8099-4af5-a842-8a29d9dca3df.png) is actually good ... it means you are on the right track.   

***The problem is that the string* `'None'` *is not the same as* `NoneType` *in python***.  You have to convert the string `'None'` to python `None` ... as shown in the code below:

The following code uses the data you posted above, except I changed 'red' to 'blue' in the data, just to make it more visible:

```python
import pandas as pd
import mplfinance as mpf
from io import StringIO

csv_string='''date,open,high,low,close,MCOOverrides
2021-01-12,378.89,379.86,376.36,378.77,None
2021-01-13,378.69,380.86,377.85,379.79,None
2021-01-14,380.59,381.13,378.10,378.46,None
2021-01-15,376.72,377.58,373.70,375.70,None
2021-01-19,378.34,379.23,376.75,378.65,None
2021-01-20,381.11,384.79,380.69,383.89,None
2021-01-21,384.49,384.95,383.25,384.24,None
2021-01-22,382.25,384.13,381.83,382.88,None
2021-01-25,383.67,384.77,378.46,384.39,None
2021-01-26,385.41,385.85,383.54,383.79,None
2021-01-27,380.22,380.32,372.01,374.41,blue
2021-01-28,376.36,381.93,375.89,377.63,None
2021-01-29,375.63,376.67,368.27,370.07,None
2021-02-01,373.72,377.34,370.38,376.23,None
'''

df = pd.read_csv(StringIO(csv_string),index_col=0,parse_dates=True)

# This plot is good, but no overrrides:
mpf.plot(df,type='candle',style='yahoo')

# This plot shows ONLY the override candle:  Why?
mpf.plot(df,type='candle',style='yahoo',marketcolor_overrides=df['MCOOverrides'].values)

# Convert string 'None' to python None:
df['MCOOverrides'] = [ None if v=='None' else v for v in df['MCOOverrides'].values]

# Now the plot looks good.  All yahoo candles, except one blue candle:
mpf.plot(df,type='candle',style='yahoo',marketcolor_overrides=df['MCOOverrides'].values)
```

---

I tested this code that I just posted, and it works fine:  makes 3 plots, as the comments in the code indicate.

Let me know if the above code works for you.

**Comment by TraderMan999** [comment]
oh wow!  i knew it would be something simple.  let me try and see if i can get it working.  Thanks for the quick response

woohoo!  that works.  totally missed in the Example docuentation that it needed to be a None type vs the word "None"

**Comment by DanielGoldfarb** [comment]
@TraderMan999  Glad to hear you got it working!
