### ISSUE TITLE
Remove volume axis

### ISSUE THREAD

**Issue by CThax12** [matplotlib/mplfinance#536]
Loving the library so far. I am wanting to remove the dividing line between the chart and volume. Here is my current code:

```
    start = dt.datetime(2021, 5, 20)
    end = dt.datetime.now()
    data = web.DataReader(ticker, "yahoo", start, end)
    colors = mpf.make_marketcolors(up="#00ff00", down="#ff0000", wick="inherit", edge="inherit", volume="inherit")
    mpf_style = mpf.make_mpf_style(base_mpf_style="mike", marketcolors=colors, gridcolor="000000")
    
    mpf.plot(data, type="candle", style=mpf_style, volume=True, savefig="chart.png", tight_layout=True, datetime_format="")
```

Here is a pic of what I have:
![image](https://user-images.githubusercontent.com/89363137/170914023-50ab696d-2997-4170-862c-b8792063ea0b.png)

Here is what I want:

![image](https://user-images.githubusercontent.com/89363137/170914372-0274f1be-b0da-416e-ba0d-61cd6a6d1497.png)

I can't seem to find any solutions, so I thought I would post here. Thank you!

**Comment by DanielGoldfarb** [comment]
This probably can be done with [`returnfig=True`](https://github.com/matplotlib/mplfinance/wiki/Acessing-mplfinance-Figure-and-Axes-objects) followed by setting `Axes.spines[...].set_visible(False)` for the appropriate spines on the appropriate Axes.  For example:

```python
fig, axlist = mpf.plot(data, type="candle", style=mpf_style, volume=True, 
                       tight_layout=True, datetime_format="", returnfig=True)
axlist[0].spines.bottom.set_visible(False)
axlist[2].spines.top.set_visible(False)
fig.savefig("chart.png")
```

---

Note, depending on what you are ultimately trying to accomplish, you may find the following alternatives useful:

1. [OHLC and Volume Data on the same Panel](https://stackoverflow.com/a/72382345/1639359).
2. [Set kwarg **`axisoff=True`**](https://github.com/matplotlib/mplfinance/issues/48#issuecomment-640296747).

**Comment by mangaroo** [comment]
I don't think this actually solves the second part, which is actually removing the volume axis (bottom-right blacked-out)? It just hides the dividing lines.

Been trying to solve this myself for a while now.

**Comment by DanielGoldfarb** [comment]
@mangaroo 

To also remove the dispaly of volume numbers and tick marks along the bottom right (or where ever it is for you chosen mpf style) ... try the following similar to above:

```python
fig, axlist = mpf.plot(data, type="candle", style=mpf_style, volume=True, 
                       tight_layout=True, datetime_format="", returnfig=True,
                       ylabel_lower='',     # no axes label (saying "Volume")
                       volume_exponent=0    # no "10^N" exponent
                       )
axlist[0].spines.bottom.set_visible(False)  # no line between main panel and volume panel
axlist[2].spines.top.set_visible(False)     # no line between main panel and volume panel
axlist[2].set_yticks([])                    # no tick marks on volume axes.
savefig.savefig("chart.png")
```

hope that helps.  let me know.   all the best.  --daniel
