### ISSUE TITLE
How do I hide the X axis?

### ISSUE THREAD

**Issue by lyl1836** [matplotlib/mplfinance#538]
@DanielGoldfarb ：

I want to hide the scale of x-axis or y-axis. What is the method?

![img1](https://user-images.githubusercontent.com/48607893/172828520-cbc5865e-33e6-4c36-9402-a28812e53dd2.png)

**Comment by DanielGoldfarb** [comment]
Try passing a null string to kwarg `datetime_format`:

```python
mpf.plot(df,...,datetime_format="")
```

---

Alternatively, you can remove all axes by setting **`axisoff=True`**
```python
mpf.plot(df,...,axisoff=True)
```
