### ISSUE TITLE
Dumping renko data to dictionary without chart generation

### ISSUE THREAD

**Issue by NaveenKota532** [matplotlib/mplfinance#540]
Dear Team,

I am using following statement  

renko_dict = {} # reassign every time before your 
 fplot.plot(dataframe, type='renko', renko_params=dict(brick_size=brick_size), return_calculated_values=renko_dict,
                       returnfig=True)

If I am using returnfig =False, chart is getting generated.
If I am using returnfig =True, I am getting the following exception
Fail to create pixmap with Tk_GetPixmap in TkImgPhotoInstanceSetSize

I would like to get the renko data for a given dataframe without chart. could anyone pls help!

With Best Regards,
Naveen

**Comment by DanielGoldfarb** [comment]
Need more information about your environment, *and your full code:*

> Fail to create pixmap with Tk_GetPixmap in TkImgPhotoInstanceSetSize

This ***is not* an mplfinance exception.  There is something else you are doing.   `returnfig=True` should do the trick for you.   Alternatively in external axes mode mplfinancr will also *not* display the plot.
