### ISSUE TITLE
Close Plot

### ISSUE THREAD

**Issue by mahmoodsoltani** [matplotlib/mplfinance#544]
Ask anything you want about mplfinance usage, project philosophy and/or priorities, or anything else related to mplfinance.
hi everyone,
how can I close plots? I create plots in a loop and after some iterates, when I call .show() function, all of the plots will appear on seperate windows!This is while only the last one is important for me. how can I closse all of plots except last one?

**Comment by DanielGoldfarb** [comment]
`mpf.plot(data,...closefig=True)` will tell mplfinance to close the plot before returning.  It is likely then, that the plot will only briefly flash on the screen, and then disappear.  It will be up to you, in your code, to determine when you are on the last plot that you do not want to close.

Alternatively, if you are calling `mpf.show()` yourself, then it sounds like you are either using `returnfig=True` or you are in external axes mode.  Either way, then ***you*** have control over the Figure object.  If so, after you have displayed the plot and you are ready to close it, try one of these:
- **`del fig   # delete the Figure object`**
- I don't recommend doing this: *but* if you have *already* (for whatever reason) imported `matplotlib.pyplot as plt` then you can call `plt.close(fig)` or `plt.close('all')`

Plese let me know if that answers your question.
