### ISSUE TITLE
Adjust style so that the center bar, open mark, and closing mark are each one pixel wide

### ISSUE THREAD

**Issue by LamBadaMan** [matplotlib/mplfinance#552]
I would like to produce a 60-day OHLC chart that includes a volume panel. The result should look like this (except for the moving average line):

<img width="914" alt="img" src="https://user-images.githubusercontent.com/85113275/188306272-df5f41cc-eadb-4d57-b9e1-8649e07570ec.png">

In particular, I want the following requirements to be satisfied:
- Volume is shown in the bottom one-fifth of the image while the top four-fifths contain the main OHLC plot.
- One day occupies an area three pixels wide (the center bar, open mark, and closing mark are each one pixel wide)
- The volume bar is also one pixel wide and placed in the same 'column' as the center bar
- The width of the image is 180 pixels (3 x 60 days), and the height is 96 pixels
- The vertical axis is scaled such that the maximum and minimum of the OHLC path coincides with the top and bottom of the image. Similarly, the maximum volume is set equal to the upper limit of the volume bar section and the remaining volume bars are scaled accordingly.
- The background color is black and the visible objects on the chart are coloured in white

I am struggling to find the parameters that allow me to set the width of the center bar, open mark, closing mark, and the volume bar to one pixel each. 

So far, I have come up with the following code:

```
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import mplfinance as mpf
import yfinance as yf

ohlc = yf.Ticker('MSFT').history(start='2022-06-01', end='2022-08-25')

mc = mpf.make_marketcolors(volume='white', ohlc='white')
s = mpf.make_mpf_style(marketcolors=mc, base_mpl_style=['dark_background'])

mpf.plot(ohlc,
         volume=True,
         figsize=(1.8,0.96),
         main_panel=0,
         volume_panel=1,
         panel_ratios=(5,1),
         style=s,
         axisoff=True,
         tight_layout=True)
```

Your help is high appreciated :)

**Comment by DanielGoldfarb** [comment]
Read carefully through the advanced [**widths tutorial**](https://github.com/matplotlib/mplfinance/blob/master/examples/widths.ipynb) and let me know if that helps you accomplish what you are trying to do.
