### ISSUE TITLE
Feature Request: Accept alpha as list instance for hlines

### ISSUE THREAD

**Issue by schroederjoa** [matplotlib/mplfinance#554]
It is possible to use lists as input for hlines parameters such as colors, linestyle, linewidths and therefore specify each hline individually. However, this does not seem possible with alpha because it would only accept float, int instance, resulting in the same alpha for all hlines. Would it be possible to implement the same functionality for alpha than for the other parameters? Thank you! Using latest version 0.12.9b1. Cheers, Joachim

**Comment by DanielGoldfarb** [comment]
Joachim,
This looks pretty easy to do.   Let me know if you would like me to guide you through the process, so that you can make the change and contribute to the library.  (I am currently distracted with other projects).

All the best.   --Daniel

**Comment by nijek** [comment]
I'm on it!

**Comment by DanielGoldfarb** [comment]
@nijek   Great!   This is probably as simple as changing [the `'alpha'` validator](https://github.com/matplotlib/mplfinance/blob/master/src/mplfinance/_utils.py#L499-L510) to allow a list, *similar to how the `'linewidths'` validator just above it allows a list.   Much appreciated.  Thanks.

**Comment by schroederjoa** [comment]
That is great, thank you very much everyone!
