### ISSUE TITLE
Histogram for custom indicators 

### ISSUE THREAD

**Issue by vlmercado** [matplotlib/mplfinance#556]
Ask anything you want about mplfinance usage, project philosophy and/or priorities, or anything else related to mplfinance.
When I plot a custom indicator in a panel, the plot type is a line. I'd like to see it as a histogram. Is there a way to do that?

**Comment by DanielGoldfarb** [comment]
`mpf.make_addplot()` accepts kwarg `type` which defaults to `'line'` but can be set to `'scatter'`, `'bar'`, `'ohlc'`, or `'candle'`.

You can see an example of this at cell **`In [21]:`** in [the addplot tutorial notebook](https://github.com/matplotlib/mplfinance/blob/master/examples/addplot.ipynb).
