### ISSUE TITLE
Update data in Tkinter application

### ISSUE THREAD

**Issue by eliasseverholt** [matplotlib/mplfinance#560]
Hello!

I'm sorry if this is the wrong forum to ask a question about this.

I have a TkInter application where I create an mplfinance plot to show some data of a certain ticker. I also want to be able to update this data. Currently I have a GUI class that handles all the visuals, then I have a method that adds a plot and then another method that tries to edit/refresh the figure with the new data.

Essentially it works a bit like the following
```py
Class GUI(tk.Tk):
  #Some nonrelevant code
  def createPlot(self):
    self.fig, _ mpf.plot(self.pdDataframe, returnFig=True)
    self.canvas = FigureCanvasTkAgg(fig)
    self.canvas.draw()
```

The createPlot works fine but I want to create a method that updates/re-renders the plot. How would I go about doing that? Creating a new figure doesn't seem to work since it gives me the following error "Starting a Matplotlib GUI outside of the main thread will likely fail. Is there a workaround for this?

**Comment by DanielGoldfarb** [comment]
@eliasseverholt 
I am not very well versed in TkInter, however it seems reasonable that the following may work:

Call your `createPlot()` *only for the initial creation of the Figure and plot*.   
You will need the Axes objects to update them later so change
```python
self.fig, _ mpf.plot(self.pdDataframe, returnFig=True)
```
to
```python
self.fig, self.axlist = mpf.plot(self.pdDataframe, returnFig=True)
```

For changes to the plot, I'd suggest writing `def updatePlot(self)` where you then pass the existing Axes object into `mpf.plot()`
```python
def updatePlot(self):
    myaxes = self.axlist[0]
    myaxes.clear()
    mpf.plot(self.pdDataframe_with_new_data, ax=myaxes)
    self.canvas.draw()
```

Let me know if this (or something similar) works.

**Comment by eliasseverholt** [comment]
@DanielGoldfarb
Hi!

Yup, that was it! Works like a charm.

Thank you very much!

**Comment by GeeteshMehto** [comment]
Hello sir, please assign this issue to me as i already worked on this kind of problem in past and has a great experience.
