### ISSUE TITLE
Adding markers to buying signals on plot

### ISSUE THREAD

**Issue by andreasklippinge** [matplotlib/mplfinance#562]
Hey all, 

Firstly, thanks Daniel for the development of this package - I really like it! 

I'm trying to implement markers in my plot for marking my buying/selling signals and did not quite understand/made it work from the documentation given. I have the following code: 
```
ticker = " ^omx "
df = yf.download(ticker, period = "1y", interval = "1d", progress = False, rounding = True)
close = df["Close"].values
df["Row"] = df.reset_index().index
rows = df["Row"]
x = rows
y = close
z = np.polyfit(x, y, 1)
p = np.poly1d(z)
df["Trendline"] = p(x)
df["linearreg"] = talib.LINEARREG(df["Close"],timeperiod=14)
df["stddev"] = talib.STDDEV(df["linearreg"],timeperiod=14)*2
short = df["Trendline"] + df["stddev"]
long = df["Trendline"] - df["stddev"]
df["Go short"] = np.where((df["Close"] > short),1,0)
df["Go long"] = np.where((df["Close"] < long),1,0)
slope = round(z[0],1)

buydates,selldates = [],[]
buyprice,sellprice = [],[]

for index,row in df.iterrows():
       if row["Go short"] == 1:
        buydates.append(index)
        buyprice.append(row["Close"])
        
    if row["Go long"] == 1:
        selldates.append(index)
        sellprice.append(row["Close"])
```
This code works for plotting the markers on a plt.plot as:
```
plt.figure(figsize=(15,15))        
plt.plot(df["Close"])
plt.scatter(df.loc[buydates].index,df.loc[buydates].Close,marker="v",color="r")
plt.scatter(df.loc[selldates].index,df.loc[selldates].Close,marker="^",color="g")
plt.show()
```
But I can't make it work on mpf.plot. I've tried just copying plt.scatter(*kwargs) as
```
mpf.make_addplot(df.loc[selldates].index,df.loc[selldates].Close,marker="^",color="g")
```
but since the make_addplot only takes 1 positional argument, I don't know how to proceed. 
So how do I create the markers in mpf.make_addplot(*kwargs) ? 

Many thanks in advance.

**Comment by GeeteshMehto** [comment]
Hello sir, please assign this issue to me as i already worked on this kind of problem in past and has a great experience.

**Comment by DanielGoldfarb** [comment]
@andreasklippinge 
Please read carefully and thoroughly through the [**entire addplot tutorial**](https://github.com/matplotlib/mplfinance/blob/master/examples/addplot.ipynb).   The tutorial explains exactly how to plot signals giving and example.  Key points to notice are:
1. the data passed into `mpf.make_addplot()` must be the same length as the data frame passed into `mpf.plot()`.   Any points in the addplot that are *not* meant to be plotted should contain the value `float('nan')`.
2. kwargs available to `mpf.make_addplot()` are shown throughout the tutorial by example.   One can also call function `mpf.kwarg_help()` or `mpf.kwarg_help('make_addplot')`.

After you have read carefully and thoroughly through the [**entire addplot tutorial**](https://github.com/matplotlib/mplfinance/blob/master/examples/addplot.ipynb) let me know if you still have questions.

**Comment by andreasklippinge** [comment]
@DanielGoldfarb 
I gave it another try and ended up with this code, which works!! 
```
df = pd.read_csv(r'C:\\Users\Andreas\Aktieanalys\dataset\^gdaxi.csv'
                 ,index_col=0,parse_dates=True)
close = df["Close"].values
df["Row"] = df.reset_index().index
rows = df["Row"]
x = rows
y = close
z = np.polyfit(x, y, 1)
p = np.poly1d(z)
df["Trendline"] = p(x)
df["linearreg"] = talib.LINEARREG(df["Close"],timeperiod=14)
df["stddev"] = talib.STDDEV(df["linearreg"],timeperiod=14)*2
short = df["Trendline"] + df["stddev"]
long = df["Trendline"] - df["stddev"]
df["Go short"] = np.where((df["Close"] > short),1,0)
df["Go long"] = np.where((df["Close"] < long),1,0)
slope = round(z[0],1)
r2 = round(r2_score(df["Close"],p(x)),2)
print("R^2 correlation is",r2)
def signal_above_stddev(Go_short,price):
    signal = []
    for date,value in Go_short.iteritems():
        if value > 0:
            signal.append(df["High"][date]*1.01)
        else:
            signal.append(np.nan)
    return signal          
def signal_below_stddev(Go_long,price):
    signal = []
    for date, value in Go_long.iteritems():
        if value > 0:
            signal.append(df["Low"][date]*0.99)
        else:
            signal.append(np.nan)
    return signal
short_signal = signal_above_stddev(df['Go_short'], df['Close'])
long_signal = signal_below_stddev(df['Go_long'], df['Close'])
apd = [mpf.make_addplot(short_signal,type='scatter',markersize=20,marker='v',color="r"),
        mpf.make_addplot(long_signal,type='scatter',markersize=20,marker='^',color="g"),
        mpf.make_addplot(short,type='line',panel=0, color='green'),
        mpf.make_addplot(long,type='line',panel=0, color='red'),
        mpf.make_addplot(df["Trendline"], type='line',panel=0, color='orange')
        ]
mpf.plot(df, type='candle', volume=True, tight_layout=False, style='yahoo', figsize=(20,12), ylabel='Closing price', returnfig=True, 
         addplot=apd, volume_panel=1, panel_ratios=(6,2))
```

![image](https://user-images.githubusercontent.com/96059069/196811068-e1446a05-aeff-4be4-b97c-788832934685.png)

Now I'm off trying to make sense of the backtesting package to see how well this strategy would pay off. 
Cheers!

**Comment by DanielGoldfarb** [comment]
@andreasklippinge 
Glad to hear it.  [That's a beautiful plot you've made](https://user-images.githubusercontent.com/96059069/196811068-e1446a05-aeff-4be4-b97c-788832934685.png).  Thanks for sharing it!
