### ISSUE TITLE
hlines between xmin and xmax

### ISSUE THREAD

**Issue by santiagohuerdo** [matplotlib/mplfinance#576]
Hi Daniel, I would need to be able to plot horizontal lines for the Fibonacci Pivots Pivots indicator. My first idea was to use mpf hlines, but this function doesn't come with the ability to delimit from where to where on the X axis. So, I had to use external axes with the matplotlib function hlines that brings xmin and xmax, the drawback is that it doesn't recognise the dates in the graph. Is there any practical solution for this?

`fig = mpf.figure(style='charles', figsize=(16,8))`
`chart = fig.add_subplot(2,1,1)`
`ewo = fig.add_subplot(2,1,2)`
`chart.hlines(y=3800, xmin='2021-12-01', xmax='2022-12-01', linewidth=2, color='red')`
`apds = [ mpf.make_addplot(df_merged['EWO_Std'], ax=ewo, ylabel='EWO (5-35)', type='bar', width=0.6, color=df_merged['EWO_Colors'].values)]`
`mpf.plot(df_merged, ax=chart,type='candle',marketcolor_overrides=df_merged['XTL_Colors'].values, addplot=apds,
         xrotation=10)`
`mpf.show()`

Thanks for your support
![Figure_1](https://user-images.githubusercontent.com/90464580/207222064-f58b82c9-7bf2-4644-9819-eb4862fab638.png)

**Comment by DanielGoldfarb** [comment]
If I understand your question, you should be able to do this *without* external axes mode.   Presently the `hlines` kwarg does not accept x-limits for the horizontal line.   However you can use the `alines` kwarg to draw a horizontal line between two specific datetimes on the x-axis.  [Try using `alines`](https://github.com/matplotlib/mplfinance/blob/master/examples/using_lines.ipynb) and let me know if that solves your problem.
