### ISSUE TITLE
I have to create a plot like this on the live candle stick plot I have created. and it needs to be updated in realtime as the news candles are formed. Can anyone help me out here ? 

### ISSUE THREAD

**Issue by sachinn03** [matplotlib/mplfinance#577]
![image](https://user-images.githubusercontent.com/36417253/208880210-ae72b1d4-9240-44f8-aad6-c0c3e1aa9b09.png)

**Comment by DanielGoldfarb** [comment]
Please show your code.   Then can advise how to make it update real-time.

**Comment by sachinn03** [comment]
Thanks @DanielGoldfarb , I am facing issue in plotting those trendlines as they are in the image.

It is a tradingview indicator .

https://www.google.com/amp/s/www.tradingview.com/script/IYL88A1N-Trendlines-with-Breaks-LUX/%3famp

Here's the link 

I am getting the stock data from yfinance and I am using it to update my chart in real time , the charts are done

Now I want to plot this indicator on my mplfinance animated chart
