### ISSUE TITLE
legend

### ISSUE THREAD

**Issue by Enming-Zhou** [matplotlib/mplfinance#581]
Does mplfinance have the function of adding legends? For example, the legends of MA5, MA20, MA60.

**Comment by DanielGoldfarb** [comment]
@Enming-Zhou   mplfinance does not yet *directly* support legends (for example with a `legend` kwarg).  

However legends can be implemented using matplotlib's `returnfig` kwarg to [gain access to the mplfinance Axes objects.](https://github.com/matplotlib/mplfinance/wiki/Acessing-mplfinance-Figure-and-Axes-objects)

## [**Click here for more detailed information about implementing legends.**](https://github.com/matplotlib/mplfinance/issues/181)





.
.  
([some additional info also here](https://github.com/matplotlib/mplfinance/issues/497).)
