### ISSUE TITLE
Possible to adjust line width?

### ISSUE THREAD

**Issue by ghost** [matplotlib/mplfinance#613]
The default plotting of lines is a bit thick, and I can't seem to find out how to adjust it (type=line plots). Please let me know if it's possible.

BTW this library is awesome, thank you for maintaining it.

**Comment by DanielGoldfarb** [comment]
Read carefully through [**this tutorial**](https://github.com/matplotlib/mplfinance/blob/master/examples/widths.ipynb) and let me know ifthat answers your question.
