### ISSUE TITLE
different time interval

### ISSUE THREAD

**Issue by gbmax** [matplotlib/mplfinance#616]
Thanks Daniel for this charming work.
After exercizing basic tutorial, I managed to make basic plot, candle chart.
I am trying to show intraday candle chart with various interval, but with no success till now.
If I set interval longer, number of candles become lesser and graph shows not with full sized figure.
I searched here and matplotlib materials, but not easy to find out appropriate one.
Can I get solution?
Images and symptoms are below.

program flow:
	1. make_data()         # construct 1st plot data
	2. Graph.draw_1st()    # call 1st plot
	3. then, user can select other seconds interval(code not shown),
	4. press space key
	5. make_data() for new seconds interval
	6. call draw_next() with new data
### ****************************
Relevant code snippets are as follows.
(I am sorry, code formatting is not familiar with me...)
### preparing apds data
#
 def make_data():

      # apds0 : for ax0(panel0)
      apds0 = [mpf.make_addplot(candles['ma5_'], width=1.1, color='brown', secondary_y=False),      # 이평선
              mpf.make_addplot(candles['ma20_'], width=1.1, color='gold', secondary_y=False),
            ]

    # apds1 : for ax1(panel1)
    apds1 = [
        mpf.make_addplot(candles['buy5'], color='r', type='line', width=1.1),
    ]
    return [apds0, apds1]

### plot class

class Graph:
#
      def __init__(self, bd, org_sec, make_data):
          self.yticks = ticker.MaxNLocator(10)
          self.hlines=dict(hlines=[0, 10],colors=['b', 'g'],linestyle='--', linewidths=1.3)
          mc = mpf.make_marketcolors(up='red',down='blue', edge={'up':'red','down':'blue'}, wick={'up':'red','down':'blue'})
          style = mpf.make_mpf_style(marketcolors=mc, gridstyle=':', rc={'axes.grid':True, 'font.family' : ['Gulim'] })
          self.layout=dict(style=style, panel_ratios=(1,0.3),figratio=(1,0.5),figscale=1.0)
          self.padding = dict(scale_padding = {'left': 0.5, 'top': 1, 'right': 1, 'bottom': 1}, tight_layout = True)

    # prepare data for panel1, panel2
    def prepare_data(apds):
        apds_ = []
        for i in range(len(apds)):
            if len(apds[i]):
                for apd in apds[i]:
                    ax = {'panel':i} if not hasattr(self, 'fig') else {'ax': self.axes[i * 2]}
                    apd.update(**ax)
                    apds_.append(apd)
        ax1_setup = dict(type='candle', axtitle=title, hlines=self.hlines)
        ax1_setup = {**ax1_setup, **self.layout}
        return apds_, ax1_setup, title

    # set x axis tick and labels
    def after_gph(self, misc, df):
        ticks = []
        tlabs = []
        ts = df.index[0]    # xtick start point
        interval = 20       # 20 minutes interval.

        while ts <= df.index[-1]:
            df_temp = df.loc[df.index <= ts, :]
            ticks.append(df.index.get_loc(df_temp.index[-1]))
            tlabs.append(ts.strftime('%H:%M'))
            import datetime
            ts = ts + datetime.timedelta(minutes=interval)    # next 20 minutes

        self.axes[-2].set_xticks(ticks)
        self.axes[-2].set_xticklabels(tlabs, ha='center', rotation=70)
        return

    # first plot
    def draw_1st(self, candles, apds, title, misc, candles_spec, code_date):
        # prepare panel data
        apds_, ax1_setup, title = self.prepare_data(apds, title, candles_spec)  
        self.fig, self.axes = mpf.plot(candles, addplot=apds_, **ax1_setup,  returnfig=True)
        
        self.axes[0].tick_params(axis='y', labelsize= 'small')
        self.axes[2].tick_params(axis='y', labelsize= 'small')
        self.axes[0].yaxis.set_major_locator(self.yticks)
        self.axes[2].yaxis.set_major_formatter(StrMethodFormatter('{x:,.0f}'))
        
        self.axes[-2].tick_params(axis='x', labelsize= 'small')

        # set x axis ticks
        self.after_gph(misc, candles)    
        
        # event callback for successive plot
        self.fig.canvas.mpl_connect('key_press_event', self.space_bar)
        plt.pause(0.1)
        mpf.show()

    # successive plot routine
    def draw_next(self, candles, apds, title, misc, candles_spec, code_date):
        apds_, ax1_setup, title = self.prepare_data(apds, title, candles_spec)

        for ax in self.axes:    # clear existing axes
            ax.clear()
        mpf.plot(candles, ax=self.axes[0], addplot=apds_, **ax1_setup)
        self.after_gph(misc, candles)
        mpf.show()

    # successive plot callback function 
    def space_bar(self, event):
        if event.key == ' ':
            self.redraw_fcn()
    # construct plto data and call draw_next
    def redraw_fcn(self, code_date=''):
        make_data()
        self.draw_next()

### operation starts here
make_data()         # construct 1st plot data
Graph.draw_1st()    # call 1st plot

![2023-05-17 19_10_47-Figure 1](https://github.com/matplotlib/mplfinance/assets/61690615/e74b7390-1974-437c-a992-6e2230bd1a8b)
![2023-05-17 19_11_06-Figure 1](https://github.com/matplotlib/mplfinance/assets/61690615/c052b190-f1f0-4928-b44a-17a376bc573e)

https://github.com/matplotlib/mplfinance/assets/61690615/bc2d53c6-7356-4228-8314-8a0b0ddad437

**Comment by DanielGoldfarb** [comment]
> If I set interval longer, number of candles become lesser and graph shows not with full sized figure.
I searched here and matplotlib materials, but not easy to find out appropriate one.

It's not clear to me ***what you want to happen*** when you change the interval.  

Do you *want* fewer candles for larger intervals?  In other words, does `40s` mean one candle for every 40 seconds, and `120s` means one candle every 120 seconds?

Or is it that case that you always want the same number of candles, but you want to see different numbers of **tick marks**, so that the tick marks change from one tick mark every 40 seconds, to one tick mark every 120 seconds?

It would be helpful also to show or post your data somewhere, as a csv file.

**Comment by gbmax** [comment]
Sorry for the insufficient explanation.
Purpose is to see the data of the same code and date differently.
In other words, 300s (seconds) is simply resampled data of  40s (seconds) data.
Viewing the 300s candle data, unlike the 40s data, it is  not good to see because it is displayed in a small size, not displayed in the entire figure space.
I also tried with only candle data, no apds, no volumes, not successful.
Data is as attached.
Thanks alot.
[40s_300s.zip](https://github.com/matplotlib/mplfinance/files/11512727/40s_300s.zip)

**Comment by DanielGoldfarb** [comment]
*It's very difficult to isolate the problem because you are not showing all of your code.*   In particular I don't see where/how `candles` is being set and/or whether at any point it is being modified.   

In general, we programmers have a tendency to make assumptions as to where a problem might be.  If we can't find the problem based on that, then there is a good chance our assumption is wrong, and the problem is likely to be in the code that we are ignoring and/or not showing.

That said, I suspect that the problem may have something to do with the `DatetimeIndex` of the `candles` dataframe.  The `DatetimeIndex` is used to set the x-axis of the plot, and it appears that the `DatetimeIndex` being used in your plots may always be that for the `40s` data, even when plotting `120s` data or `300s` data, etc.

[**Are you using Pandas to resample the data?**](https://github.com/matplotlib/mplfinance/wiki/Resampling-Time-Series-Data-with-Pandas#2-existing-ohlcv-data-to-new-ohlc-data)  If not, then you should, since it will certainly give you a correct `DatetimeIndex`.

**Comment by gbmax** [comment]
Sorry, I am not familiar with this kind of asking.
It is hard to think problem with reader's perspective.
Whole code is pretty long and complex, there are much of irrevant codes, so I was not sure to explain the issue by code.
So I rewrote self-running code to reveal the issue as compact as possible.
Fortunately(unfortunately) it works fine(40S candles and 300S candle shows in the full figure).
So I can go forward from this code snippet to what I am trying to implement.
My apology and thanks again for your kind consideration.

gb.

Below is what I'v tested with previous data.
with space bar, it shows 40S and 300S graph successively.

```
#%%
import sys,os
import pandas as pd
import mplfinance as mpf
import matplotlib.pyplot as plt

#%%
data_40S = pd.read_csv('40S.csv')
data_40S['time'] = pd.to_datetime(data_40S['time'])
data_300S = pd.read_csv('300S.csv')
data_300S['time'] = pd.to_datetime(data_300S['time'])

data_40S.set_index('time', drop=True, inplace=True)
data_300S.set_index('time', drop=True, inplace=True)
from itertools import cycle         
pool = cycle(['data_40S', 'data_300S'])

#%%
import mplfinance as mpf

class Graph:
    def __init__(self, fcn):
        self.data_fcn = fcn
        self.padding = dict(scale_padding = {'left': 0.5, 'top': 0.5, 'right': 0.5, 'bottom': 0.5}, tight_layout = True)
        plt.ioff()
    
    # prepare apds data
    def prepare_data(self, apds, title):
        apds_ = []
        for i in range(len(apds)):
            if len(apds[i]):
                for apd in apds[i]:
                    ax = {'panel':i} if not hasattr(self, 'fig') else {'ax': self.axes[i * 2]}
                    apd.update(**ax)
                    apds_.append(apd)
        ax1_setup = dict(type='candle', axtitle=title)
        return apds_, ax1_setup

    # gph.draw_1st
    def draw_1st(self, candle, apds, title):
        apds_, ax1_setup = self.prepare_data(apds, title)
        self.fig, self.axes = mpf.plot(candle, type='candle', addplot=apds_, axtitle=title, figscale=1.5, returnfig=True)
        self.axes[0].tick_params(axis='y', labelsize= 'small')

        self.fig.canvas.mpl_connect('key_press_event', self.space_bar)  # define successive draw event
        plt.pause(0.1)
        mpf.show(block=True)
    
    # successive frawing.
    def draw_next(self, candle, apds, title):
        apds_, ax1_setup = self.prepare_data(apds, title)

        for ax in self.axes:    
            ax.clear()
        mpf.plot(candle, ax=self.axes[0], type='candle', addplot=apds_, axtitle=title, figscale=1.5)
        plt.pause(0.1)
        mpf.show(block=True)

    # draw successive graph with space bar
    def space_bar(self, event):
        if event.key == ' ':
            df, apds, data_str = make_data()
            gph.draw_next(df, apds, data_str)

#%%
def make_data():
    data_str = next(pool)   # next data
    df = eval(data_str)
    df['ma5'] = df['close'].rolling(5).mean()
    df['ma20'] = df['close'].rolling(20).mean()

    apds0 = [
            mpf.make_addplot(df['ma5'], width=1.3, color='g', secondary_y=False),
            ]

    apds1 = []
    apds1= [
        mpf.make_addplot(df['ma20'], color='r', width=0.6),
    ]
    return df, [apds0, apds1], data_str

gph = Graph(make_data)
df, apds, data_str = make_data()
gph.draw_1st(df, apds, data_str)
# %%

```

**Comment by DanielGoldfarb** [comment]
I am glad to hear that it is working for you now.  Often simplifying the code helps to find, or remove, the issue.
