### ISSUE TITLE
Create `conda install` for `mplfinance`

### ISSUE THREAD

**Issue by DanielGoldfarb** [matplotlib/mplfinance#62]
Please create a `conda install` for `mplfinance`.

**Comment by kevinashaw** [comment]
Many thanks for taking over the repo!

**Comment by DanielGoldfarb** [comment]
@kevinashaw 
Kevin,
  Thanks for the appreciation.   Are you able to help with this one?   If not, I will get to it eventually.  I just have to read the documentation on how to create and publish a conda install package.  Working on some other enhancements first.
   All the best.  --Daniel

**Comment by kcowgill** [comment]
@DanielGoldfarb you can create a conda recipe by typing:
`conda skeleton pypi mplfinance`
which will leave you with a meta.yaml file based on the currently available version on pypi that you can tweak slightly - attached is what I've recently created (github file upload prevents a .yaml file):
[meta.txt](https://github.com/matplotlib/mplfinance/files/4394480/meta.txt)

I'm unfamiliar with publishing packages to public conda channels, but hopefully this can help to get you started.

**Comment by DanielGoldfarb** [comment]
@kcowgill 
Kent,
   Thanks.  I will take a look and follow up.
    All the best.  --Daniel

**Comment by tacaswell** [comment]
I suggest submitting the recipe to conda-forge (see https://github.com/conda-forge/staged-recipes) .  They have the machinery in place to build and upload the packages and a bot that auto-updates the recipe when you create a new tag.

**Comment by DanielGoldfarb** [comment]
@tacaswell 
Tom,  Thanks will definitely do that (when I get to this).  I had noticed that matplotlib is on the conda-forge channel.  Thanks,.  --Daniel

**Comment by B00mGit** [comment]
Hi @DanielGoldfarb,
I was just wondering if the conda pkg was on the horizon...?
Thx

**Comment by DanielGoldfarb** [comment]
I started playing with this today.  It's on anaconda cloud now: https://anaconda.org/DanielGoldfarb/mplfinance

install with `conda install -c danielgoldfarb mplfinance` works.  

**Does anyone know how I can set it up so that it installs from one of the ***default channels***, so that users can type simply:
`conda install mplfinance` ?**

**Comment by DanielGoldfarb** [comment]
**https://github.com/ContinuumIO/anaconda-issues/issues/12151#issuecomment-728298740**

**Comment by DanielGoldfarb** [comment]
https://anaconda.org/conda-forge/mplfinance
