### ISSUE TITLE
Bug Report: Is there a typo in src/mplfinance/plotting.py, line 946: fig.suptitle(title,**title_kwargs)

### ISSUE THREAD

**Issue by ngterry** [matplotlib/mplfinance#644]
Is there a typo in src/mplfinance/plotting.py, line 946: fig.suptitle(title,**title_kwargs)? Should it be subtitle instead?

**Comment by DanielGoldfarb** [comment]
No.  [It's **sup**title](https://matplotlib.org/stable/api/figure_api.html#matplotlib.figure.Figure.suptitle).

See also [here](https://matplotlib.org/stable/gallery/subplots_axes_and_figures/figure_title.html).
