### ISSUE TITLE
Bug Report: marketcolors display error when open=close

### ISSUE THREAD

**Issue by nkta3m** [matplotlib/mplfinance#658]
**Describe the bug**
i set  my_color = mpf.make_marketcolors( up="red",down="green",volume="in", inherit=True)

but plot draw green bar when open=close, and open price higher than previous day close.

**Expected behavior**
Display colors correctly

**Screenshots**
![001324](https://github.com/matplotlib/mplfinance/assets/13484700/df4ca794-832c-404a-8297-6a13b8ec565e)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [firefox]
 - Version [mplfinance         0.12.10b0]

**Additional context**

**Comment by DanielGoldfarb** [comment]
This is ***not*** a bug.   

By definition, the colors on traditional candlestick charts depend ***only*** on the change from the Open to the Close.  Previous prices have no affect on candlestick color when using *traditional* candlestick charts.

However "hollow and filled" candlesticks ***do*** look at the previous price:  [**Click here for more information**](https://github.com/matplotlib/mplfinance/blob/master/examples/hollow_and_filled_candles.ipynb).
