### ISSUE TITLE
Bug Report: Typo

### ISSUE THREAD

**Issue by aidenkwong** [matplotlib/mplfinance#659]
**Describe the bug**
mplfinance/plotting.py", line 946, in plot
    fig.suptitle(title,**title_kwargs)
    ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'suptitle'

**Comment by DanielGoldfarb** [comment]
This is ***not*** a bug or typo.   [**`Figure.suptitle()`** does exist (click here)](https://matplotlib.org/stable/api/figure_api.html#matplotlib.figure.Figure.suptitle).

If you show your code then I can perhaps determine what you are doing wrong.
