### ISSUE TITLE
The example image of price-movement_plots.ipynb is inconsistent with the displayed result.

### ISSUE THREAD

**Issue by Minor-babe** [matplotlib/mplfinance#665]
I use mplfinance to generate PNF charts, referring to the example in price-movement_plots.ipynb.
I downloaded the SPY_20110701_20120630_Bollinger.csv file as the data source.
My code is as follows:

import mplfinance as mpf
import pandas as pd

daily = pd.read_csv('SPY_20110701_20120630_Bollinger.csv',index_col=0,parse_dates=True)
daily.index.name = 'Date'
mpf.plot(daily, type='pnf')

Based on the result image provided in price-movement_plots.ipynb, my expected output should look like this:
![2024-04-01 16-14-49](https://github.com/matplotlib/mplfinance/assets/52151314/2f54146a-cf22-45b5-bdf6-c39b01216d3e)

But actually, the image I get is:
![Figure_1](https://github.com/matplotlib/mplfinance/assets/52151314/64e91b5b-aa39-4e9c-b9d4-05e542d98d67)

my mplfinance version: v0.12.10b0.

Please inform me, what caused this? Did the data change?

**Comment by DanielGoldfarb** [comment]
I re-ran the price-movement_plots.ipynb notebook on my local machine and I am getting a plot that matches yours.  I believe this is the correct plot:

![image](https://github.com/matplotlib/mplfinance/assets/11164790/0ff61632-6c3f-46d6-af0c-3e8fb938b982)

**Comment by DanielGoldfarb** [comment]
I just updated the repository with the regenerated price-movements notebook.
