### ISSUE TITLE
Custom Candlestick Timeframe

### ISSUE THREAD

**Issue by pije76** [matplotlib/mplfinance#675]
Can I create my own custom candlestick by using mplfinance?
I want to create custom candlestick chart by using the data from lower timeframe (example: Hourly or Daily) and then create my custom Weekly or Monthly chart based on the specified date-frame from user input, example: from 15 May to 20 May (6 calendar days).

**Comment by DanielGoldfarb** [comment]
@pije76 -
Yes, you can do this.  But you do this with Pandas.   Mplfinance simply plots candlesticks the OHLCV data that you pass in, whether the candles are every 15 minutes, or hourly, or daily, weekly, etc.

You can change the frequency of your candles using Pandas DataFrame **resample** functionality.  See the following links for further details:

- [mplfinance daily to weekly resample example](https://github.com/matplotlib/mplfinance/blob/master/examples/scratch_pad/pandas_resample_test.ipynb)
- [resampling frequencies available](https://github.com/matplotlib/mplfinance/wiki/Resampling-Time-Series-Data-with-Pandas#resampling-options)
- [mplfinance general pandas resampling documentation](https://github.com/matplotlib/mplfinance/wiki/Resampling-Time-Series-Data-with-Pandas)
- [see also](https://github.com/matplotlib/mplfinance/wiki/Resampling-Time-Series-Data-with-Pandas#see-also)

**Comment by pije76** [comment]
> @pije76 - Yes, you can do this. But you do this with Pandas. Mplfinance simply plots candlesticks the OHLCV data that you pass in, whether the candles are every 15 minutes, or hourly, or daily, weekly, etc.
> 
> You can change the frequency of your candles using Pandas DataFrame **resample** functionality. See the following links for further details:
> 
> * [mplfinance daily to weekly resample example](https://github.com/matplotlib/mplfinance/blob/master/examples/scratch_pad/pandas_resample_test.ipynb)
> * [resampling frequencies available](https://github.com/matplotlib/mplfinance/wiki/Resampling-Time-Series-Data-with-Pandas#resampling-options)
> * [mplfinance general pandas resampling documentation](https://github.com/matplotlib/mplfinance/wiki/Resampling-Time-Series-Data-with-Pandas)
> * [see also](https://github.com/matplotlib/mplfinance/wiki/Resampling-Time-Series-Data-with-Pandas#see-also)

Thank you so much for the information @DanielGoldfarb 
I will try it.
