### ISSUE TITLE
Point and Figure Chart Type

### ISSUE THREAD

**Issue by coffincw** [matplotlib/mplfinance#68]
Another chart type similar to Renko Plots, are Point and Figure charts.  They also don't take into account the passage of time. I think this chart type would be a good addition to the package.  

Information:
https://www.dummies.com/personal-finance/investing/technical-analysis/how-to-create-a-point-and-figure-chart-of-trading-prices/
https://www.investopedia.com/terms/p/pointandfigurechart.asp

Existing Code:
https://stackoverflow.com/questions/8750648/point-and-figure-chart-with-matplotlib

If an option, I'd like to work on this feature.

**Comment by DanielGoldfarb** [comment]
go for it!  thanks!
