### ISSUE TITLE
Plot always in new figure

### ISSUE THREAD

**Issue by Mangilu** [matplotlib/mplfinance#683]
I create the main candlestick plot here:
mpf.plot(df.loc[start_date:end_date], type='candle', style='charles', title='Candlestick Chart', returnfig=True)

Then I create two indicators, within a loop, with addplot:
add_plot = mpf.make_addplot(fit_df['FitLine'], color='blue', linestyle='--', width=2.5)
marker_addplot = mpf.make_addplot(marker_df['MarkerValue'], type='scatter', markersize=100, color='orange', marker='o')

But when I add them to the main plot
mpf.plot(df.loc[start_date:end_date], addplot=[add_plot, marker_addplot], style='charles')

The loop plot is displayed correctly but always in a new figure.
I can't understand what could be the problem.

**Comment by OneManShow0815** [comment]
You need to list your full code, with these 3 lines, no one can imagine where the problem is.
