### ISSUE TITLE
Volume graph's peak Y-axis is too high

### ISSUE THREAD

**Issue by fintron** [matplotlib/mplfinance#75]
Sometimes the Volume subchart's peak y-axis is too high compared to the peak volume.

Here's an example: 

![image](https://user-images.githubusercontent.com/62899768/77939847-a0523d00-726c-11ea-9212-373854251029.png)

The peak volume was ~30k. It's reasonable to stop the peak volume around 40k, but the chart above goes up to almost 60k. This wastes space in the chart and makes it harder to read the existing volume bars.

**Comment by DanielGoldfarb** [comment]
This is strange.   [The code specifically sets the upper limit on the yaxis to 1.1 * max(volumes).](https://github.com/matplotlib/mplfinance/blob/master/src/mplfinance/plotting.py#L331-L335)
Will have to investigate why that doesn't seem to be working as expected here.  

***Can you please provide the data, and code, that were used to generate this plot?***

**Comment by fintron** [comment]
Here's the sample:
[sample.csv.zip](https://github.com/matplotlib/mplfinance/files/4405613/sample.csv.zip)

code:
```
df = pd.read_csv('sample.csv', index_col=0, parse_dates=True)
mpf.plot(df, type='line', volume=True)
```

**Comment by DanielGoldfarb** [comment]
In your sample file, out of almost 2300 data points, there are 4 large numbers:

timestamp | Open | High | Low | Close | Volume
-- | -- | -- | -- | -- | --
2020-01-02   09:30:00-05:00 | 1341.55 | 1347.28 | 1341.55 | 1347.01 | 53112
2020-01-07 09:30:00-05:00 | 1397.94 | 1397.94 | 1393.29 | 1395.52 | 44491
2020-01-03 15:59:00-05:00 | 1360.09 | 1362.23 | 1359.48 | 1359.49 | 40712
2020-01-06 12:05:00-05:00 | 1386.4519 | 1387.415 | 1386.4519 | 1387.415 | 39615

I don't have time now to play with it myself, but I suspect that, given the resolution of your plot, and the large number of data points (2295), you are unable to see these four outliers on the plot.  

You could play with the zoom, and/or set kwarg `figscale=2.5` maybe, to be able to actually see them on the plot.  At any rate, it appears that the one point at 5311 is what is setting `ymax`  to over 5800.

Please let me know if that solves your problem.

**Comment by DanielGoldfarb** [comment]
Btw, it is normal and behaving as expected to have some space on the left before the first data point, and some on the right after the last.  This was mentioned once before. This is standard practice generally for plotting.  However if it's regarded as too much (i think it's about right) or if there is enough demand for an option to have the first and last data point _exactly_ at the left and right axes, we can consider adding that as an option.

**Comment by DanielGoldfarb** [comment]
![before_zoom](https://user-images.githubusercontent.com/11164790/77982753-12fa0180-72db-11ea-9b97-1548afb7b4d4.jpg)

**Above is plot before zoom.   Below using the magnifying glass zoom feature on the plot, shows the high volume at the beginning that is resonsible for the high y-axis limit on the lower subplot.  The single volume bar is so narrow with this much data, and happens to line up very close or in-line with one of the grid lines, that it cannot be seen when zoomed out.

![zoomed](https://user-images.githubusercontent.com/11164790/77982760-18574c00-72db-11ea-92fa-067a4f9c5f36.jpg)

**Plotting only the first day also makes it easy to see the one, very high volume:**

    mpf.plot(df.loc[:'2020-01-02',:], type='line', volume=True)#, figscale=2.25)

![image](https://user-images.githubusercontent.com/11164790/77983064-fca07580-72db-11ea-926c-df1445c7b0ef.png)

**Comment by DanielGoldfarb** [comment]
@fintron - Thank you very much for providing the data and the code.  That made it much easier to find the issue.

**Comment by fintron** [comment]
@DanielGoldfarb - thanks for your help!

> However if it's regarded as too much (i think it's about right) or if there is enough demand for an option to have the first and last data point exactly at the left and right axes, we can consider adding that as an option.

That would be nice to have as an option!

**Comment by fintron** [comment]
@DanielGoldfarb - it could be nice to support aggregating volume in the plot below. For example, if the graph is in minutes but that’s too fine for the volume, maybe just plot aggregates of 5 minutes in the volume graph below?

**Comment by DanielGoldfarb** [comment]
So you would want to aggregate the volumes to 5 mins, but leave the OHLC at 1 min??  

Certainly it is easy to aggregate both using Pandas as noted in #19 and [demonstrated here](https://github.com/matplotlib/mplfinance/blob/master/examples/scratch_pad/pandas_resample_test.ipynb).  However there is a basic assumption in the code that volume and prices (which share the x-axis) have the same periodicity, but possiblely if I can break that assumption without over complicating the code I would consider it.  It's an interesting idea, but I also wonder how often people would want it.  Personally if I were to aggregate the volumes, I would probably want to aggregate the prices so that my open,high,low, and close apply to the same 5 minute intervals (which as noted above can be done easily with Pandas resample).
