### ISSUE TITLE
Save does not close figures

### ISSUE THREAD

**Issue by fxhuhn** [matplotlib/mplfinance#86]
If it try to create and save a set of figures, i get the following warning message:

plotting.py:173: RuntimeWarning
More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  fig = plt.figure()

This should not be the case when saving the images directly. Or is this a mistake on my side? How i have to close these?

**Comment by tacaswell** [comment]
Managing the life cycle of Figures can sometimes be tricky.  On one hand having figures get garbage collected under the user is not greate, so in Matplotlib we hold references to the figures when they are created, but that causes the problem you are having now where you are essentially leaking figures.

When you are done with a figure you can do `plt.close(fig)` to discard it or do `plt.close('all')` to close all open Figures and drop the internal Matplotlib references to them.

**Comment by fxhuhn** [comment]
Hi @tacaswell ,
thanks, i will try it as follows:
```
import matplotlib.pyplot as plt
...
plt.close('all')
```
