### ISSUE TITLE
No module named 'mplfinance'

### ISSUE THREAD

**Issue by dchou1618** [matplotlib/mplfinance#9]
In Jupyter, ran !pip install mplfinance and import mplfinance as mpf, but resulted in above error

**Comment by DanielGoldfarb** [comment]
Please provide the output cell from your `!pip install mplfinance` ?
Also, what operating system are you running?
What versions of jupyter, python, and pip are you running?

I just tried reproducing this and it worked fine for me.

**Comment by DanielGoldfarb** [comment]
@dchou1618 -- please provide the diagnostic information requested above in my previous comment.   

In addition to that, please also include the output from the following:

    import sys
    print(sys.path)

All of this information will enable me to help you with this problem.  Thank you so much.  --Daniel

**Comment by dchou1618** [comment]
Output cell from !pip install mplfinance: 

`DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Requirement already satisfied: mplfinance in /usr/local/lib/python2.7/site-packages (0.11.1a1)
Requirement already satisfied: pandas in /usr/local/lib/python2.7/site-packages (from mplfinance) (0.24.2)
Requirement already satisfied: matplotlib in /usr/local/lib/python2.7/site-packages (from mplfinance) (2.2.3)
Requirement already satisfied: python-dateutil>=2.5.0 in /usr/local/lib/python2.7/site-packages (from pandas->mplfinance) (2.7.5)
Requirement already satisfied: numpy>=1.12.0 in /usr/local/lib/python2.7/site-packages (from pandas->mplfinance) (1.16.5)
Requirement already satisfied: pytz>=2011k in /usr/local/lib/python2.7/site-packages (from pandas->mplfinance) (2019.1)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python2.7/site-packages (from matplotlib->mplfinance) (2.3.0)
Requirement already satisfied: backports.functools-lru-cache in /usr/local/lib/python2.7/site-packages (from matplotlib->mplfinance) (1.5)
Requirement already satisfied: subprocess32 in /usr/local/lib/python2.7/site-packages (from matplotlib->mplfinance) (3.5.3)
Requirement already satisfied: six>=1.10 in /usr/local/lib/python2.7/site-packages (from matplotlib->mplfinance) (1.12.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python2.7/site-packages (from matplotlib->mplfinance) (1.0.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python2.7/site-packages (from matplotlib->mplfinance) (0.10.0)
Requirement already satisfied: setuptools in /usr/local/lib/python2.7/site-packages (from kiwisolver>=1.0.1->matplotlib->mplfinance) (41.0.0)`

Operating System: macOS Mojave Version 10.14.6

Jupyter Version: 5.7.4
Python Version: 2.7.16
Pip Version: 19.3.1

Output from import sys:

`['/Users/dylanc_home/Desktop/options', '/Library/Frameworks/Python.framework/Versions/3.7/lib/python37.zip', '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7', '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload', '', '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages', '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/bs4-0.0.1-py3.7.egg', '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/crypto-1.4.1-py3.7.egg', '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium-3.141.0-py3.7.egg', '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/identicon-1.0-py3.7.egg', '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/PyAudio-0.2.11-py3.7-macosx-10.9-x86_64.egg', '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/google_cloud_language-1.2.0-py3.7.egg', '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/networkx-2.3-py3.7.egg', '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/gspread-3.1.0-py3.7.egg', '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/oauth2client-4.1.3-py3.7.egg', '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/httplib2-0.12.1-py3.7.egg', '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/loading-0.0.1-py3.7.egg', '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/wordninja-0.1.5-py3.7.egg', '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/image-1.5.27-py3.7.egg', '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pydotplus-2.0.2-py3.7.egg', '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/arff-0.9-py3.7.egg', '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tensorflow_hub-0.6.0-py3.7.egg', '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pytesseract-0.3.0-py3.7.egg', '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/scikit_image-0.16.2-py3.7-macosx-10.9-x86_64.egg', '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/imageio-2.6.1-py3.7.egg', '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/PyWavelets-1.1.1-py3.7-macosx-10.9-x86_64.egg', '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/plotly-4.4.1-py3.7.egg', '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/mpl_finance-0.10.0-py3.7.egg', '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/mplfinance-0.11.1a1-py3.7.egg', '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/chart_studio-1.0.0-py3.7.egg', '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/IPython/extensions', '/Users/dylanc_home/.ipython']`

**Comment by DanielGoldfarb** [comment]
@dchou1618 - Thank you.  
As you can see here on this page https://matplotlib.org/3.1.1/users/installing.html 
about half way down the page:

    Matplotlib requires the following dependencies:
    Python (>= 3.6) 
    ...

Thus also `mplfinance`, which requires `matplotlib`, also requires `Python 3.6` or greater. 

The strange thing  is, it appears from your printout of `sys.path` that perhaps `3.7` is installed on your machine, yet you appear to be running Python 2.7 in your jupyter notebook.   (note: you may need to use `pip3` to install mplfinance, or run pip under python 3).  When you click on 'New' in Jupyter, make sure you have a choice for a new `Python 3` notebook.   Your problem should resolve itself under Python 3.   Let me know if you need further assistance.

**Comment by DanielGoldfarb** [comment]
@dchou1618  you may want to check also whether you have a separate `pip3` command on your machine (that runs pip under Python 3 instead of 2) and, if so, try installing using pip3.

**Comment by DanielGoldfarb** [comment]
10 days with no repsonse.  Appears to me user and/or environment error (pip install is issuing DEPRECATION message for Python 2.7).
