### ISSUE TITLE
Change linecolor of addPlot

### ISSUE THREAD

**Issue by fxhuhn** [matplotlib/mplfinance#95]
Hi there,
is there a way, to change the color of the line if i use the addplot method?
Siminlar to my example with **linecolor**:

```
mpf.make_addplot(stock['signals'] * 0.99,
                                                scatter=True,
                                                markersize=100,
                                                marker='^',
                                                **linecolor='green'**)
```

**Comment by DanielGoldfarb** [comment]
Yes, just use the `color=` kwarg when calling `mpf.make_addplot()`

You can see an example in cell '`In [15]`' **[in the addplot notebook](https://github.com/matplotlib/mplfinance/blob/master/examples/addplot.ipynb)**

**Comment by fxhuhn** [comment]
ah ok, color instead of line color. My fault. 
Is there also a link available what kind of color names a possible? I see in 15/16 'g' and in 18 'orange.'

**Comment by DanielGoldfarb** [comment]
Just google "matplotlib colors"

Also, https://matplotlib.org/3.1.0/gallery/color/named_colors.html

**Comment by DanielGoldfarb** [comment]
> ah ok, color instead of line color.

It's a little confusing, but in the `mpf.plot()` API, color could refer to candle colors, up/down colors, edge colors, etc. so we made the kwarg `linecolor` to indicate that it only applies to type=line, `mpf.plot(df,type=line)`

But in `mpf.make_addplot()`, there is only one color, so ...

kwarg `color` is the matplotlib standard, so it is `linecolor` that is contrary, but as I said it was to imply that linecolor only applies to a `type=line` plot.  I am open to suggestions to make it less confusing.

**Comment by fxhuhn** [comment]
Yeah, that makes sense. 
For me it would have been easier to offer the parameters in the request instead of working with kwargs. But this is my personal view.

I have learned that `_valid_addplot_kwargs():` is my friend in this case :-)

**Comment by DanielGoldfarb** [comment]
> I have learned that `_valid_addplot_kwargs():` is my friend in this case :-)

Yeah, that's the idea behind the "valid kwargs" dicts in the code.  They validate the kwargs, provide default values for them ***and at the same time become the documentation for all available kwargs.***   HTH.   All the best.  --D.
